### ISSUE TITLE
[UF5] AppController says "safe to be deleted", but this breaks 4 routes

### ISSUE THREAD

**Issue by StrykeSlammerII** [alexweissman/UserFrosting#1241]
AppController class in the skeleton says it is "safe to be deleted", but doing so causes errors similar to `Fatal error: Uncaught RuntimeException: Named route does not exist for name: index in /home/strike/Frosting/UF5-native/vendor/slim/slim/Slim/Routing/RouteCollector.php`
chat link: https://chat.userfrosting.com/channel/support?msg=pCkTbS8m33m64qSjH

`/`, `/legal`, `/about`, and `/privacy` are the affected routes.

Most full sites will want to provide their own pages here, but dependent sprinkles should be able to use the defaults without including or overriding AppController.

**Comment by lcharette** [comment]
To fix, it should be documented in the skeleton that while these Controllers are safe to be deleted, there's also another step to delete the route.

Plus, `index` name route should not be required / hardcoded in the navigation template (or provide a fallback), so an exception is not thrown if the `index` route doesn't exist (or at least, a 404 page is thrown instead)

**Comment by lcharette** [comment]
Done for part one :)
