### ISSUE TITLE
How to make a good app unusable for 90% of developers

### ISSUE THREAD

**Issue by vordan** [alexweissman/UserFrosting#1248]
Your decision to require PHP 8.x is **practically denying the usage** of this good app (at least, looks good, haven't tried it, can't try it).
I'm sure it is provable that 90% of today's web server installations do not use PHP 8.
Updating PHP on servers is very serious and can't be done lightly - it can break some applications already on it.
I understand that there are developers like youselves which always like the latest and the best, but, this is counter-productive.
Frankly, this kind of app can be safely coded in any version of PHP from 5 and up, but, unfortunately, that's not the case.
At least, you should allow some kind of "compatibility mode", which at least accepts PHP 7.

So, there is my request - make the app compatible with PHP 7.x. It can't be that hard

**Comment by lcharette** [comment]
PHP 8.0 is End of life : https://www.php.net/supported-versions.php. Using PHP 5.0 today is a VERY bad idea.
Our dependencies don't support it, so we can support it. That's it.
