### ISSUE TITLE
Missing file in UF-PM System

### ISSUE THREAD

**Issue by nastrange** [alexweissman/UserFrosting#126]
For some reason the Private message system I downloaded is missing a file: 'account/includes.php' without which the whole messaging thing is failing to work.

**Comment by wacokid** [comment]
Do you have a date on when the new Private Messaging System will be available?

**Comment by alexweissman** [comment]
Probably not for a while - my priority right now is in finishing the new UF core, which itself will probably take another 2-3 months.

**Comment by wacokid** [comment]
Thanks.  Any suggestions on what else would be easy to integrate as a user messaging system prior to that?

**Comment by alexweissman** [comment]
Hmm.  The easiest thing to do for now might just be to try and update the existing plugin.  I haven't really used it, but you might be able to get it working in a few hours.  If you succeed, please fork and submit a pull request!
