### ISSUE TITLE
Navigation menu for new user groups

### ISSUE THREAD

**Issue by drewmo** [alexweissman/UserFrosting#127]
It seems to me that if you create a new user group there is no function to add the group's navigation menu settings to the <code>nav_group_matches</code> table.

 I noticed this from my fresh install today after adding a new default user group, searching online I couldn't find anyone else with this issue so maybe it is just me?

 As far as I can tell the <code>updatePageGroupLink</code> function only checks permission for the page, checks if the page exists, gets the page's details, and updates it's status to private / public. 

The only reference I can find to <code>nav_group_matches</code> is the function <code>fetchMenu</code> in db_functions, and it is only used to get the allowed menu not update it.

I will be trying to add this functionality to the <code>addPage</code> function unless someone else informs me of something I have done wrong.

**Comment by alexweissman** [comment]
Menus can now be configured to automatically show/hide nav items based on user permissions.  This can be done using the `checkAccess` function.  Example: https://github.com/alexweissman/UserFrosting/blob/dev-0.3.0/userfrosting/templates/themes/default/menus/sidebar.html#L23
