### ISSUE TITLE
ufTable `addParams` field Does Nothing

### ISSUE THREAD

**Issue by StrykeSlammerII** [alexweissman/UserFrosting#1275]
### Affected sprinkle or package

userfrosting/sprinkle-admin

### UserFrosting or package Version

5.1.3

### Debug Data

```bash
UserFrosting Environnement Information
======================================

 -------------------- ------------------------------------------ 
  Framework version    5.1.3                                     
  OS Name              Linux                                     
  Main Sprinkle        My Application                            
  Main Sprinkle Path   /home/strike/Frosting/UF5-addParams/app/  
  Environment mode     default                                   
  PHP Version          8.3.12                                    
  Node Version         v22.10.0                                  
  NPM Version          10.9.0                                    
 -------------------- ------------------------------------------ 


Loaded Sprinkles
================

 ------------------ --------------------------------------- -------------------------------------------------------------------------------------- 
  Sprinkle           Namespace                               Path                                                                                  
 ------------------ --------------------------------------- -------------------------------------------------------------------------------------- 
  Core Sprinkle      UserFrosting\Sprinkle\Core\Core         /home/strike/Frosting/UF5-addParams/vendor/userfrosting/sprinkle-core/app/src/../     
  Account Sprinkle   UserFrosting\Sprinkle\Account\Account   /home/strike/Frosting/UF5-addParams/vendor/userfrosting/sprinkle-account/app/src/../  
  AdminLTE Theme     UserFrosting\Theme\AdminLTE\AdminLTE    /home/strike/Frosting/UF5-addParams/vendor/userfrosting/theme-adminlte/app/src/../    
  Admin Sprinkle     UserFrosting\Sprinkle\Admin\Admin       /home/strike/Frosting/UF5-addParams/vendor/userfrosting/sprinkle-admin/app/src/../    
  My Application     UserFrosting\App\MyApp                  /home/strike/Frosting/UF5-addParams/app/src/../                                       
 ------------------ --------------------------------------- -------------------------------------------------------------------------------------- 


Database config
===============

 ------------ ------------------------------------------------------------------ 
  CONNECTION   sqlite                                                            
 ------------ ------------------------------------------------------------------ 
  DRIVER       sqlite                                                            
  HOST                                                                           
  PORT                                                                           
  DATABASE     /home/strike/Frosting/UF5-addParams/app/database/userfrosting.db  
  USERNAME                                                                       
  PASSWORD                                                                       
 ------------ ------------------------------------------------------------------ 


Testing database connection...
==============================

                                                                                                                        
 [OK] Database connection successful
```

### Chat Discussion (optional)

https://chat.userfrosting.com/channel/support?msg=63XZe8SjCrpdkmocw

### Description

Technically, [addParams](https://learn.userfrosting.com/client-side-code/components/tables#addparams) doesn't Do Nothing--it gets parsed correctly in the `s` object inside the jQuery `ajax` call--but it doesn't seem to last beyond that.

By the time the code gets to the end of [UF's widget-sort2Hash.js](https://github.com/userfrosting/theme-adminlte/blob/698994b8af7c301fc57bf4c4b579f4956eb2bf94/app/assets/userfrosting/js/tablesorter/widget-sort2Hash.js#L242) to update the address bar, anything in `addParams` is either lost or ignored.

A quick fix would be to just remove this option (it doesn't seem to be used in the base UF app), but then I'd have to find another way to pass parameters to my Sprunjes :stuck_out_tongue: 

I haven't yet tracked down where the correct URL from `s` goes after the `ajax` call, so the problem may be upstream rather than in `widget-sort2Hash.js`. I'll comment here if I can narrow it down any further.

Disclaimers:
There's also the possibility of interference from my adblocker, since I see JS code from that triggering between the pieces of code that I could read.
I'm also a JS n00b and have never touched AJAX before, so possibly I'm still breaking things unintentionally. If anyone CAN or CANNOT reproduce, I'd appreciate confirmation.

### Steps To Reproduce

1. Fresh UF install via composer
1b. if needed, manually run `php bakery build:assets`--it's faster to edit the built JS assets directly rather than overwriting things with a new sprinkle
2. Login as root
3. Verify that `http://localhost:8080/groups` shows a table of the 3 Starcraft races and changes the address bar to `http://localhost:8080/groups#&sort[table-groups][name]=asc&page[table-groups]=1&size[table-groups]=10`
4. Edit `public/assets/page.groups.js`, line 40, to add `addParams: {name: "Terran"}` to the `.ufTable(` call
5. Reload `http://localhost:8080/groups`, and note that both the table and address bar have not changed. Instead, `&name="Terran"` should be added at the end of the URL and the table should only have a single "Terrans" entry.
(One could even add nonsense to addParams, and the resulting page would not change)
5b. Setting a breakpoint at `$("#widget-groups").ufTable`, line 38, should verify that the edited `addParams` is actually called in the browser.

**Comment by StrykeSlammerII** [comment]
There may also be something else going on that I didn't understand/expect.

After some additional testing with above API and Sprunje, `http://localhost:8080/api/groups?size=10&page=0&sorts[name]=asc&filters[name]=T` works as expected, and only returns rows for "Protoss" and "Terran".

However, removing "filters" and the square brackets, so that `&name=T` is passed to the Sprunje, returns all three rows instead. :thinking: 
Since the Sprunje isn't accepting the parameters I expected, it doesn't matter whether they're passed via addParams or not.

I'll keep experimenting and report back if I can find a better syntax to use in addParams. If that's the only issue, I'll also submit a PR to `/learn`.

**Comment by StrykeSlammerII** [comment]
Also: I was able to find where the unused `name=T` parameter is passed to `widget-sort2Hash.js`, so I doubt there's any upstream issue.
Fortunately(?), the address that function returns has nothing to do with the AHR/AJAX request: it's just a UI "feature" so it's out-of-scope of this issue.

**Comment by StrykeSlammerII** [comment]
Figured it out--yes, it was a usage error on my end.
I've submitted [usage notes for `addParams`](https://github.com/userfrosting/learn/pull/149) to `/learn` and will close this issue once that is updated.

**Comment by lcharette** [comment]
Glad you found it. I merged the PR.
