### ISSUE TITLE
Redundant user errors after enable/disable the user's group property

### ISSUE THREAD

**Issue by assafv** [alexweissman/UserFrosting#129]
1. On admin, create a new user.
2. On a different browser, login with that user ( logged successfully ).
3. On admin, disable the user's only "User" group.
4. Refresh user's browser -> error 404
5. On Admin, enable the user's only "User" group.
6. Refresh user's browser on homepage

You will see the errors that the user was suppose to see when he got redirected to the error page instead.

snapshot attached
![uf_defect_redundant_errors](https://cloud.githubusercontent.com/assets/1512224/4604742/fabe053c-51b4-11e4-9437-f5e8f672eaaf.png)

**Comment by alexweissman** [comment]
Error messages are now handled by Fortress's `MessageStream` class: https://github.com/alexweissman/fortress/blob/master/fortress/MessageStream.php
