### ISSUE TITLE
SB Admin 2

### ISSUE THREAD

**Issue by alexcroox** [alexweissman/UserFrosting#132]
Noticed this is built off SB Admin, there is SB Admin 2 which looks pretty nice.

http://startbootstrap.com/template-overviews/sb-admin-2/

Is it a case of straight replacement or is there a lot of heavy customisation on the theme?

**Comment by anthonybartoli** [comment]
> At this point we really need a full-fledged forum (possibly built on UF ) to carry on and encourage conversations like these :-D

If @alexweissman is still considering a forum, I highly recommend [phpBB](http://www.phpbb.com). It won't be built on UF but it's ready to go out of the box. I am looking to contribute to this project so i'd be happy to run the forum if @alexweissman is too busy to manage it. I manage one already and am familiar with how it works.

**Comment by alexweissman** [comment]
Thanks, yeah I know phpBB is pretty popular.  Send me an email at <shortened version of my first name> at alexanderweissman.com, we can talk about it.

**Comment by anthonybartoli** [comment]
How about Google Groups? We'd get pretty much the same functionality without the cost or hassle of hosting a forum.

**Comment by alexweissman** [comment]
I'm starting to work on the implementation of groups for the new version of UF, and I need to sort out how we're going to do theming.  I've already implemented the structure for adding themes (it is similar to Wordpress' themes, but more elegant and using Twig ;-) )

The question is, how should themes be assigned?  To individual users?  Or to groups, and then users will get the theme associated with their primary group?

**Comment by alexweissman** [comment]
Alright, theming has been implemented: https://github.com/alexweissman/UserFrosting/tree/dev-0.3.0/userfrosting/templates/themes.  Basically, it consists of **theme directory** containing a collection of HTML templates and a theme stylesheet (`theme.css`).  

There is a base collection of HTML files in the `default` theme, which represent the core renderable content of the UF system.  Other themes can override these files simply by creating new versions of the files in their own folders.  Twig (templating engine) will try to load the theme's files first, falling back on the default theme files.  Then, the theme stylesheet will be loaded (or the default stylesheet, if the theme stylesheet is not present).
