### ISSUE TITLE
Translating UF interface 

### ISSUE THREAD

**Issue by Ctbmaz** [alexweissman/UserFrosting#145]
I'm testing Userfrosting right now and I noticed there is an option to select language. But it looks like it don't work. I tried to switch to es file included in translation directory but nothing changed. There was some Spanish mesage sometimes but overall the UF pages remained in english.
Is there a way to translate UF to other language? I would like to translate it to Polish.( I tried to create new file called pl based on English file and translated all message strings in it to polish but as I said it did nothing. Do I have to translate something else too? I'm interested into translating all aspects of interface not just messages. Is there a way to do that ?

**Comment by arochwer** [comment]
@lilfade hey! sorry i just got around this... what you need my help with?

**Comment by alexweissman** [comment]
I have implemented a custom function in Twig, `translate`, which looks up a message token and translates into the user's currently selected language.  For example, https://github.com/alexweissman/UserFrosting/blob/dev-0.3.0/userfrosting/templates/themes/default/menus/sidebar.html#L25:

```
<a href="{{site.uri.public}}/users"><i class="fa fa-users fa-fw"></i> {{ translate("MENU_USERS") }}</a>
```

This looks for the `MENU_USERS` token in the corresponding [language file](https://github.com/alexweissman/UserFrosting/tree/dev-0.3.0/userfrosting/locale).  Many of the language files are out-of-date (with `en_US` being the canonical up-to-date file).  Some help updating these translations, and providing new languages, would be great.

**Comment by alexweissman** [comment]
See #360.
