### ISSUE TITLE
captcha

### ISSUE THREAD

**Issue by tayzee** [alexweissman/UserFrosting#149]
Hi again,

I am using the latest version of your app.

When trying to register a new user, I am running into the following problem on the registration page:
![screen shot 2014-11-06 at 12 51 08](https://cloud.githubusercontent.com/assets/6752666/4934572/dfd2dffc-65a2-11e4-87b0-3117fedfdcbf.png)

I also notice in the developer tools:
![screen shot 2014-11-06 at 12 52 19](https://cloud.githubusercontent.com/assets/6752666/4934601/0757431a-65a3-11e4-9374-727db3f76703.png)

I see you guys have been trying to sort the problem out, have you been able to do so, or is this just happening to me?

Secondly, is there a way for me to disable using captcha for now?

Thanks,
Tay

**Comment by alexweissman** [comment]
Alright, just reopen the issue if you still have trouble.
