### ISSUE TITLE
Side Navigation

### ISSUE THREAD

**Issue by tayzee** [alexweissman/UserFrosting#153]
2 issues I have found, both regarding the menus.

The first problem is that if you create sub menus (left-sub) regardless of whether you make one of those sub-items only viewable to admins, it is still viewable by all groups.

The second thing I am having problems with is when for instance you load one of the pages that is linked to a sub-menu, for instance Site Settings, when you click on one of the items under that sub-menu, it loads the page, but collapses the menu and doesnt show the active item. I cant figure out how to fix that.

**Comment by alexweissman** [comment]
This is fixed in the dev branch, with our upgrade to SB Admin 2.  Basically, we will have some JS code that automatically determines which page we're on, and highlights the corresponding menu item: https://github.com/alexweissman/UserFrosting/blob/dev-0.3.0/public/js/sb-admin-2.js#L29
