### ISSUE TITLE
How to make sure users remain connected a long while? 

### ISSUE THREAD

**Issue by KevinC0** [alexweissman/UserFrosting#181]
Hello, 

I really enjoy UserFrosting, congrats on the great work! One minor feedback, I experiment regular disconnection from UserFrosting (i.e after a long moment, when I close my web browser, ...). Would you have a lead on how to make sure user's doesn't have to login regularly? 

Best, 

Kevin

**Comment by alexweissman** [comment]
The issue with sessions is discussed in #228.
