### ISSUE TITLE
Secured file locations

### ISSUE THREAD

**Issue by mmickelson** [alexweissman/UserFrosting#183]
I'm putting together an admin site and want to have pages be www.example.com/admin/documents.php instead of www.example.com/admin/account/documents.php. It appears that the only tracked pages for page-level authorization are those in the account and forms directories. What is the best way to organize the admin pages in a way that I can put them wherever I want and still have them tracked in the User Frosting dashboard?

**Comment by alexweissman** [comment]
Please reopen the issue if you're still having trouble.

**Comment by mmickelson** [comment]
Will do. Sorry I got pulled onto something else for a while. I'll come back to this and give a report when I am able to work on it again.

**Comment by alexweissman** [comment]
No problem, I'm going to be shifting my attention to [Bootsole](https://github.com/alexweissman/bootsole/tree/htmlbuilder) for a few weeks, anyway!
