### ISSUE TITLE
The specified page details could not be found.

### ISSUE THREAD

**Issue by mmickelson** [alexweissman/UserFrosting#184]
I'm getting this error "The specified page details could not be found." that makes pages invisible no matter what settings I have in the dashboard. I've added the usual basic authentication code at the top of each page I want secured.
I added "" to the page_include_paths in the config.php so that the admin site root files are included in the options for page level authorization. See https://github.com/alexweissman/UserFrosting/issues/183 for the thread.
It seems that the root level files are the ones that are having this problem.

What does the error mean and what might be a way to fix it?

**Comment by alexweissman** [comment]
Alright, closing this issue - lemme know if you have the same problems with the `master` branch.
