### ISSUE TITLE
Want to add a new field in Registration form

### ISSUE THREAD

**Issue by efb2a** [alexweissman/UserFrosting#189]
I want to add a <select> ("List") element in my Registration form and want to store the selected item in "study_in" column in 'uf_users' table. When I tried to add, it gave me error and said define class. 
Please tell me that what modifications should I make to add new fields in Registration form. And What all files I need to modify in order to do that ? 

I want something like that! 
I want the 'I am in list working. Please Help me Alex. Thanks in advance! 

![1111](https://cloud.githubusercontent.com/assets/10271290/5530416/7db3b6da-8a45-11e4-9bbc-c5e0faea0a81.JPG)

**Comment by alexweissman** [comment]
Closing...please reopen if you are still having trouble.
