### ISSUE TITLE
Multiuser Support/Templating

### ISSUE THREAD

**Issue by oladapooni** [alexweissman/UserFrosting#195]
I'm trying to learn a little bit more here because I'm more used to creating templates for Wordpress. I know it was mentioned something about templating on the Main Features page, and I was wondering if I can still create an experience for each user without the tempting upgrade. Essentially what I'm doing is creating an incentive system to display the number of points that a user has been awarded and more in the dashboard.

**Comment by alexweissman** [comment]
Which version of UF are you using?  The templating system is still kind of scattered at the moment, we're working on a better, unified templating system for the next big version of UF.  

In the meantime, your best bet is to assign different users to different groups, and then have different versions of each page for each group.  What aspect do you want to customize for each user?  Navbars?  CSS?  Permissions?

For simply fetching and displaying points, you shouldn't need any special templating features.  If you want special CSS for each user, you could add a table that maps `user_id` or `group_id` to a specific CSS file, and then add code to your header script that loads the appropriate CSS file based on the currently logged in user.

**Comment by oladapooni** [comment]
I’m using UF 0.2.2, and the goal is to have different point values displayed for each user. I don’t have the wireframe ready at the moment for a clearer picture, but besides the pictures for each user, the point values that I’ll be awarding is paramount. 

Cheers,

Oladapo Onikuyide

Innovation distinguishes between a leader and a follower.
-Steve Jobs

**Comment by alexweissman** [comment]
Cool, yeah you shouldn't need any special templating system.  I would just write another db/secure function, for example `loadUserPoints(user_id)`, and then call that in `dashboard.php`.  Then you can pass in `$loggedInUser->user_id` to that function, and it will load the points for the given user.  Or, you can have the points be loaded as part of the `loadUser` function.

**Comment by oladapooni** [comment]
Thank you sir.

Oladapo

**Comment by alexweissman** [comment]
No problem, just reopen this issue if you have any trouble getting it to work!
