### ISSUE TITLE
"Logging in" as specific user

### ISSUE THREAD

**Issue by ebrightTP** [alexweissman/UserFrosting#197]
Is there a way to "Spoof" that you are a specific user from an Admin environment (blocking specific functionality for privacy's sake), and subsequently return to the Admin environment?  

Failing that, is there a way to log in as a specific user from an Admin environment in UserFrosting?

**Comment by r3wt** [comment]
The method isn't built in, but its possible if you code it up. What you'd want to do is use `fetchuserdetails()` to construct a loggedInUser object. your admin session would still exist, but alongside it could be whatever loggedInUser session you like.

**Comment by alexweissman** [comment]
It's an interesting idea, and I seem to recall someone asking about this as well.  What are you trying to accomplish by logging in as another user?  Debugging?  Performing actions on their behalf?

**Comment by ebrightTP** [comment]
The original idea was to perform actions on their behalf; I'm uncertain as to whether or not this will be needed, however, since I have informed the person who wishes to have this functionality that I will make it so that Admins/Salespeople (UF user groups) will be able to "give" items/files generated to specific users.

**Comment by alexweissman** [comment]
Ok, added this to the feature request list: https://github.com/alexweissman/UserFrosting/wiki/Feature-request-list
