### ISSUE TITLE
Error ! Anyhelp ?

### ISSUE THREAD

**Issue by Mullerr** [alexweissman/UserFrosting#198]
i didn't change anything in this line 
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/a8884635/public_html/models/config.php on line 57

Parse error: syntax error, unexpected T_STRING in /home/a8884635/public_html/models/config.php on line 57

**Comment by alexweissman** [comment]
The `\` on that line is the namespace operator.  What version of PHP are you using?  Namespaces weren't introduced until PHP 5.3.

**Comment by alexweissman** [comment]
Please re-open this issue if you're still having trouble.  Thanks!
