### ISSUE TITLE
Next version/incarnation of UF

### ISSUE THREAD

**Issue by alexweissman** [alexweissman/UserFrosting#199]
For the next big version of UserFrosting, we have proposed the following components:

- **Templating:** ~~[Bootsole 0.2.0 (currently under development)](https://github.com/alexweissman/bootsole/)~~ **[Twig](http://twig.sensiolabs.org/) might be the best choice after all** - it won't build your tables and forms for you, but it is a good deal less complex and should be easier to work with.  Oh well, it was worth a try...
- **URL Routing:** ~~[Klein](https://chriso.github.io/klein.php/)~~  [Slim](www.slimframework.com)
- **Database ORM**: ~~[Redbean 4](http://redbeanphp.com/)~~ Custom-built model especially for UF ;-)
- **Server-side validation**: [Valitron] (https://github.com/vlucas/valitron)
- **Client-side validation**: [FormValidation (formerly known as BootstrapValidator)](https://github.com/formvalidation/formvalidation)
- **Dependency management:** [Composer](https://getcomposer.org/)
- **Mail:** [PHPMailer](https://github.com/Synchro/PHPMailer)?

Thoughts?  Anything we're missing?

**Comment by andig** [comment]
+1 for composer

Would appreciate Doctrine/ORM too.

**Comment by alexweissman** [comment]
Yup, I'm starting to realize that *everyone* uses Composer.  As for the ORM, I picked Redbean over Doctrine because it's more lightweight.  Then again, it depends on the target audience of UF.  Either way, we'll definitely be using an ORM in the next version ;-)

Send me a message through my website if you want to chat more ;-)

**Comment by rdmiller** [comment]
I'm just starting to work with UF to manage users for some Angular SPAs.  I would put admin control over login durations to be high on my list.  Thanks for the great work, Alex and all.

Rob
IUB '03

**Comment by alexweissman** [comment]
Cool, will do!  Also, [Bootsole](https://alexweissman.github.io/bootsole/) is almost ready!  This is an important step in bringing UF into the world of modern web development, and will make it tremendously easier for developers to adapt and extend UF for their needs.

**Comment by rdmiller** [comment]
Do you have an ETA on when 0.3.0 will be ready?

**Comment by r3wt** [comment]
@rdmiller Alex has begun work on 0.3.0

Its still very much in the stages of R & D, but you can see the progress Alex has made so far:

https://github.com/alexweissman/UserFrosting/tree/slim

**Comment by alexweissman** [comment]
Yup, it'll be another month or two at least.  But, if you have some expertise on Slim, Twig, or RedBean and want to contribute, let me know!

**Comment by andig** [comment]
I can only add that Doctrine ORM is an excellent product and imho the de-facto standard, I believe more so and with broader support than redbean (my personal experience from looking a both and extensively using Doctrine).

**Comment by alexweissman** [comment]
Thanks.  Yes it is true that Doctrine is a more widely used ORM.  However, I chose RedBean because it is "no config" (see http://redbeanphp.com/about).  And, not sure if Doctrine does this as well, but it exposes direct SQL querying as well.  

One of the goals of UF is to help novice programmers get started, so I am trying to strike a delicate balance between an easy learning curve and best practices of modern web design.

**Comment by andig** [comment]
Don't want to debate your choice, just for sake of completeness. 

> However, I chose RedBean because it is "no config" (see http://redbeanphp.com/about). And, not sure if Doctrine does this as well, but it exposes direct SQL querying as well.

Doctrine does both afaik. For a "no config" example see https://github.com/volkszaehler/volkszaehler.org/blob/master/lib/Volkszaehler/Router.php. 

Direct SQL is possible as well via the underlying DBAL abstraction (`$this->em->getConnection()->executeQuery()`).

> One of the goals of UF is to help novice programmers get started, so I am trying to strike a delicate balance between an easy learning curve and best practices of modern web design.

Doctrine is definitely more verbose. Maybe it would be possible to encapsulate the ORM-using stuff to make if possible to include UF in Doctrine applications? As doctrine requires annotations, would it potentially be possible to annotate the RB model to work with Doctrine, too?

**Comment by r3wt** [comment]
Doctrine is slower than Christmas

**Comment by alexweissman** [comment]
No worries, I think it's good to keep an open mind and have an open discussion :-)

Didn't realize that Doctrine had direct SQL, that's actually good to know.  I'm not sure if I want to throw annotations into the mix, especially since I'll already be throwing request schema into the next version.

There will be a layer between RedBean and the UF controllers - if you take a look at the `models` folder of the `slim` branch, you'll see `DBObject`, `User`, etc.  So, something you could do is simply replace those classes with Doctrine-based model classes that implement the same functions.  Maybe I could even formally write the model as an `interface` to make it easier.

**Comment by r3wt** [comment]
I vote SwiftMailer instead of PHPMailer.

**Comment by alexweissman** [comment]
Ok, it's basically ready to go - just needs to be documented!  https://github.com/alexweissman/UserFrosting/tree/dev-0.3.0
