### ISSUE TITLE
Nav bar placement

### ISSUE THREAD

**Issue by swells808** [alexweissman/UserFrosting#200]
So really 2 questions here: Is it possible to just have the top nav bar and not the left side one displayed?

And when I am logged in as an admin I have the drop down nav from the top but, not as a standard user. Where is that option?

**Comment by alexweissman** [comment]
At the moment, the nav layouts are all controlled by `css/sb-admin.css` and `css/sb-admin-master.css`, as well as the `renderMenu` function in `models/template_functions.php`. You can get rid of the `<ul class="nav navbar-nav side-nav">` group in that function.

As for the dropdown in the top, did you create a new user group or something?  It should appear already for users in the standard `Users` group.

**Comment by swells808** [comment]
Yes this is for  new group. I want group 1 to see a nav bar with options that are just authorized for that group alone. Is there an easier way to go about this? Perhaps a direct bootstrap way?

**Comment by alexweissman** [comment]
[Is this what you're looking for](https://github.com/alexweissman/UserFrosting/wiki/Adding-a-navigation-menu-item)?

**Comment by swells808** [comment]
I saw that but let dig a little into this and get back to you. Thanks.

**Comment by alexweissman** [comment]
Alright, this will be easier to do in the upcoming version.  Let me know if you have any more problems!
