### ISSUE TITLE
CSV-User-Import (SQL-Database)

### ISSUE THREAD

**Issue by andreasf2012** [alexweissman/UserFrosting#201]
Hello, 

is it possible to create new users directly in the database by importing csv-files. Writing the php-script is not the problem, but is there something to consider?

Thanks in advance, 
Andreas

**Comment by alexweissman** [comment]
At the moment UF doesn't have this feature built-in, but if you're using phpMyAdmin there is functionality to do it there.

But yes I agree, CSV import/export would be a good and easy feature to implement directly in UF.

**Comment by andreasf2012** [comment]
Yeah, I would appreciate that! 

Can you explain me, how I can set a hashed password directly to the sql-database? Can I generate the hash, is there a function in UF? 

Thank you!

**Comment by alexweissman** [comment]
Sure, just use the `password_hash` and password_verify` functions that are built into PHP.  To set it to the DB, you can call the `updateUserPassword` function in `secure_functions.php`, or the `updateUserField` function in `db_functions.php`.  

The only difference is that  `updateUserPassword` is a secure function, so it will validate and check the user permissions before updating the password.

**Comment by andreasf2012** [comment]
Ok, thank you! 

Can you please tell me, which values I have to use for $algo and $options creating the hash (function password_hash). Can you help me?

**Comment by alexweissman** [comment]
You can use the `PASSWORD_BCRYPT` algorithm, without any options.  Actually, we already have a built-in wrapper function for this: `passwordHashUF`.

**Comment by andreasf2012** [comment]
It works, great! 

Thank you again!

**Comment by nuno-iglesias** [comment]
HI to everybody,

First of all, thanks to all the effort making all this.
I'm have finish adapting Userfrosting to our needs (a very simple app) and now I'm trying to import some users, with no luck.
Is there any script used for that?

**Comment by alexweissman** [comment]
@nuno-iglesias take a look at the tutorials: http://www.userfrosting.com/tutorials/
