### ISSUE TITLE
Hide add button if user does not have certain permission?

### ISSUE THREAD

**Issue by Forge-Media** [alexweissman/UserFrosting#209]
Hi, me again ;)

Before I push my app, ForgeCP first Beta I would like to try and hide a button.

* When a user (Client) logs in, the Dashboard page (Atoms) displays a table with **only** their Atoms (VPSs).
![ForgeCP Clients](http://i.imgur.com/SaT2t8u.png)

* When a root user  logs in, the Dashboard page (Atoms) displays a table with all Atoms. 
![ForgeCP Admin](http://i.imgur.com/Qck02b2.png)

The issue is that these tables are the same, and an if statement simply checks whether a user is an admin and if so calls a function to list AllAtoms else list UserAtoms.

However, the add Atom Button is visible to both admins and users. However, if a user clicks it a permissions error appears. **Is it possible to hide this button if a user is not an admin?**

**Comment by alexweissman** [comment]
Yup, try this in your `table_atoms.php` (or wherever you build the table):

```
if (checkActionPermission("createAtom", []){
    $buttons_render['add']['hidden'] = "";
} else {
    $buttons_render['add']['hidden'] = "hidden";
}
```

I am assuming that `createAtom` is the name of your secure action for creating an Atom.

**Comment by Forge-Media** [comment]
One bracket was missing: 
```
if (checkActionPermission("createAtom", [])) {
```
But otherwise that worked thanks :+1:

**Comment by Forge-Media** [comment]
One last thing this is the IF statement to display the correct Atoms to the correct users:
```
// Load users
if ($loggedInUser->user_id == $master_account) {
    if (($atoms = loadAllAtoms($get['limit'])) === false) {
        apiReturnError($ajax, ACCOUNT_ROOT);  
    }
} else if (($atoms = loadUserAtoms($user_id)) === false) {
        apiReturnError($ajax, ACCOUNT_ROOT);  
}
```
Is there a way to instead of checking if user is = master_account but rather just in the admin group?

**Comment by Forge-Media** [comment]
This seems to a be a valid solution:
```
// Load users
if ($loggedInUser->user_id == $master_account) {
    if (($atoms = loadAllAtoms($get['limit'])) === false) {
        apiReturnError($ajax, ACCOUNT_ROOT);  
    }
} else if (checkActionPermission("loadAllAtoms", [])) {
     $atoms = loadAllAtoms($get['limit']);
} else if (($atoms = loadUserAtoms($user_id)) === false) {
        apiReturnError($ajax, ACCOUNT_ROOT); 
}
```

**Comment by alexweissman** [comment]
Yup, actually you don't even need the `if ($loggedInUser->user_id == $master_account)` part.  The master account automatically has permission to do everything.  So when you do `checkActionPermission("loadAllAtoms", [])`, the master account will automatically be approved ;-)

**Comment by Forge-Media** [comment]
oh ok yeah, makes sense thanks :D

**Comment by alexweissman** [comment]
Let me know if you have any more problems!
