### ISSUE TITLE
Mail Service Provider for 0.3.0

### ISSUE THREAD

**Issue by Soupala** [alexweissman/UserFrosting#21]
I'm trying to figure out how the email side of this project, and I imagine others will also be interested as well.  I currently don't have any SMTP stuff installed my LAMP stack. I want to send the mail securely, and preferably piping through a 3rd party service like Mailgun or SendGrid. Mailgun provides 10,000 free emails/month, so I'm thinking of focusing on figuring out how to do that.  

Any thoughts or tips.   Is this a priority for anyone else?  What are folks currently doing to get sendMail to work?

**Comment by alexweissman** [comment]
We will be using [PHPMailer](https://github.com/PHPMailer/PHPMailer) in 0.3.0.  However this still doesn't address the need for a third-party mailing service, maybe someone can write a plugin for this?

**Comment by alexweissman** [comment]
Ok, I've made SMTP a configuration option in v0.3.1.  So, you should now be able to configure UF to send emails through any SMTP server you have access to.
