### ISSUE TITLE
Is it possible to hide the .php extension

### ISSUE THREAD

**Issue by Forge-Media** [alexweissman/UserFrosting#210]
Not anything major, just would like to hide the .php extension if possible

I've tried a few .htaccess suggestions such as:

```
RewriteEngine On

# Unless directory, remove trailing slash
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^([^/]+)/$ http://example.com/folder/$1 [R=301,L]

# Redirect external .php requests to extensionless url
RewriteCond %{THE_REQUEST} ^(.+)\.php([#?][^\ ]*)?\ HTTP/
RewriteRule ^(.+)\.php$ http://example.com/folder/$1 [R=301,L]

# Resolve .php file for extensionless php urls
RewriteRule ^([^/.]+)$ $1.php [L] 
```
&
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([^\.]+)$ $1.php [NC,L]
```
Neither seem to work.
The second code simply results in a page not found on server error.

Is UserFrosting compatible with hiding the extension.

**Comment by alexweissman** [comment]
It should work - what about

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME}\.php -f
RewriteRule .* $0.php
```

Mind you, you'll have to update all of the links in the database.  Or, you can try playing around with that routing library I mentioned in the other issue ;-)

**Comment by Forge-Media** [comment]
Just read the same about having to update existing links, thanks for the help anyway.
