### ISSUE TITLE
error after adding new user field

### ISSUE THREAD

**Issue by webaaa1** [alexweissman/UserFrosting#211]
Hi,

I tried add a new field on the user registration form and followed all steps described in the wiki's article about this topic.

All forms shows correctly the new field.
I can edit or update the field on an existing user.
But I get an error when I want register or create a new user.

The php error log says: 
"Error (8): Undefined variable: city in C:\xampp\htdocs\web_uf\models\db_functions.php on line 956"

I am using the new version 0.2.2

Is there any solution for this?

Thanks for your help!

**Comment by alexweissman** [comment]
Did you add `$city` as a parameter to the `addUser` function?

**Comment by webaaa1** [comment]
You're right! I missed add it in that first line of the addUser function. Now it works!

Thanks for your support!
