### ISSUE TITLE
Nothing happens on 'Continue Install...' button

### ISSUE THREAD

**Issue by nmgtn** [alexweissman/UserFrosting#213]
I downloaded UserFrosting yesterday. The features look really promising and exactly what I'm looking for, so thanks for that! My download is d9b8523.

I'm running it in xampp, using PHP 5.6.3, and trying to run the installer in Chrome 39.

### My problem
I've put the database config in, and when I start the installer and get to wizard_site_config.php, it says "Great news, we're able to connect to your database!" at the top. However, I fill in the Site Settings form and click 'Continue Install...', and nothing happens (except that the icons on each text box go green to show validation).

### Logs
The console isn't super-helpful, but it says:

```
base site path is: ../
userfrosting.js:46 base site path is: ../
userfrosting.js:249 validating field: site_url='localhost/userfrosting/'
userfrosting.js:249 validating field: site_name='UserFrosting'
userfrosting.js:249 validating field: user_title='New Member'
userfrosting.js:249 validating field: site_email='normington@gmail.com'
wizard_site_config.php:198 error
```

In php_error_log I've got more errors, but nothing that makes it obvious to *me*:

```
[26-Jan-2015 16:34:13 Europe/Berlin] Error in C:\xampp\htdocs\userfrosting\models\db_functions.php on line 1752: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'userfrostingtest.uf_plugin_configuration' doesn't exist

[26-Jan-2015 16:34:13 Europe/Berlin] PHP Notice:  Undefined index: activation in C:\xampp\htdocs\userfrosting\models\config.php on line 79

[26-Jan-2015 16:34:13 Europe/Berlin] PHP Notice:  Undefined index: can_register in C:\xampp\htdocs\userfrosting\models\config.php on line 80

[26-Jan-2015 16:34:13 Europe/Berlin] PHP Notice:  Undefined index: website_name in C:\xampp\htdocs\userfrosting\models\config.php on line 81

[26-Jan-2015 16:34:13 Europe/Berlin] PHP Notice:  Undefined index: website_url in C:\xampp\htdocs\userfrosting\models\config.php on line 82

[26-Jan-2015 16:34:13 Europe/Berlin] PHP Notice:  Undefined index: email in C:\xampp\htdocs\userfrosting\models\config.php on line 83

[26-Jan-2015 16:34:13 Europe/Berlin] PHP Notice:  Undefined index: resend_activation_threshold in C:\xampp\htdocs\userfrosting\models\config.php on line 84

[26-Jan-2015 16:34:13 Europe/Berlin] PHP Notice:  Undefined index: language in C:\xampp\htdocs\userfrosting\models\config.php on line 85

[26-Jan-2015 16:34:13 Europe/Berlin] PHP Notice:  Undefined index: new_user_title in C:\xampp\htdocs\userfrosting\models\config.php on line 86

[26-Jan-2015 16:34:13 Europe/Berlin] PHP Notice:  Undefined index: email_login in C:\xampp\htdocs\userfrosting\models\config.php on line 87

[26-Jan-2015 16:34:13 Europe/Berlin] PHP Notice:  Undefined index: token_timeout in C:\xampp\htdocs\userfrosting\models\config.php on line 88

[26-Jan-2015 16:34:13 Europe/Berlin] PHP Notice:  Undefined index: version in C:\xampp\htdocs\userfrosting\models\config.php on line 89

[26-Jan-2015 16:34:13 Europe/Berlin] Error in C:\xampp\htdocs\userfrosting\models\db_functions.php on line 1943: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'userfrostingtest.uf_filelist' doesn't exist

```

Sorry if this is dumping too much information! I'm not sure what is behind this and didn't want to be too vague. Let me know if there's anything else I can provide to help fix the problem! This feels like it should be a simple thing to solve but I can't find anything on it looking through past issues, only #139 and #174 seem a little similar.

Thanks for your help!

**Comment by alexweissman** [comment]
> Sorry if this is dumping too much information!

Not at all!  This is exactly what I'm looking for when someone submits a troubleshooting issue.  

It looks like there are (at least) two tables that didn't get created when `wizard_site_config.php` POSTed to `install_db.php`: `uf_plugin_configuration` and `uf_filelist`.  Can you check in `phpmyadmin` (or whatever you use to manage your DB) and tell me which tables *did* get created, if any?

These two tables also happen to be the tables associated with the latest changes to the installer.  @lilfade, can you take a look at this too?

**Comment by normington** [comment]
Thanks for your quick reply.

I created a new database for UserFrosting before the install, and the only table that has been added is `uf_configuration`, which is empty (zero rows).

**Comment by alexweissman** [comment]
Interesting.  `uf_configuration` is actually the first table that should be created, so I guess the problem lies there.  It's creating the table, but not adding the rows, so there must be something going on with lines 200-214 in `install_db.php`:

```
$configuration_entry = "
INSERT INTO `".$db_table_prefix."configuration` (`id`, `name`, `value`) VALUES
(1, 'website_name', '".$site_name."'),
(2, 'website_url', '".$site_url_root."'),
(3, 'email', '".$site_email."'),
(4, 'activation', ".$selected_activation."),
(5, 'resend_activation_threshold', '0'),
(6, 'language', 'models/languages/en.php'),
(8, 'can_register', ".$selected_register."),
(9, 'new_user_title', '".$user_title."'),
(10, 'root_account_config_token', '" . md5(uniqid(mt_rand(), false)) . "'),
(11, 'email_login', '".$selected_email."'),
(12, 'token_timeout', '10800'),
(13, 'version', '0.2.2');
";
```
Can you try printing out this query immediately after these lines?  I'd like to see what is actually getting called.

Also, you mentioned that you're using PHP 5.6, which I actually haven't tested with yet.  Could there be a compatibility issue?

**Comment by normington** [comment]
Okay - I did a bit of fiddling.

### XAMPP w/ PHP 5.6.3 - still failing
Added the line `echo "configuration_entry is $configuration_entry";` to `install_db.php` immediately after lines 200-214, as above.

Didn't see anything different in the console or php_error_log - nothing extra being printed at all, compared to my first go.

### WAMPServer w/ PHP 5.5.12 - better...
I thought I'd pursue the PHP version avenue, so I installed WAMPServer to avoid having to mess around with XAMPP to change the PHP version.

Added the line `echo "configuration_entry is $configuration_entry";` to `install_db.php` immediately after lines 200-214, as above.

When I hit 'Continue Install...' in `wizard_site_config.php`, things actually happened this time! I got lots of green messages showing tables being created, and a final one saying:
> Database setup complete, please create the master (root) account.(etc)

However, the final message was red, and said 
> Oops, looks like our server might have goofed. If you're an admin, please check the PHP error logs.

The console showed:
```
userfrosting.js:46 base site path is: ../
userfrosting.js:249 validating field: site_url='localhost/userfrosting2/'
userfrosting.js:249 validating field: site_name='UserFrosting'
userfrosting.js:249 validating field: user_title='New Member'
userfrosting.js:249 validating field: site_email='normington@gmail.com'
userfrosting.js:457 Backend error: configuration_entry is 
INSERT INTO `uf_configuration` (`id`, `name`, `value`) VALUES
(1, 'website_name', 'UserFrosting'),
(2, 'website_url', 'localhost/userfrosting/'),
(3, 'email', 'normington@gmail.com'),
(4, 'activation', 1),
(5, 'resend_activation_threshold', '0'),
(6, 'language', 'models/languages/en.php'),
(8, 'can_register', 1),
(9, 'new_user_title', 'New Member'),
(10, 'root_account_config_token', 'f2c1b3d58d990854cc7e8cecce9cb0f5'),
(11, 'email_login', '0'),
(12, 'token_timeout', '10800'),
(13, 'version', '0.2.2');
{"errors":0,"successes":22}
wizard_site_config.php:198 error
```
So, the `echo` line I added seems to have worked this time, at least, but some error was reported...

Nothing was added to the php_error_log.

However, the installation did work. Not sure if I was supposed to be automatically forwarded to `wizard_root_user` after this, but I navigated there manually and set up the master user, and things seem to work.

### Remaining issue
I'm assuming the reason for this improvement is the switch from PHP 5.6 to 5.5.
The result of the installation is that the site works okay, so it's done it's job in that way.
However, it did throw an error on the page (red message mentioned above), and said `Backend error` in the console.

I appreciate that the remaining errors aren't very descriptive! Please let me know if there's something else I can do to see where the new errors are coming from.

**Comment by alexweissman** [comment]
Thanks for the detailed explanation and error logs.  The "Oops, looks like our server might have goofed" message might have just been left over in the message queue, and didn't get reported until after the successful installation. 

Let me try running the installer myself as PHP 5.5 and 5.6 (I'm actually using 5.4 for local development) and see if I can get at the heart of this issue.  If it's a problem with the DB commands, I might just wait to fix it until the next version when we will be using an ORM.  But, I'm glad it worked in the end and let me know if you run into any more problems.

**Comment by normington** [comment]
Great. I'll leave it up to you whether you leave this open or close it, but I'm sorted now, so thanks for your help!
