### ISSUE TITLE
Parse error: syntax error, unexpected '{' in C:\web-aqua\root\models\password.php on line 10

### ISSUE THREAD

**Issue by xnshady** [alexweissman/UserFrosting#215]
I have now installed UserFrosting on my root of my apache test web server.
I have have a mysql running on localhost, and i have a db user account setup.

When i click Start Installation i get this error:

Parse error: syntax error, unexpected '{' in C:\web-aqua\root\models\password.php on line 10

**Comment by alexweissman** [comment]
Looks like your error is on this line: 
`namespace {`

What version of PHP are you using?  Namespaces weren't introduced until PHP 5.3.

**Comment by xnshady** [comment]
Yes updating php fixed the problem :+1:
