### ISSUE TITLE
Use any kind of character for "display name"?

### ISSUE THREAD

**Issue by TrivialRoo** [alexweissman/UserFrosting#216]
Is there a way I can edit the API so I can allow my users to set their "Display Names" to be anything (even the same display names as other, e.g. Steam's user system), while keeping their "usernames" unique?

**Comment by alexweissman** [comment]
Sure, the check is done in line 157 of `models/secure_functions.php`.  So, just remove the code block:

```
    if(displayNameExists($display_name)) {
        addAlert("danger", lang("ACCOUNT_DISPLAYNAME_IN_USE",array($display_name)));
        $error_count++;
    }
```

**Comment by alexweissman** [comment]
Let me know if you need any more help!
