### ISSUE TITLE
Running an updateUser___ function does not update loggedInUser's value

### ISSUE THREAD

**Issue by ebrightTP** [alexweissman/UserFrosting#217]
When you run an updateUser____() function, such as updateUserTitle(), it changes the value in the database, but not in the $_SESSION's loggedInUser.  This is important when updating values such as "credits".

**Comment by alexweissman** [comment]
Thanks!  We should do a check when a user field is updated, to see if `$user_id == $loggedInUser->user_id`, and then update the `$loggedInUser` object if so.

**Comment by ebrightTP** [comment]
The only problem is that when you create the `$loggedInUser` object, the variable names may not necessarily match up to the backend.  For example: 

`$loggedInUser->displayname = $userdetails["display_name"];`
`$loggedInUser->username = $userdetails["user_name"];`

**Comment by alexweissman** [comment]
Unfortunately for now, yes.  When we switch over to [RedBean](http://redbeanphp.com/), this will be automatically handled.  Yet another reason for us to go with an ORM!

**Comment by jaggedarrow** [comment]
I have run into the same problem. Please list the code needed to fix this. Thanks!

**Comment by r3wt** [comment]
why not just modify the object with the new values? $loggedInUser is a reference to $_SESSION['user'], so it will automatically persist anytime you update it.

**Comment by jaggedarrow** [comment]
So I should be replacing "foo" with the field name such as "user" and putting this code into process_login.php where "loggedinuser" is being set, or in secure_functions.php as ebrightTP suggested above?

**Comment by ebrightTP** [comment]
process_login.php only runs once: When the user is logging in.  

You have to update the $loggedInUser or $_SESSION['userFrosting'] or $_SESSION['user'] values inside their respective secure_functions.php functions.

**Comment by r3wt** [comment]
@ebrightTP that's not really true. you can just edit $_SESSION['userFrosting'] directly, because its an instance of `loggedInUser`. i'm not really sure what the point of "secure functions" is. maybe its because they relate to things that should be secure?

**Comment by ebrightTP** [comment]
Editing the `$_SESSION['user']` will edit the built-in/custom values stored in the Session variable, but when the user logs out and logs back in, the values are pulled in to the `$_SESSION['user']` from the `uf_users` table.  

The secure_functions.php functions are what are run to edit the built-in/custom values in the `uf_users` table.  Only problem is that they currently only modify it in the table, not in the session.  

Here’s what I did in the updateUserEmail function in the secure_functions.php file:

```php
    if (updateUserField($user_id, 'email', $email)){
        addAlert("success", lang("ACCOUNT_EMAIL_UPDATED"));
        $_SESSION["userCakeUser"]->email = $email;
        return true;
    } else {
        return false;
    }
```

This is much easier than having to remember to modify the `$loggedInUser->email` value every time I call `updateUserEmail();`

**Comment by r3wt** [comment]
my whole point was that if these methods were self contained in the object its self instead of just random functions, there would be no need to update it. the class would take care of that.

**Comment by jaggedarrow** [comment]
Thanks, that worked.

**Comment by alexweissman** [comment]
Hey guys,

I've been trying to wrap my head around this issue for a while, and the bigger issue of managing the relationship between the database and in-memory objects.  I've been playing with ORMs, but they all seem to have some problem or another.  

Here is what I propose instead.

Every database "entity" (so, users, groups, etc) will have three classes associated with it.  The first will be the entity object itself.  So for example, we'd have a class `User`.  Objects of this class will internally maintain a list of the columns and values, and will have a `store` function that either creates the record in the DB (if it doesn't exist), or update the record (if it does exist).  `User` objects will also be able to delete themselves from the database, via a `delete` method (of course, the object itself won't be deleted until the program ends.

Then we'd have a static class, `UserLoader`, that can fetch either a single `User`, or a collection of users (as a `UserCollection` object), based on various rules/filters:

    $user = UserLoader::fetch(1);  // Fetch the user with id '1'
    $user = UserLoader::fetch('alex', 'user_name');   // Fetch the user by user_name

The major CRUD operations would operate directly on the `User` object:
**Create:**

    $user = new User($properties);
    $user->store();

**Update:**

    $user = new User($properties);
    $user->display_name = "Max Powers";
    $user->store();

**Delete:**

    $user = new User($properties);
    $user->delete();
    unset($user);    // To remove from memory, if desired

A `User` object can also have methods like `groups()` (to get the groups to which the user belongs), and even `login($password)` (to authenticate a `User` as the currently logged-in user). 

So updating the loggedInUser, or any other user for that matter, would involve changing the object property and then invoking `store()`.  The only difference would be whether you're getting the `User` object from the session (to change your own account properties) or from the database (to change another `User`'s properties).

What do you think?

**Comment by chrison999** [comment]
I think I need to learn more about PHP/Javascript so that, someday, I'll understand what you just said!

LOL!

Chris

P.S. You totally lost me, so whatever works for you and everyone else is fine by me.  ;)

**Comment by alexweissman** [comment]
Haha, I barely understand it myself!  It turns out that this is not such a trivial question after all, and the ORM debate is [very heated](http://blog.jooq.org/2013/07/07/high-complexity-and-low-throughput-reasons-for-using-an-orm/)!

**Comment by alexweissman** [comment]
Alright, I've implemented the `MySqlUser` class: https://github.com/alexweissman/UserFrosting/blob/dev-0.3.0/userfrosting/models/mysql/MySqlUser.php

It works as per @r3wt's suggestion: encapsulating User information, DB queries, etc.  The entire object can be assigned to the user's session, so changing the logged-in user's parameters is as easy as:
```
$_SESSION["userfrosting"]["user"]->display_name = "Herbert Hoover";
 $_SESSION["userfrosting"]["user"]->store();
```
