### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by mcwhorter72** [alexweissman/UserFrosting#218]
I'm doing a fresh install.
I updated the database settings in the db-settings.php file and clicked continue.
The next page (wizard_site_config.php) does nothing. It sits at a blank white screen in Chrome and returns "The website cannot display the page" in IE (HTTP500).

Any ideas?

**Comment by alexweissman** [comment]
Are you using PHP 5.6 by any chance?  See #213.

**Comment by mcwhorter72** [comment]
It appears I'm using php version 5.2.17  and mySQL version 5.0 hosted by Godaddy. 
Any ideas.

**Comment by alexweissman** [comment]
Yup, you need at least PHP 5.4 to run UF.  If you're on shared hosting, give them a call, they'll upgrade for you.

**Comment by mcwhorter72** [comment]
That worked. I'm all setup. Thanks.
