### ISSUE TITLE
Simultaneous Login

### ISSUE THREAD

**Issue by ebrightTP** [alexweissman/UserFrosting#219]
How would I go about making sure that if someone logs in on the same account on a different computer/browser/session, it kicks them out of any existing sessions? 

I'm trying to prevent multiple people sharing the same account.

**Comment by alexweissman** [comment]
You could store the session id in the database, and update it every time a login is processed.  Then, you could check (in `models/config.php`, for example) that the current session id matches the one in the database.  If not, then you destroy the session with `session_destroy()`.  

Of course a really savvy user would just find out their session id and copy it over to the other computer/browser.  But, most users probably won't be that clever.
