### ISSUE TITLE
Add new user field to account settings page

### ISSUE THREAD

**Issue by mcwhorter72** [alexweissman/UserFrosting#220]
Ok, I successfully followed the Wiki on how to add additional user fields. The wiki stops with allowing the Admin edit those fields. So, I'm trying to allow the logged in User to edit their new fields too. I modified the 'account/account settings.php' file to display the items. But I can't get the data to load into the input boxes. 

I tried pulling the data in using this:
echo $loggedInUser->newfieldname;

  

I'm sure I am missing something trivial.
Thanks.

**Comment by alexweissman** [comment]
If I'm not mistaken, that page still uses the old pattern (before templating).  You might want to consider switching that over to render the form via the `FormBuilder` class.

**Comment by mcwhorter72** [comment]
That form 'gets' data from the users.php to populate it. I can't figure out how to make the form operate as a stand alone page (not a modal) that pulls in the current user data so it can be edited by the user. This seems like basic functionality, I just can't get it to work. Is there an example somewhere?

**Comment by alexweissman** [comment]
Actually, it just gets some parameters (telling it which fields to show, which to hide, etc) from `users.php`.  The data itself is pulled in `form_user.php` through functions like `loadUser`.  Try taking a look at the documentation for [Bootsole 0.1.4](https://github.com/alexweissman/bootsole/tree/0.1.4).  I'm going to try to upgrade UF to use the newest version of Bootsole, which does templating for everything, pretty soon.  But in the meanwhile, the docs for the version used in UF (0.1.4) might be worth taking a look at.

**Comment by alexweissman** [comment]
If you want to post your code to a Gist, I can take a look at it.

**Comment by mcwhorter72** [comment]
OK, I got this to work. Was actually easy once I looked at what I was doing... So, I added 5 new user fields. However, when I update them on the form, the values lose their case. So, 'Jon Smith' is saved as 'jon smith' and 'Washington DC' is saved as 'washington dc'... I looked at the code, but couldn't figure out what code/file to edit... THANKS.

**Comment by alexweissman** [comment]
Cool.  What is going on in `api/update_user.php`?  Are you calling `strtolower` on the $_POST variables?
