### ISSUE TITLE
Why PHP's mail()?

### ISSUE THREAD

**Issue by ebrightTP** [alexweissman/UserFrosting#221]
I was looking at `class.mail.php` to see if I could send html templates.  I'm wondering if there is a particular reason that we are using PHP's built-in `mail()` function, instead of something like [PHPMailer](https://github.com/Synchro/PHPMailer) or another plugin that allows sending to a relay server.  

Incidentally, the process to change mail so that it can send html templates is:

    Add line 42:  public $type = "plain";
    Edit line 44: public function newTemplateMsg($template,$additionalHooks,$emailtype = "plain")
    Add line 49:  $this->type = $emailtype;
    Edit line 69: $header .= 'Content-type: text/'.$this->type.'; charset=iso-8859-1' . "\r\n";

Change any templates you want to send as html to have `"html"` as the third parameter.

**Comment by alexweissman** [comment]
This has come up before: see issue #21.  Basically, I was concerned about introducing extra dependencies.  But since we'll be using a lot of third-party packages anyway in the new version, switching to a more full-featured mail library is a good idea.  I've added it to the list in #199.
