### ISSUE TITLE
Stuck on registering new user

### ISSUE THREAD

**Issue by andrie81** [alexweissman/UserFrosting#222]
![capture](https://cloud.githubusercontent.com/assets/10769776/5972640/dae7befa-a854-11e4-93d4-da434e7799f3.JPG)

Successfully installed on my server.

Unfortunately, can't seem to register any new user after that. Can't find any error log in any of the folders.

HP Version	5.5.21
MySQL Version	5.5.40-cll

Any directions or way to have some error output? Thanks in advance.

**Comment by andrie81** [comment]
using Chrome Console, get these error. 

POST http://....../api/create_user.php 403 (Forbidden)
x.ajaxTransport.send           jquery-1.10.2.min.js:6 
x.extend.ajax                       jquery-1.10.2.min.js:6
(anonymous function)         register.php(200)
x.event.dispatch                  jquery-1.10.2.min.js:5
x.event.add.v.handle           jquery-1.10.2.min.js:5

**Comment by alexweissman** [comment]
Hmm, well it's giving you a 403 Forbidden error on `create_user.php`.  Do you have your server configured to prevent access to subdirectories?

**Comment by andrie81** [comment]
I've contacted my hosting provider and they disabled mod_security.
New user registration is working fine now. Thanks for your direction on this.
