### ISSUE TITLE
PKI authentication

### ISSUE THREAD

**Issue by mginx** [alexweissman/UserFrosting#223]
Besides user/password it would be very useful to add PKI authentication and  allow UserFrosting to use CAS

**Comment by alexweissman** [comment]
Isn't this more of a concern at the server level (e.g., setting up SSL) rather than the web application level?

**Comment by mginx** [comment]
The idea would be to extend userfrosting to be the front-end of the service enabling SSO on per-service for user/group  and delegating the actual work to CAS.

**Comment by alexweissman** [comment]
Ah ok, so you're talking about single sign-on.  There's been talk of using SAML or OAuth already: #202.

I should probably make it clear that I won't be implementing any more features until we rebuild the core UF as described in #199.

This project is too poorly organized and unwieldy as it is, I don't want to stuff any more features into it until we get the basics down :-)

**Comment by mginx** [comment]
Yes, that's what I had in mind. Thanks for clarification.
