### ISSUE TITLE
Suggestion: Add rate limiting on register/login attempts, and password hash compare against known weak passwords

### ISSUE THREAD

**Issue by sotiris84** [alexweissman/UserFrosting#224]
Hello, I just came across this post below and I thought to share here. I know userfrosting uses many of these, but I find the rate limiting and password hash compare extremely interesting. I hope you read the article and incorporate any feature you might like. Thanks! 
 
http://blog.codinghorror.com/the-god-login/

**Comment by alexweissman** [comment]
Yup, I agree.  These would be fairly simple to implement, too.

**Comment by alexweissman** [comment]
Added to feature request list: https://github.com/alexweissman/UserFrosting/wiki/Feature-request-list
