### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by andrie81** [alexweissman/UserFrosting#225]
Hi,

Been developing a cloud app using UF and it was great! It's really simple and clean when I get how it, load and works. Really move my project way ahead of its original schedule.

I'm a beginner in Java, when I run UF with Java Console one, i get:

" Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/. "

As I dig in, I get the feeling that somtimes later, that XMLHttpRequest  will not be used as standard anymore. Any direction I can go from here?

Thanks!

p/s: Maybe its nothing and I'm paranoia. Maybe I just like a clean console. LOL

**Comment by alexweissman** [comment]
Awesome, always happy to hear from people using UF in the wild.

I'm not sure if I understand what you mean by Java Console.  Do you mean Javascript?  If so, in which browser are you getting the message, and on which page?

**Comment by r3wt** [comment]
@alexweissman The latest version of Chrome has deprecated synchronous Ajax requests. as a work around, you can use  `$.ajaxOptions({})` to set ajax synchronous to true, then switch it back after your synchronous call, however the correct way is to use javascript promises like so

```js

$.getJSON(endpoind,function(data){
//do something
}).done(function(){
console.log('i\'m a great way to have a synchronous callback in ajax!);
//now you can nest the next step here.

**Comment by alexweissman** [comment]
Ah ok, yeah I knew that async's were not a best practice.  But the problem is that I wanted to be able to have modular functions that load data, like `loadUsers()`.  How could I achieve that with promises?

**Comment by alexweissman** [comment]
Ok, all ajax requests in 0.3.0 are now asynchronous!  Hurray for `Deferred`!
