### ISSUE TITLE
Content on the page just for certain groups

### ISSUE THREAD

**Issue by j0sk** [alexweissman/UserFrosting#227]
Sorry to spam this noobie question but I wasn't able to get it work I tried to read documentation and I googled quite lot.

I think it could be wise to add this kind of noobie examples to wiki/documentation for noobie users like me.

So I like to view some content on the page if user is member of that group. I have created a new group but I wasn't even able to ECHO user's group_ids or group_names.

I can ECHO the user_id:
<?php echo $loggedInUser->user_id; ?>

But how I should ECHO the user's groups?
This didn't work:
<?php echo $loggedInUserInGroup->group_id; ?>

Br,

-j0sk

**Comment by alexweissman** [comment]
You can load the logged in user's groups using the `loadUserGroups` function:

`$groups = loadUserGroups($loggedInUser->user_id);`

The function is defined in `models/secure_functions.php`.

I'm holding off on the documentation until we rewrite the code base to use a modern object-relationship mapper (basically an abstract way of interacting with the database).  Because at that point, the interface will probably look a lot different ;-)

**Comment by j0sk** [comment]
Thank you! I got it work. I'm not that much coder but I wrote this code to view some special content for user that is member in the group called Creator.

 <?php 
	// Function to check if selected group is part of the multidimensional array
	function multiArrayGroupSearch($search_for, $search_in) {
	    foreach ($search_in as $element) {
		if ( ($element === $search_for) || (is_array($element) && multiArrayGroupSearch($search_for, $element)) ){
		    return true;
		}
	    }
	    return false;
	}
	// To add all current user's groups in the variable
	$groups = loadUserGroups($loggedInUser->user_id);

	// This variable is true if user is in group Creator
	$in_creator_group = multiArrayGroupSearch("Creator", $groups) ? 'True' : 'False';

	// Show content if user is member of the group: Creator
	if ( $in_creator_group == "True" ) {
		echo "You are creator!<br />";
	}
	?>

**Comment by alexweissman** [comment]
Oh, I didn't realize that you just wanted to check if a user is a member of a group!  You can also use the `userInGroup($user_id, $group_id)` function!

**Comment by alexweissman** [comment]
Let me know if you have any more problems!
