### ISSUE TITLE
How to add pages to be secure?

### ISSUE THREAD

**Issue by lordtopcat** [alexweissman/UserFrosting#230]
Hi there,

I've looked everywhere on your site and here but can't find ANY information on how to add new pages that are secured by this framework?

I've added the pages to the account folder, and set permission levels in the admin panel, but I just get a blank white page when I go there. So do I need to add something to these pages?

Thanks.

**Comment by alexweissman** [comment]
Are you getting any messages in your php error log or brower console?

**Comment by lordtopcat** [comment]
Hi Alex,

Thanks for your quick reply.

It seems to be a problem on my end, (seems stupid of me) but I forgot to
update the links to some other reources I required.

The pages are now working, yay.

So to be clear, once pages are protected in the admin control panel, I
don't need to add anything else to said pages?

Cheers

**Comment by alexweissman** [comment]
Are you calling 
```
if (!securePage(__FILE__)){
    apiReturnError($ajax);
}
```
at the beginning of the script for that page?  That should be all you need.

**Comment by lordtopcat** [comment]
Awesome, thank you :)

**Comment by alexweissman** [comment]
Let me know if you have any more trouble!
