### ISSUE TITLE
Does isLoggedInUserInGroup work?

### ISSUE THREAD

**Issue by lordtopcat** [alexweissman/UserFrosting#232]
Hi guys,

Does isLoggedInUserInGroup work? If so, am I doing it wrong? lol

    if(isLoggedInUserInGroup(2)) {
    echo '<div style="float:right; padding-right:10px;"><a href="/events/account/admIndex.php"><img src="/events/img/admin.png" border="0" /></a></div>';
    }

Doesn't show to any user?

Would appreciate some help :)

Cheers

**Comment by alexweissman** [comment]
It's a static member of the `PermissionValidators` class.  So, try:
```
if(PermissionValidators::isLoggedInUserInGroup(2)) {
echo '<div style="float:right; padding-right:10px;"><a href="/events/account/admIndex.php"><img src="/events/img/admin.png" border="0" /></a></div>';
}
```

**Comment by alexweissman** [comment]
Let me know if you have any more trouble!
