### ISSUE TITLE
Sub-user implementation 

### ISSUE THREAD

**Issue by antoiner77** [alexweissman/UserFrosting#233]
Hello, I wonder about the creation/management of a sub-user solution .Is there a simple way to implement something like that: -A user can create and manage x number of sub-user
                                                
regards,
Antoine

**Comment by alexweissman** [comment]
Sure.  The best way would be to create a table that maps users to sub-users:

| id | user_id | sub_user_id |
| --- | ----- | ----- |
|  |  |  |

Make a new secure function `createSubUser` that creates a new user, adds them to some groups, and then associates the new user as a sub-user of the currently logged in user.

Then, you can grant permissions to your top-level Users group to run `createSubUser`.  If you want to limit them to a certain number of sub-users, create a permission function like:

```
hasLessThanXSubUsers(x){
   // Query the sub-user mapping table, and determine whether or not they have less than x sub-users
   // Return true or false accordingly
}
```

**Comment by antoiner77** [comment]
Thx, i will take a look at this.
