### ISSUE TITLE
Restricted User-Names + Display-Names?

### ISSUE THREAD

**Issue by TSRalex** [alexweissman/UserFrosting#235]
Do you have any suggestion, how to manage a restriction for user-names and display-names?

E.g. I would like to avoid, that users choose "pretending names" like "admin...." or "moderator...." etc.

**Comment by alexweissman** [comment]
Well, you could just use a blacklist in `api/create_user.php`, and check the submitted user name against an array of forbidden names.  Use `addAlert` and `apiReturnError` to generate an error message and halt the script.

**Comment by TSRalex** [comment]
Thank you very much for the idea - I´ll forward it to our programmer! :-)

**Comment by alexweissman** [comment]
Let me know if you have any more problems!
