### ISSUE TITLE
Prompt user to change password on next login

### ISSUE THREAD

**Issue by ebrightTP** [alexweissman/UserFrosting#236]
Is there a way for an Admin to flag a user so that when they next log in, they *must* input a new password?

**Comment by alexweissman** [comment]
Haha, I was *just* thinking about that today!  I'll add it to the feature list for 0.3.0.  

In the meanwhile, you could probably implement it based on the **activated** field, or add another column to the users table to keep track of new users and prompt them accordingly.

**Comment by alexweissman** [comment]
Added to the feature request list.
