### ISSUE TITLE
wrong getAbsoluteDocumentPath

### ISSUE THREAD

**Issue by mrday86** [alexweissman/UserFrosting#237]
I installed userfrosting in a folder named frost,this is the path:
/htdocs/web/frost
after, i added some new paths in the database (frost_filelist table)
"/emp" located in /htdocs/web/frost/emp
"../new" located in /htdocs/web/new
The first path give me no problems, but the second one yes: using
if (!securePage(__FILE__)){
    apiReturnError($ajax);
}
in every file located under the "/new" folder, like "/new/page.php", return false.
After some "debug", I found that this function getAbsoluteDocumentPath convert this string 
"/htdocs/web/new/page.php"
to this
http://mysite.it/frost//htdocs/web/frost
obviously this page cannot be found in the frost_pages table.
Some hint? Thanks

**Comment by alexweissman** [comment]
Hmm, so at the moment UF assumes that all of the files/directories that it manages will be located within the root UF directory.  Is there any way you can restructure your system so that `new/` is inside the `frost/` directory?

**Comment by mrday86** [comment]
Actually, the files in the ```new/``` directory contains the future index files of my site, so it's not my aim to put that files in the ```frost/``` folder (also if I can use the htaccess to mask this folder hierarchy). Since out of the ```frost/``` folder my only need is the database connection, would I lost something by omitting this:
```if (!securePage(__FILE__)){
    apiReturnError($ajax);
}``` ?
It would be great, for the next upgrade to develop this feature: adding files and folder out of the ```userfrosting folder```.
Thanks

**Comment by alexweissman** [comment]
Sure.  Actually in the next iteration, my plan is to keep all of model code out of the public directory entirely; something similar to what they do [here](http://code.tutsplus.com/tutorials/organize-your-next-php-project-the-right-way--net-5873).

**Comment by mrday86** [comment]
It's a good project, gl with it

**Comment by Mwai** [comment]
Sorry for going off topic, but I'm trying to change account root, for navigational purposes after user login. Can't seem to find a way how

**Comment by mrday86** [comment]
I can't understand, if you mean the group login redirect, you have to see the admin panel. I suggest you to open a new dedicated topic to get help in the right way

**Comment by alexweissman** [comment]
@Mwai please try changing the name of the account root folder in the `filelist` table.

**Comment by alexweissman** [comment]
Let me know if you have any more trouble!
