### ISSUE TITLE
Error when renaming register.php

### ISSUE THREAD

**Issue by andrie81** [alexweissman/UserFrosting#239]
Hi,

I received POST http://xx.xx/api/create_user.php 403 (Forbidden) error when i rename register.php.

Does UF check for a file list available in the root directory?

BTW, I've made a lot of changes to UF. When 0.3.0 comes out I expect that I would need to rewrite all the changes on the new versons?
Looking forward for 0.3.0!

**Comment by alexweissman** [comment]
Hi Andrie,

Thanks for using UF!  Yes, UF checks for the file in the `pages` table.  But, I am surprised that the problem is occurring in `api/create_user.php`, instead of whatever you renamed `register.php` to.  

Did you use the Site Authorization tool (when logged in as root user) to add the new page?

**Comment by alexweissman** [comment]
Also, yes you will probably need to rewrite your custom code for UF 0.3.0, but it will be worth it to make your code more maintainable in the long run.  I know, I will have to do it for my own website as well >_<  

Hopefully we can release some tutorials explaining how the new structure works.  In the meantime, you can get a sneak preview of the new routing/templating system here:
https://github.com/alexweissman/UserFrosting/blob/0.2.3/public/index.php

That one file, plus a bunch of HTML [templates](https://github.com/alexweissman/UserFrosting/tree/0.2.3/userfrosting/templates/pages/public), takes care of the entire public side of UF.

**Comment by andrie81** [comment]
Thanks for your time Alex,

Yes, I do notice Site Authorization have to be used when adding a new page but it seems that it only add pages within the /forms and /account directory. Should I manually add the page(s) in the database?

- Gonna try that and get back to you for the results.

**Comment by alexweissman** [comment]
Ahh, I forgot that you'll need to add any new subdirectories to the `filelist` table.  Sorry about that!

**Comment by andrie81** [comment]
Yes Alex, also notice that. Thanks for your respond.

But register.php is in the root directory with index.php and login.php

I tried and rename login.php to something else and it work just fine. Still figuring out where the permission checks is. Hahhaha...

Already check for file permission in my server. Everything looks fine to me. Change create_user.php from 0644 to 0755. Same results. I can now assume it's not file permission issue?

**Comment by alexweissman** [comment]
`api/create_user.php` shouldn't be doing any permissions checks unless you are trying to create a user as an admin (in which case it would display a permissions error, rather than throwing a 403).  This sounds like it must be a server config issue.  Are you using Apache?

**Comment by andrie81** [comment]
Apache Version	2.2.29
PHP Version	5.5.21
MySQL Version	5.5.40-cll
Architecture	x86_64
Operating System	linux

It would be great if you can give me a direction to start troubleshooting. I'm beating the bush right now. LOL.

Like you said, UF should display a permissions error but it's not. I'm opening this issue just in case I missed something with the workflow.

I appreciate your reply and help. UF is just fast to start developing when you understand how it works. Glad I hop in to UF.

**Comment by andrie81** [comment]
This is where the renamed ```register.php``` is denied.

```javascript
                var url = APIPATH + "create_user.php";
                $.ajax({  
                  type: "POST",
```

Nothing is changed in the original ```register.php``` and that makes me even more confused.

**Comment by alexweissman** [comment]
So, if you just change the filename back to `register.php`, and do nothing else, does it work again?

**Comment by andrie81** [comment]
I did made some modifications on the original ```register.php``` and that makes me wondering if the changes created the error. So i revert to the original file, rename it to something else. The error still occurred.

When i change it back to ```register.php``` it work again. Hahahah.. gremlins?

Still trying to figure out where the permission check is. Already rules out  ```fileslist``` and ```pages``` table.

**Comment by alexweissman** [comment]
Yeah, I just tried changing the filename from `register.php` to `whoo.php` in my local install, and I can still register a new user just fine.  Gremlins indeed.
There shouldn't be any permission check at all on `register.php` or `api/create_user.php`.  I don't suppose you have any custom `.htaccess` rules?

**Comment by andrie81** [comment]
Nope. Not even ```.htaccess``` exist in the root directory. I'm going to tackle this from a different approach I guess. I do make a heavy modification to UF.

I get the proper answer from you Alex, thanks for your great help. - The right route when user register.
```register.php``` -> ```api/create_user.php``` -> db functions etc

I'm all good and need to re-checked every modifications I made to see where the error comes from. I don't think it's from UF as you already tested it and it work fine.

I'll leave this to you to let it be open or close it.

**Comment by alexweissman** [comment]
Let me know if you're still having trouble!
