### ISSUE TITLE
Ajax create_user.php proper use?

### ISSUE THREAD

**Issue by kenjikato** [alexweissman/UserFrosting#240]
Sorry for the newb question, but I'm trying to do an Ajax POST call to the create_user.php and I'm just getting back 302.

I'm assuming I'm doing something wrong, but not sure what at this point.

I'm trying to do this request for a "unregistered" new user coming from a very simple client side mobile web page that is not being served from the server where my instance of UserFrosting is running (although I probably could do that).

Here's the POST request from a simple rest app like Paw (https://luckymarmot.com/paw):
POST http://MYSITE.com/USERFROSTING/api/create_user.php?user_name=testman&display_name=testman&email=testman%40example.com&password=Abc123&passwordc=Abc123&ajaxMode=true

But at this point I'm assuming it's just me doing something stupid.

Any chance of getting a simple example of how to use create_user.php as an Ajax call.

Thanks!

**Comment by andrie81** [comment]
Hi.. I think this would help?

https://github.com/alexweissman/UserFrosting/issues/158

I still can't get passed it tho. Now running to other problems related registration process.

**Comment by alexweissman** [comment]
By any chance, is the subdomain that you specify for `create_user.php` different from the subdomain of the page you're calling it from?  That could be causing the 302 redirect.

**Comment by kenjikato** [comment]
@andrie81 while that is useful for what I am doing, I'm actually just trying to do a simple registration purely through an Ajax call.

@alexweissman I am indeed calling the subdomain of creat_user.php from a different subdomain.  So that probably explains my current issue.

What I really want to do is have a predominantly offline mobile web app turned into a native mobile app via phonegap.  But I want the users to be able to sign up for an account that lets them store data in the cloud and share it when they are online.

I'm trying to call a rest service to do the signup on my backend service from the web app (where I'm doing a local provision of a temporary account to begin with to make initial use simple). Then when the user is ready and online I want them to signup for a full account and sync with the back end.

So far UserFrosting seems like it will fit the bill if I can figure out how to tackle this signup issue. So the calling "domain" is actually the local mobile web app which I'm guessing might lead to a cross domain problem.

Think of it this way.  The form and information is all collected in the local web app, and I want to have it fired over to my server via a rest call. I'm fine leaving out the password even (for security), and having the user sent an email or text message as part of the verification step, and setting up the password later.

Any suggestion are welcome. Thanks!

**Comment by alexweissman** [comment]
Ahh, gotcha.  So, UF is running your backend, and then you have a mobile app interacting with the backend via POST and GET requests.  Seems like we should be able to get it to work.

What happens if you specifically whitelist the mobile app's domain to allow Cross-domain requests?  You could put this in your `config.php`:
`header("Access-Control-Allow-Origin: http://yourdomain-you-are-connecting-from.com");`

See https://stackoverflow.com/questions/6871021/how-to-enable-cross-domain-request-on-the-server

**Comment by kenjikato** [comment]
@alexweissman I forgot about whitelisting. Basically I need to enable CORS to get this to work.

Then I thought this still my not work (unless I'm opening my server to the world with a * wildcard) because the calling agent is a mobile app from a phone from virtually any network, not a specific domain per say in my mind.

So I went and did some snooping around on stackoverflow after you put the idea in my head of CORS, and found this post http://stackoverflow.com/questions/13920782/phonegap-javascript-sending-cross-domain-ajax-request

Which led me to this in the phonegap docks: http://docs.phonegap.com/en/1.9.0/guide_whitelist_index.md.html

I will let you know if I hit any other bugs, but I think I'm good now.  UF is quickly turning into the solution that I've been looking for to manage users, and could very well drive my future projects. Thanks for creating a great resource!

**Comment by alexweissman** [comment]
No problem!  If you figure it out and want to add the solution to our [troubleshooting wiki](https://github.com/alexweissman/UserFrosting/wiki/Troubleshooting-UserFrosting), please do!

**Comment by kenjikato** [comment]
I think I'm almost there, but one last bit to get past.  I'm getting responses now that I setup a .htaccess file on my server that allows for a cross-domain request, but I'm getting back an error from the POST:

```{"errors":1,"successes":0}```

and when I go to the ```http://MYSITE.COM/USERFROSTING/api/user_alerts.php``` I see:

```[{"type":"danger","message":"Failed security question"},{"type":"danger","message":"Aww hellllls no!"}]```

So, I'm assuming that this is because I'm either not using the captcha or some other security element when I'm making the request.  I have my own locally served html file with an interface in the mobile app that lets the user enter there sign up data and then submit it. To help simplify what I've done below is a javascript code snippet using jQuery that's making the call from my mobile web app.
```
<script>
	$(document).ready(function () {
	    $.ajax({
	    	type: "POST",
	    	dataType: 'json',
	      	data: {user_name: 'John Smith', display_name: 'jsmith', email: 'me@example.com', password: 'abc123', passwordc: 'abc123', ajaxMode: true},
	      	url: "http://MYSITE.COM/USERFROSTING/api/create_user.php",
	      	success: function (jsonData) {
	        	alert("success")
	        	alert(jsonData);
	      	},
	      	error: function(errorObj) {
	        	alert(errorObj.statusText);
	        },
	    });
	});
</script> 
```

Do I need to have the captcha as part of my app (I guess I would have to call this from the server first?), do I need to encrypt the data on my side before sending it, or is there something else I should be looking at to troubleshoot this?

Thanks again!

**Comment by alexweissman** [comment]
It's not the captcha, it's the honeypot.  

If you look in `register.php`, you'll see a hidden field called `spiderbro` that has a very specific value.  This value needs to be received by `create_user.php`, otherwise it assumes that a bot has submitted the request.

See [this article](http://solutionfactor.net/blog/2014/02/01/honeypot-technique-fast-easy-spam-prevention/) for more information on the honeypot technique.

**Comment by kenjikato** [comment]
OK, I have the honeypot working now. But I'm still getting back an error:
```{"errors":1,"successes":0}```

and the following message on the ```user_alerts.php``` page: 
```
[{"type":"danger","message":"Failed security question"}]
```

After searching through UF code I'm assuming this is now the failed captcha.

So, is there a simple way to turn off the captcha verification for ajax calls (without pulling the code out), or is there a way to add the captcha using a GET call first so that I can display it on the mobile apps sign up page?

Security wise I guess that's not the best thing to do.  On the other hand a spider or hacker would need to know about making a GET call first to get the validation captcha parameter before it could even submit the user registration using a PUT.

Thanks yet again!

**Comment by kenjikato** [comment]
**Success!!!**
After some more snooping around in UF I found the ```generate_captcha.php``` in the API directory.

So, the question I now have is how does UF know that the captcha validation came from me?

Rather, if I had 100 users all registering within the span of say 5 minutes. How does UF understand that the GET captcha that was sent to my device is the one that I'm sending back in the POST from my device, and not one of the other 99 users registering in that 5 minute time frame?

Also, it would be nice to have an admin way of turning the captcha off if I didn't want it as part of the validation, rather than having to remove the code from UF.

**Comment by alexweissman** [comment]
@kenjikato sorry for not replying, I must have missed this one!  The generated captcha is stored in the client's session, so when a client submits the captcha, it is compared against the one stored in **their own personal session**.

I will make captcha a settable preference in the upcoming 0.3.0.  

Let me know if you have any more trouble!
