### ISSUE TITLE
Creating Manger Account type

### ISSUE THREAD

**Issue by webofnithin** [alexweissman/UserFrosting#242]
Hi,
I want to create a manager group .A manager should be able to create new users,edit,delete them.I gave page level authorization and group level still i'm getting a 404 error while signing in.Please help 
this how my page level permission looks like 
![screen shot 2015-02-25 at 12 12 31 pm](https://cloud.githubusercontent.com/assets/1277421/6366170/a88858be-bce7-11e4-8e7c-f10b4ca708a8.png)

And Permissions for my Manger Group 

* createUser
* loadSitePages
* loadUser
* loadUsers
*

**Comment by alexweissman** [comment]
If you go into your `models/config.php`, you'll see a constant `LOG_AUTH_FAILURES`.  Set that to `true`, then try signing in again.  Any authorization-related problems will be logged to your php error log.  So, please post your php error log once you have done that.
Thanks, and welcome to UF!

**Comment by webofnithin** [comment]
Hi Alex,
Thanks For the reply.. 

[Wed Feb 25 17:15:49 2015] [error] [client 106.51.35.96] File does not exist: /home/pjhomel/public_html/404.shtml
[Wed Feb 25 17:15:49 2015] [error] [client 106.51.35.96] File does not exist: /home/pjhomel/public_html/user/logout.php

This is what's in my error log ..

**Comment by ebrightTP** [comment]
What did you set the homepage to for the Manager group?  

Also, where is the user/ folder on your server? Is it in the public_html/ folder?

**Comment by webofnithin** [comment]
forms/table_users.php

**Comment by alexweissman** [comment]
Did you add the `user` folder to the `filelist` table? This table tells UF which subdirectories to look in for files.

**Comment by webofnithin** [comment]
I added it..Still no effect.. 
Thanks

**Comment by alexweissman** [comment]
Well, you also probably don't want to set `forms/table_users.php` as the home page.  That just generates the table, not a complete web page.  Try setting it to `account/users.php`.

Also, I'm not sure why it's trying to send you to `user/logout.php`.  Does that file actually exist?  Did you move all the files from `account` to `user` or something?

**Comment by alexweissman** [comment]
Let me know if you're still having problems!
