### ISSUE TITLE
config.php on new pages not being called

### ISSUE THREAD

**Issue by DynamoDesignDevelopment** [alexweissman/UserFrosting#245]
I created a new php page in the account directory.

I included this code like the other pages: 

require_once("../models/config.php");

However when I call a function I created from an html button, it seems as if nothing from the config.php is being loaded because the console says Uncaught ReferenceError: loadCurrentUser is not defined

Am I missing something? Thanks.

**Comment by alexweissman** [comment]
`loadCurrentUser` is a Javascript function, not a PHP function.  So, including `models/config.php` won't help.  You need to make sure that all of the correct JS files are included.  

To do this, make sure you are calling `renderAccountPageHeader` at the beginning of the page, similar to how it is done in `dashboard.php`.  This function will automatically insert the necessary JS `<script>` tags.

**Comment by DynamoDesignDevelopment** [comment]
That worked for me thanks!

I have another problem trying to update user fields without the use of a submit form button.

I have a form which has a field called 'collection'. I added what was necessary in the database and tested it by changing one of the fields in the account_settings.php to see if it would work, it does. However from the page I created mentioned in my first post I call an update function in javascript from html buttons to update the database:

var request;
		  
		var url = APIPATH + 'update_user.php';
		// abort any pending request
		if (request) {
			request.abort();
		}
		var $form = $("form[name='updateAccount']");
		var $inputs = $form.find("input");
		// post to the backend script in ajax mode
		var serializedData = $form.serialize() + '&ajaxMode=true';
		// Disable the inputs for the duration of the ajax request
		$inputs.prop("disabled", true);
	
		// fire off the request
		request = $.ajax({
			url: url,
			type: "post",
			data: serializedData
		})
		.done(function (result, textStatus, jqXHR){
			var resultJSON = processJSONResult(result);
			// Render alerts
			alertWidget('display-alerts');
			
		}).fail(function (jqXHR, textStatus, errorThrown){
			// log the error to the console
			console.error(
				"The following error occured: "+
				textStatus, errorThrown
			);
		}).always(function () {
			// reenable the inputs
			$inputs.prop("disabled", false);
		});

I'm not getting any errors when calling this in the function anymore, but it is not updating the users collection. Is that how I would submit the information in the form? I changed 
var $form = $(this);
to
var $inputs = $form.find("input"); 

but I'm not sure that's how its done. Any help would be greatly appreciated. thanks.

**Comment by lilfade** [comment]
Check out how plugin settings are updated in the settings page that may be
what your looking for.

**Comment by alexweissman** [comment]
Is this the entire JS code?  Make sure that you wrap the entire thing in 
```
$("form[name='updateAccount']").submit(function(e){
    e.preventDefault();


});
```

**Comment by DynamoDesignDevelopment** [comment]
I tried putting that in like it is in other pages, but I still can't get it working. Here is the page code without that implemented.

<?php

require_once("../models/config.php");

/*
if (!securePage(__FILE__)){
  // Forward to index page
  addAlert("danger", "Whoops, looks like you don't have permission to view that page.");
  header("Location: index.php");
  exit();
}
*/

setReferralPage(getAbsoluteDocumentPath(__FILE__));

?>

<!DOCTYPE html>
<html lang="en">
<?php
	echo renderTemplate("head.html", array("#SITE_ROOT#" => SITE_ROOT, "#SITE_TITLE#" => SITE_TITLE, "#PAGE_TITLE#" => "page name"));
  ?>

<head>
	



	<link rel="stylesheet" href="../css/bootstrap.css">
	<link rel="stylesheet" href="../css/colorbox.css">

</head>

<body background="../pattern.png">

	
		
	<div class="headerContainer">
    
		<p><a class="iframe" href="../login.php">
			<div class="headerLogo">
				<img src="../logo.svg" width="100px">
			</div>
		</a></p>
		
		<script>
			$(document).ready(function(){
				$(".iframe").colorbox({iframe:true, width:"80%", height:"80%"});
			});
		</script>
		
		<a href="dashboard.php">
		  <div class="headerOption">
			<div class="headerOptionName">
				<h13> BROWSE SETS </h13>
			</div>
		  </div>
		</a>
		
		<a href="collection.php">
		  <div class="headerOption">
			<div class="headerOptionName">
				<h13> COLLECTION </h13>
			</div>
		  </div>
		</a>

		<div class="headerLG">
			<a href="account_settings.php">
				<button class="btn btn-success submit lg">Account</button>
			</a>

			<a href="logout.php">
				<button class="btn btn-success2 submit">Logout</button>
			</a>
		</div>
	  
	</div>
	

	
	<script src="../viewSet.js"></script>
	
	
	
	
	
	<form class="form-horizontal" role="form" name="updateAccount" action="update_user.php" method="post">	  
		<input type="hidden" name="csrf_token" value="<?php echo $loggedInUser->csrf_token; ?>" />
		<input type ="text" name="collection" value="" />
	</form>

<script>

	function updateCollection(card){
		
		// Get id of the logged in user 
		var user = loadCurrentUser();
		
		var collection = [];
		var set = [];
		
		for (var i = 0; i < 10; i++)
		{
			collection[i] = [];
		}
		
               //testing with empty values
		console.log("collection: " + collection);
	
		alertWidget('display-alerts');

		// Set default form field values
		$('form[name="updateAccount"] input[name="collection"]').val( collection );

		var request;		
		
		var url = APIPATH + 'update_user.php';
		// abort any pending request
		if (request) {
			request.abort();
		}
		var $form = $("form[name='updateAccount']");
		var $inputs = $form.find("input");
		// post to the backend script in ajax mode
		var serializedData = $form.serialize() + '&ajaxMode=true';
		// Disable the inputs for the duration of the ajax request
		$inputs.prop("disabled", true);
	
		// fire off the request
		request = $.ajax({
			url: url,
			type: "post",
			data: serializedData
		})
		.done(function (result, textStatus, jqXHR){
			var resultJSON = processJSONResult(result);
			// Render alerts
			alertWidget('display-alerts');
			
		}).fail(function (jqXHR, textStatus, errorThrown){
			// log the error to the console
			console.error(
				"The following error occured: "+
				textStatus, errorThrown
			);
		}).always(function () {
			// reenable the inputs
			$inputs.prop("disabled", false);
		});
	
		// prevent default posting of form
		event.preventDefault();   		
	
	}
	</script>
	
	
	
	
	
	
	
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<script type="text/javascript" src="http://arrow.scrolltotop.com/arrow79.js"></script>

	
</body>


</html>

**Comment by alexweissman** [comment]
So, your browser console should tell you if the form is actually being submitted.  Look to see if it's POSTing to `update_user.php` when you click the button.

One thing I notice is that the way you're implementing the buttons on your form is a little funky.  You shouldn't need to wrap them in `<a>` tags.  Just do:
`<button type="submit" class="btn btn-success submit lg">Account</button>`

Also, the button that submits the form should be inside the `<form>` block.  Not sure exactly what you're trying to do, but I'd do something like:

```
    <form class="form-horizontal" role="form" name="updateAccount" action="update_user.php" method="post">    
        <input type="hidden" name="csrf_token" value="<?php echo $loggedInUser->csrf_token; ?>" />
        <input type ="text" name="collection" value="" />
        <button type="submit" class="btn btn-success submit lg">Account</button>
        <a href="logout.php" class="btn btn-success2 submit">Logout</a>
    </form>
```

Notice how the "Logout" button is just a link that we've styled to **look like** a button, while the "Account" button is an **actual** button that submits the form.

**Comment by DynamoDesignDevelopment** [comment]
The console just displays "collection: ,,,,,,"). But no form submission results.

There is no 1 single button to submit the form data, there are multiple buttons created in the viewSet.js file being loaded. I want those buttons to submit the form data to update the database. (the form will be hidden from view)

If those buttons cannot submit the form data to the database...how can I just update the database without the use of a form? if its possible

Thanks for the help btw, i'm obviously not that knowledgeable in php and html, i'm used to actionscript. But this part is all I need to get what i'm trying to do to work.

**Comment by alexweissman** [comment]
You don't strictly need to use `<form>`, but it is a best practice.  And, it is the only way to have jQuery respond to the `submit` event.  You could use a different event, like `click`, and tie that directly to the button:
```
$('.btn-success').on('click', function(e){
    updateCollection(  );
});
```
But, I'm not sure exactly what you're trying to do.  The only way to update the database is by sending a request to a PHP script.  The call to `$.ajax` is what makes that request.

I would recommend searching around on StackOverflow, these are general-purpose questions about Javascript/jQuery that could be better answered there.

[This tutorial](https://www.airpair.com/js/jquery-ajax-post-tutorial) also has a good explanation, especially since it gives an overview of HTTP requests/responses at the beginning.

**Comment by alexweissman** [comment]
Let me know if you're still having any problems!
