### ISSUE TITLE
How can I get hold of the current session

### ISSUE THREAD

**Issue by intdev03** [alexweissman/UserFrosting#246]
Hi,
UserFrosting sits on top of my applicatin.User logs into my app through userfrosting code but then my code has to get hold of the session.How do I do that?
Sorry this may be a basic question,I am pretty new to php.

Thanks,
Ga

**Comment by alexweissman** [comment]
No problem, welcome to UF!  The session is just stored in the PHP global session variable, `$_SESSION`.  You can also access the currently logged-in user through the `$loggedInUser` variable.
