### ISSUE TITLE
mysql suddenly stopped after using uf,the error log shows this.Any reason why?

### ISSUE THREAD

**Issue by intdev03** [alexweissman/UserFrosting#247]
2015-03-01 09:58:20 4728 [ERROR] InnoDB: Attempted to open a previously opened tablespace. Previous tablespace mysql/innodb_table_stats uses space ID: 1 at filepath: .\mysql\innodb_table_stats.ibd. Cannot open tablespace usrm/uf_configuration which uses space ID: 1 at filepath: .\usrm\uf_configuration.ibd
InnoDB: Error: could not open single-table tablespace file .\usrm\uf_configuration.ibd
InnoDB: We do not continue the crash recovery, because the table may become
InnoDB: corrupt if we cannot apply the log records in the InnoDB log to it.
InnoDB: To fix the problem and start mysqld:
InnoDB: 1) If there is a permission problem in the file and mysqld cannot
InnoDB: open the file, you should modify the permissions.
InnoDB: 2) If the table is not needed, or you can restore it from a backup,
InnoDB: then you can remove the .ibd file, and InnoDB will do a normal
InnoDB: crash recovery and ignore that table.
InnoDB: 3) If the file system or the disk is broken, and you cannot remove
InnoDB: the .ibd file, you can set innodb_force_recovery > 0 in my.cnf
InnoDB: and force InnoDB to continue crash recovery here.

**Comment by alexweissman** [comment]
Hmm, haven't seen that before.  What web server are you using?

**Comment by intdev03** [comment]
I am using the uWamp stack.Its just a bundled(zip) version of wamp.If you ask for webserver it would be APACHE

**Comment by alexweissman** [comment]
Interesting.  `uf_configuration` is the first table that gets created by the installer, so it sounds like this is not a UF-related problem.  

I found this thread: https://stackoverflow.com/questions/18022809/xampp-mysql-shutdown-unexpectedly.  Just make sure you back up any important data before you go around deleting DB files ;-)

**Comment by intdev03** [comment]
I tried the solution.But it doesnt work.Also it created another ibdata1 file and mysql doesnt want to start

**Comment by intdev03** [comment]
okie,i also deleted the log files and mysql is started now,but the schema uf(as configured ) is corrupted.Any idea/root cause of this error?In case this happens again?

**Comment by alexweissman** [comment]
Not really sure, but I'm adding this problem to the troubleshooting Wiki (https://github.com/alexweissman/UserFrosting/wiki/Troubleshooting-UserFrosting#mysql-shuts-down-unexpectedly-after-installing-userfrosting).
