### ISSUE TITLE
Minor typo on install page

### ISSUE THREAD

**Issue by ahouston** [alexweissman/UserFrosting#249]
Hi,

This is pretty minor, but thought I'd mention it as it's a one character fix.

On wizard_root_user.php on the install, the following info is presented:

Database setup complete, please create the master (root) account. The configuration token can be found in the 'uc_configuration' table of your database, as the value for 'root_account_config_token'.

That should read "...found in the 'uf_configuration' table..."

**Comment by alexweissman** [comment]
Thanks, good catch!  Actually, it should really use whatever DB prefix the developer specifies, come to think of it...

**Comment by r3wt** [comment]
pr was merged. closing
