### ISSUE TITLE
Line 138 funcs.php boolean comparison of null value

### ISSUE THREAD

**Issue by r3wt** [alexweissman/UserFrosting#25]
Its not a big issue, but line 138 is improper comparison because you are using a boolean comparison operator to compare a non boolean value.

instead of  

`if($salt === null)`

should be

`if(empty($salt) && $salt == null)`

but 

`if($salt ==  null)` is probably as much as you need for something as trivial as password hashing.

this being said, it is my opinion that the function should be rewritten as follows:

    function generateHashMD5($plainText, $salt = false) {
	if (!$salt || empty($salt))
	{
		$salt = substr(md5(uniqid(rand(), true)), 0, 25);
		// Returns a 65-character hexadecimal string
		return $salt . sha1($salt . $plainText);
	}
	else
	{
		$salt = substr($salt, 0, 25);
		// Returns a 65-character hexadecimal string
		return $salt . sha1($salt . $plainText);
	}	
    }

notice the second line of the function first checks if salt is false, OR if salt is empty. this prevents erroneous exclusion of salt in cases where an empty string was mistakenly passed to the function as `$salt`.

this is an effort to limit the occurence of weak salts. it is still possible to defeat this mechanism by passing in true as the second parameter, but that could be prevented by rewriting it as

if (!$salt || empty($salt) || $salt === true)

but its probably overkill since users of the software are unlikely to mess with these functions, but its possible they could mistakenly overwrite them in the login or registration pages

**Comment by alexweissman** [comment]
I believe this issue was rendered moot with the addition of the `password` library.
