### ISSUE TITLE
Issue with Users Page

### ISSUE THREAD

**Issue by dlbass** [alexweissman/UserFrosting#254]
This is a fresh install of UserFrosting, so I probably messed something up in the install. When I go to view the Users page as the root account, I see this:
![image](https://cloud.githubusercontent.com/assets/4282090/6490185/067a652a-c26a-11e4-9de1-dc5b4284a858.png)

As an administrator, I see this:
![image](https://cloud.githubusercontent.com/assets/4282090/6490193/1a6c7d48-c26a-11e4-93d1-5c30ee7faf03.png)
 
And if I click back to the Dashboard from the Users page as an administrator, this happens:
![image](https://cloud.githubusercontent.com/assets/4282090/6490201/313c1c36-c26a-11e4-809e-a73055802e42.png)

Any ideas what is wrong?

**Comment by alexweissman** [comment]
Hmm, it is odd that none of the user information is showing up even when you're logged in as the root user.  Can you check to make sure that all the tables were created properly?  For example, are there any rows in the `users` table?  How about the `group_action_permits` table?

**Comment by dlbass** [comment]
I guess they are all there, the two tables you mentioned have content. 

users shows both users I created.

group_action_permits:

![image](https://cloud.githubusercontent.com/assets/4282090/6491458/e6f089ba-c272-11e4-893c-e7bd0f654a88.png)

**Comment by alexweissman** [comment]
Did you move/rename the page directories by any chance?  Also, any errors showing up in your PHP error log?

**Comment by dlbass** [comment]
I did move the files out of the extracted folder into the directory above before I ran the installer. After the installer, nothing was moved.

Here are two errors from the tail end of the error.log:
[Wed Mar 04 12:25:21.933063 2015] [:error] [pid 11948] [client 172.19.10.17:58477] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/userfrosting/forms/table_users.php on line 153, referer: http://172.19.1.58/userfrosting/account/users.php
[Wed Mar 04 12:25:21.933138 2015] [:error] [pid 11948] [client 172.19.10.17:58477] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/userfrosting/models/template_functions.php on line 134, referer: http://172.19.1.58/userfrosting/account/users.php

**Comment by alexweissman** [comment]
Weird, all I see on line 153 of `table_users.php` is:
```
 $users[$user_id]['user_status_style'] = "default";
```

It sounds to me like the problem is with the `$users` array that is being loaded from `loadUsers`.  Can I see your `users` table?

**Comment by dlbass** [comment]
![image](https://cloud.githubusercontent.com/assets/4282090/6493600/5dd2a258-c281-11e4-84e3-3dcfbbb4fc1c.png)

Does this show what you need to see?

**Comment by alexweissman** [comment]
This looks good.  And, you checked to make sure that you have PDO installed and enabled?

**Comment by dlbass** [comment]
I am not sure what should be after the = in the last line in this screenshot, it took forever to find this, and it looks like PDO is enabled, but maybe has an invalid configuration.

![image](https://cloud.githubusercontent.com/assets/4282090/6495013/d8c96fbe-c28b-11e4-906b-9c0bcf85c133.png)

**Comment by alexweissman** [comment]
Let's try testing the `fetchAllUsers` function (unsecured version of `loadUsers`) directly.  Create a page somewhere like:

```
<?php

require_once("models/config.php");

$users = fetchAllUsers();
echo "<pre>";
print_r($users);
echo "</pre>";

?>

See if that outputs anything.

**Comment by dlbass** [comment]
It outputs this:

Array
(
    [] => 1
)

**Comment by alexweissman** [comment]
Whoa.  Well then, looks like we found the problem.  It should be returning an array of users, keyed by their ids.  Something like:

```
Array
(
[1] => Array ( "user_name" => "blah", "display_name" => "Bleh", ...)
)
```

It doesn't look like [`fetchAllUsers`](https://github.com/alexweissman/UserFrosting/blob/master/models/db_functions.php#L220) has changed in any of the recent pulls, nor does it look like a problem with your DB structure.  So, I really feel like it must be a problem with DB configuration.  Are you sure there aren't any DB-related errors turning up in your php error log?

**Comment by dlbass** [comment]
Thanks for troubleshooting this.

mysql/error.log is clean

syslog is clean

These are the only errors I can find:
```
user@ubuntu-webserver:~$ tail /var/log/apache2/error.log
[Wed Mar 04 18:56:47.259582 2015] [:error] [pid 1228] [client 172.19.13.34:50072] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/userfrosting/forms/table_users.php on line 151, referer: http://172.19.1.58/userfrosting/account/users.php
[Wed Mar 04 18:56:47.259586 2015] [:error] [pid 1228] [client 172.19.13.34:50072] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/userfrosting/forms/table_users.php on line 152, referer: http://172.19.1.58/userfrosting/account/users.php
[Wed Mar 04 18:56:47.259589 2015] [:error] [pid 1228] [client 172.19.13.34:50072] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/userfrosting/forms/table_users.php on line 153, referer: http://172.19.1.58/userfrosting/account/users.php
[Wed Mar 04 18:56:47.259711 2015] [:error] [pid 1228] [client 172.19.13.34:50072] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/userfrosting/models/template_functions.php on line 134, referer: http://172.19.1.58/userfrosting/account/users.php
[Wed Mar 04 18:56:47.259735 2015] [:error] [pid 1228] [client 172.19.13.34:50072] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/userfrosting/models/template_functions.php on line 134, referer: http://172.19.1.58/userfrosting/account/users.php
[Wed Mar 04 18:56:47.259747 2015] [:error] [pid 1228] [client 172.19.13.34:50072] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/userfrosting/models/template_functions.php on line 134, referer: http://172.19.1.58/userfrosting/account/users.php
[Wed Mar 04 18:56:47.259761 2015] [:error] [pid 1228] [client 172.19.13.34:50072] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/userfrosting/models/template_functions.php on line 134, referer: http://172.19.1.58/userfrosting/account/users.php
[Wed Mar 04 18:56:47.259778 2015] [:error] [pid 1228] [client 172.19.13.34:50072] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/userfrosting/models/template_functions.php on line 134, referer: http://172.19.1.58/userfrosting/account/users.php
[Wed Mar 04 18:56:47.259786 2015] [:error] [pid 1228] [client 172.19.13.34:50072] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/userfrosting/models/template_functions.php on line 134, referer: http://172.19.1.58/userfrosting/account/users.php
[Wed Mar 04 18:56:47.259794 2015] [:error] [pid 1228] [client 172.19.13.34:50072] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/userfrosting/models/template_functions.php on line 134, referer: http://172.19.1.58/userfrosting/account/users.php

**Comment by alexweissman** [comment]
Really, really strange.  What happens if we try to just do a barebones PDO request to the `users` table:

```
<?php

require_once("models/config.php");

echo "<pre>";

global $db_table_prefix;

$results = array();

$db = pdoConnect();

$sqlVars = array();

$query = "select {$db_table_prefix}users.id as user_id, user_name, display_name, email, title, sign_up_stamp, last_sign_in_stamp, active, enabled, primary_group_id from {$db_table_prefix}users";

$stmt = $db->prepare($query);
$stmt->execute($sqlVars);

while ($r = $stmt->fetch(PDO::FETCH_ASSOC)) {
    print_r($r);
}

echo "</pre>";

?>
```

**Comment by dlbass** [comment]
I'm guessing that works as you'd expect it to.

```
Array
(
    [user_id] => 1
    [user_name] => derrickb
    [display_name] => Derrick B
    [email] => derrickb@example.com
    [title] => Master Account
    [sign_up_stamp] => 1425482293
    [last_sign_in_stamp] => 1425562495
    [active] => 1
    [enabled] => 1
    [primary_group_id] => 2
)
Array
(
    [user_id] => 2
    [user_name] => johnc
    [display_name] => John C
    [email] => johnc@example.com
    [title] => CTO
    [sign_up_stamp] => 1425482382
    [last_sign_in_stamp] => 1425491095
    [active] => 1
    [enabled] => 1
    [primary_group_id] => 1
)

**Comment by alexweissman** [comment]
Yes.  Wow, this makes no sense.  What version of PHP are you using?

**Comment by dlbass** [comment]
![image](https://cloud.githubusercontent.com/assets/4282090/6513090/215a24aa-c33e-11e4-9545-e33a01df2a28.png)

**Comment by lilfade** [comment]
Try this and see if pdo is even loaded

```php
if (class_exists('PDO')){ echo 'pdo good';}
```

**Comment by dlbass** [comment]
![image](https://cloud.githubusercontent.com/assets/4282090/6513552/630e98e2-c341-11e4-9c01-86f18bbc42e8.png)

**Comment by lilfade** [comment]
Did all the js files make it in /models/js?

**Comment by dlbass** [comment]
user@ubuntu-webserver:~$ ls /var/www/html/userfrosting/models/js
ls: cannot access /var/www/html/userfrosting/models/js: No such file or directory

user@ubuntu-webserver:/var/www/html/userfrosting/models$ ls
authorization.php    db-settings.php      password.php
chrome.php           error_functions.php  post.php
class.mail.php       form_builder.php     rb.php
class.user.php       funcs.php            secure_functions.php
class_validator.php  languages            table_builder.php
config.php           mail-templates       template_functions.php
db_functions.php     page-templates       validation

**Comment by lilfade** [comment]
What version did you download master or on of the numbered versions?

**Comment by alexweissman** [comment]
Well the weird thing is that the code that we tested is basically the same code as in `fetchAllUsers`, just outside of the function and the `try...catch` block.

**Comment by dlbass** [comment]
I am fairly certain I downloaded from this link: https://github.com/alexweissman/UserFrosting/zipball/master

**Comment by lilfade** [comment]
Yes that's a odd problem I've never come across. I might recommend checking config.php for errors and double check and make sure all files are uploaded and have correct permissions. I haven't had issues on Ubuntu with UF so I'm not sure what else to tall you to try unfortunately.  You could double check your apache config and make sure your not inadvertently blocking js (doubtful since the css is working from the ss' s).

**Comment by alexweissman** [comment]
I don't think this is a JS issue.  We tried testing `fetchAllUsers` individually, and it doesn't return the correct array of users.

**Comment by alexweissman** [comment]
[This issue](https://github.com/laravel/framework/issues/4825) in Laravel might be relevant.  Same version of PHP, on Ubuntu, similar problem with database fetching.

**Comment by alexweissman** [comment]
Holllld on, could this just be an operator precedence issue?  What happens if you add in parentheses in line 239 of `model/db_functions.php`:

```
while (($r = $stmt->fetch(PDO::FETCH_ASSOC)) && ($i < $limit)) {
```

**Comment by alexweissman** [comment]
Shit, yeah: http://php.net/manual/en/language.operators.precedence.php

Notice that `=` has precedence lower than `&&` but higher than `and`.  It was the recent pull request that messed this up.

**Comment by dlbass** [comment]
Adding the parentheses corrected the issue on the root user not seeing users, but the admin user still can't see them.

**Comment by alexweissman** [comment]
Sweet, I've reverted the errant changes.  Sorry about that!

**Comment by OlaviSau** [comment]
Could you actually put that into the UF version up right now? Got the same error, fixed with parentheses.

**Comment by alexweissman** [comment]
Hmm, I reverted the code back to the way it was 5 days ago; have you pulled the latest version?

**Comment by OlaviSau** [comment]
Hmm...I think i pulled it latest like 2 days ago?

**Comment by alexweissman** [comment]
Weird, did you get the zipball?

**Comment by OlaviSau** [comment]
And yeah :)

**Comment by alexweissman** [comment]
Cool, glad you got it figured out.
