### ISSUE TITLE
Registration form not allowing registration?

### ISSUE THREAD

**Issue by AgentScreem** [alexweissman/UserFrosting#255]
So, I'm implementing UF on my site, however the registration form isn't allowing users to register. My friend and I have both used the registration page edited with CSS, and unedited. It highlights the boxes in green (validating that the required information is entered) but doesn't go any further. User registration is on.

Below is a screenshot of where the process ends and doesn't continue:

![issue](https://cloud.githubusercontent.com/assets/11327030/6500212/7bd0dd2a-c343-11e4-86eb-3e7406b3c03b.PNG)

The user is also not created in the DB.

Anyone got any ideas of what the issue may be here?

**Comment by normington** [comment]
I had a problem similar to this and it turned out to be that my version of php was too old. Can you check your php version? Does anything turn up in the php error log when you try to register?

**Comment by AgentScreem** [comment]
My current PHP version is 5.5.

**Comment by normington** [comment]
Cool, that should be okay then - not the same as the issues I was seeing! Is there anything reported in the php error log?

**Comment by AgentScreem** [comment]
No there isn't, however I've noticed in the Chrome Console that is gives the error "403 (Forbidden)" and am in contact with my hosting company to see if they know anything that will resolve this.

**Comment by AgentScreem** [comment]
**Resolved!**

My hosting company advised that it was their Mod_Security rule that triggered, and they have since whitelisted it.
