### ISSUE TITLE
Group Restricted to specific files

### ISSUE THREAD

**Issue by jabbersquat** [alexweissman/UserFrosting#257]
Instead of having to manually tick the permission of each new page I add (which I plan to add a few), I used the following code to on new page to restrict to a particular group:
```
$user_id = ($loggedInUser->user_id);
$in_group = userInGroup($user_id, '3' );

if ( $in_group == "true" ) { ... } 
```
This works great for the page, but each page has links to files like jpgs, gifs, mp3s, etc.  Once a logged in user has the full url of one of those files, the user no longer needs to be logged in to see those files because those files don't have that restriction the page does.  Is there a way to only restrict access to all files in a directory?

Sorry if this is something easy and I am just missing it, but please help.

**Comment by alexweissman** [comment]
How about doing something like this: https://stackoverflow.com/questions/9963284/restrict-access-to-image-files-for-logged-in-users-only-in-php?

The main point is that you will need to put the images in a non-public folder (so, not your `public_html` or whatever folder).  That way, people can only access them through a PHP script, which *does* have access to that folder.

I would also strongly recommend against hardcoding your authorization routines.  What if you want to change the access rules at some point?  You'd have to go back and change all your code.  Use the page-level and function-level authorization.  If you don't want to manually check everything through the interface, you could write a script that updates the database to give appropriate permissions for a large number of users/groups.

**Comment by alexweissman** [comment]
Let me know if you're still having problems.
