### ISSUE TITLE
Install failing on wizard_site_config.php

### ISSUE THREAD

**Issue by thankably** [alexweissman/UserFrosting#262]
I have triple checked my db settings, and using PHP Version	5.4.38 MySQL Version 5.6.23 and just verified pdo is enabled. It is on a shared server, but haven't had issues installing or doing anything else recently.

**Comment by anthonybartoli** [comment]
What does your PHP error log say? 

I was able to successfully install UF on a shared hosting account with HostGator using PHP 5.4.38 with Percona 5.5.40-36.1. 

I did get a warning on wizard_site_config.php: "You currently have version 5.4.38 of PHP installed. We recommend version 5.5 or later. UserFrosting can still be installed, but we highly recommend you upgrade soon." But I was still able to successfully install.

**Comment by alexweissman** [comment]
Yeah, I've heard this has been an issue for other people, but I still haven't been able to replicate it.  Are you having the same problem as in #213?

**Comment by thankably** [comment]
I sent a request to my host to turn error logging on, in the mean time I downloaded and installed usercake and got it working, I would really like to get frosting working instead... I'm going to try it on another account.

**Comment by alexweissman** [comment]
I do notice that `install_db.php` checks to see if the tables already exist by accessing the `information_schema` database.  Could this be a permissions issue on shared hosting environments?  

Can you try throwing some debug print statements into `install/install_db.php` to see how far it gets?  I thought I had suitable error-catching in place, but my guess is that it's getting stuck somewhere on that page.

**Comment by thankably** [comment]
Sorry just got home from the office, this can be closed. I have no idea what I did different, but was able to get it installed this afternoon.

**Comment by alexweissman** [comment]
Glad it's working now, but it would be great if we could figure out where this bug is coming from.  Did you use a different browser or something?
