### ISSUE TITLE
lost password request - deny - error

### ISSUE THREAD

**Issue by anthonybartoli** [alexweissman/UserFrosting#264]
Upon submitting a lost password request, clicking the link to deny the request ("If this was not you please click the link below to deny this request") leads to an error page (**api/user_reset_password.php**) that says:

*Error: data must be submitted via POST.*

And in the database, **lost_password_request** in **uf_users** table remains 1 after clicking the link. 

Can I write a fix for this?

**Comment by alexweissman** [comment]
Sure.  It looks like the `checkRequestMode` function was misused in `api/user_reset_password.php`.
