### ISSUE TITLE
security - directories / index views publicly viewable by default

### ISSUE THREAD

**Issue by anthonybartoli** [alexweissman/UserFrosting#265]
Directories without an index.php file are publicly viewable unless redirected (i.e. site_url/account). 

For example:

site_url/api
site_url/models

A simple security enhancement would be to disable these views.This can be accomplished most simply by including an .htaccess file in the root directory with:

    #disable directory listings
    Options All -Indexes

Or by including an empty index.php file in all directories like WordPress does. 

Perhaps the next version of UF should at least include empty index.php files in case a given web host does not allow Options directives in .htaccess (AllowOverride must be enabled in Apache's httpd.conf for the .htaccess solution to work).

**Comment by alexweissman** [comment]
Thanks, yes this is a problem in general with direct mapping of filesystems to URIs.  The next version of UF will use a proper URI routing system, with all requests being handled by the base `index.php`.  Then, access control will be implemented within each route.
