### ISSUE TITLE
redirect window.location.replace not working

### ISSUE THREAD

**Issue by abeck87** [alexweissman/UserFrosting#267]
Hello,

I thought i would test this app out. I really like it out of the box. I did notice the "window.location.replace" redirects are not working for some reason. For example when completing the installation or registering, i'm left at the same page. I am using php 5.5. Wasn't sure if that might the cause of it. 

Thanks - Andrew

**Comment by abeck87** [comment]
For some reason within register.php "if result json" is returning a 1 which is why the window.location.replace isn't getting called. 

if (resultJSON['errors'] && resultJSON['errors'] > 0){
                        console.log("error");
						// Reload captcha
						var img_src = APIPATH + 'generate_captcha.php?' + new Date().getTime();
                        $.ajax({  
                          type: "GET",  
                          url: img_src,  
                          dataType: "text"
                        }).done(function(result) { 
                            $('#captcha').attr('src', result);
                            form.find('input[name="captcha"]' ).val("");
                            alertWidget('display-alerts');
                            return;
                        });
                  } else {
                    window.location.replace('login.php');

**Comment by abeck87** [comment]
I figured out my issue. 

While converting everything over to postgres, I discovered the PDO lastInsertId function for postgress needs the sequence name actually set. 

$inserted_id = $db->lastInsertId('users_id_seq');

**Comment by alexweissman** [comment]
Cool, glad you got it figured out!  The next generation of UF will use an ORM, so all the nuances of different DB's will be handled automatically ;-)
