### ISSUE TITLE
Problem with my new fields on registration form

### ISSUE THREAD

**Issue by barlow1123** [alexweissman/UserFrosting#268]
I have followed the tutorial to add a new field on the registration form, I was able to get this all working ok.

I have now tried to change the field to a dropdown box, after looking through the "bootsole" documentation, I came up with the following code and inserted it under $fields in register.php:

```
'local_authority' => [
        	'type' => 'select',
			'label' => 'Local Authority',
			'icon' => 'fa fa-fw fa-edit',
		  	'items' => [
		  		'ta' => [
		  			'label' => 'Teaching Assistant'
		  			],
		  		'street_lord' => [
		  			'label' => 'Street Lord'
		  			],
				'adjunct' => [
					'label' => 'Adjunct Instructor'
					],
				'assistant' => [
					'label' => 'Assistant Professor'
					],
				'associate' => [
					'label' => 'Associate Professor'
					],
				'professor' => [
					'label' => 'Professor'
					],
				'emeritus' => [
					'label' => 'Professor Emeritus'
					]
			]
	]
```

This code displays the field on the page, as a drop down box, however, when clicking on the dropdown, there are no options.

This is also apparent when viewing the source as no <option> tags are being printed.

Is there something missing within my code?

Thanks in advance.

**Comment by alexweissman** [comment]
Sorry for the delay, I must have missed this one!  I think what you want is this:

```
'local_authority' => [
            'type' => 'select',
            'label' => 'Local Authority',
            'icon' => 'fa fa-fw fa-edit',
            'items' => [
                'ta' => 'Teaching Assistant',
                'street_lord' =>  'Street Lord',
                'adjunct' => 'Adjunct Instructor',
                'assistant' => 'Assistant Professor',
                'associate' => 'Associate Professor',
                'professor' => 'Professor',
                'emeritus' => 'Professor Emeritus'
            ]
    ]
```

Be advised that we're actually dropping Bootsole from the next version entirely.  It was a good idea, but unnecessarily complex for most peoples' needs.  Instead we'll be using [Twig](http://twig.sensiolabs.org/), which is easier and more flexible.
