### ISSUE TITLE
documentation / docs

### ISSUE THREAD

**Issue by anthonybartoli** [alexweissman/UserFrosting#272]
I was able to quickly generate very informative docs using [ApiGen](http://www.apigen.org) which I'll include in pull requests for branches master and slim should @alexweissman want to include the docs in the source code. 

Related to https://github.com/alexweissman/UserFrosting/issues/55 - perhaps the docs would be useful to others on userfrosting.com as well. ApiGen generates a directory of static HTML files API-style. So as UF becomes more object-oriented, the docs will be even more useful.   

Only quirk i've noticed is that for some reason the Function link at the top goes to valueExists (https://github.com/ApiGen/ApiGen/issues/575). A full list of all functions can still be browsed on the left though. 

Below is a zip of docs for the master branch for quick viewing:

https://www.dropbox.com/s/48nc300f3ndsyjw/userfrosting-docs-master-mar-22-2015.zip

**Comment by alexweissman** [comment]
Whoa, cool.  Is this compatible with the [phpDoc](http://phpdoc.org/) syntax for code documentation?

**Comment by anthonybartoli** [comment]
I think so, but I'm not completely sure. They appear to be competitors. I'll generate docs with phpDocumentor and see how they are different.

**Comment by alexweissman** [comment]
Great, just as long as the comment block format it uses is compatible with PHP's Reflection library, then either format would be fine.

**Comment by anthonybartoli** [comment]
I've got a busy week so phpDocumentor docs will get done later this week sometime. In the meantime, below is a zip of ApiGen-generated documentation for the slim branch:

https://www.dropbox.com/s/1d7p1ufwp2sxug2/uf-docs-branch-slim.zip?dl=0

**Comment by anthonybartoli** [comment]
phpDocumentor and ApiGen (and doxygen) both look for comments in phpDoc / DocBlock format. 

I found ApiGen's documentation to be the best out of the box, though I will continue to play around with phpDocumentor and doxygen. I think doxygen has the best potential but it is the most complex to use.  

Right now generated documentation is not as helpful as it could be, since the current UF is not object-oriented and mostly lacks comments in the DocBlock format. As the codebase becomes more object-oriented, docs will be more useful and clear. 

Are you going to include generated documentation either in the source code or on the website (or both)? I'd be happy to generate docs for each version. I am pretty shocked to see no formal documentation on the UserCake website.

**Comment by alexweissman** [comment]
I guess there are two types of documentation we need to think about: formal, class-by-class and method-by-method documentation, and practical "getting-started/how-to" documentation.  Ideally, I'd like to have both of these available on the website.

Yeah, it took me some time to figure out how UC worked because they didn't have any good documentation.  I'd like to spare people that same experience with UF.

**Comment by alexweissman** [comment]
I've finished documenting the code as PHPDoc blocks, so all that is left is to automatically generate web pages using phpDocumentor/ApiGen/doxygen.

**Comment by anthonybartoli** [comment]
Cool Alex. I'll generate the docs sometime this week with phpDocumentor, ApiGen, and doxygen and then you can decide what looks best.

**Comment by alexweissman** [comment]
wow, thanks!

**Comment by anthonybartoli** [comment]
I can't believe how much time has passed...

I worked a temporary gig for a few months and got caught up with other stuff. I haven't forgotten about this project! :)

**Comment by alexweissman** [comment]
Haha, no problem and glad you're still around.  Did you know that we have [chat](https://gitter.im/alexweissman/UserFrosting) now?

**Comment by anthonybartoli** [comment]
I generated two versions with ApiGen using its default and Twitter Bootstrap themes and one version using phpDocumentor:

phpDocumentor: 
https://www.dropbox.com/s/x4xzyjosnxqk660/documentation-phpdocumentor-default.zip

ApiGen - default:
https://www.dropbox.com/s/w63ivsi5vm3kjf6/documentation-apigen-default.zip?dl=0

ApiGen - Twitter Bootstrap theme:
https://www.dropbox.com/s/g07g5jic7g6m8nx/documentation-apigen-bootstrap.zip?dl=0

ApiGen printed some parse errors for both themes. A screenshot of the errors is included in both zips. 

I also verified that the ApiGen bug I pointed out in March has been fixed.

With phpDocumentor, I only generated one version with its default settings due to the amount of time it took to generate (over an hour) and a hunch that you will like ApiGen's docs a lot better. 

ApiGen's docs include a search functionality that I think makes it a winner over phpDocumentor. Users can also easily download ApiGen documentation for local browsing.  

I didn't bother with Doxygen due to time constraints. Considering its broad use and quantity of configuration options, I doubt it can tell us anything that ApiGen and phpDocumentor don't already. (though if you discover important code information that ApiGen or phpDocumentor fails to include, then Doxygen can probably do it and I'll be happy to make it happen.) 

Let me know what you think.

**Comment by anthonybartoli** [comment]
Docs excluding everything in /vendor: 

https://www.dropbox.com/s/h39mhi7bjs7xgsk/documentation-apigen-no-vendors.zip?dl=0

**Comment by anthonybartoli** [comment]
As discussed on Gitter, ApiGen did not include an interface method's DocBlock summary and description for an implemented method's documentation (you had to pull up the documentation for the interface method itself). 

In contrast, phpDoc's documentation for implemented methods includes any documentation from the interface but lacks search functionality. 

I went ahead and tested ApiGen with two simple files (one containing a class, the other containing 1 interface) to see if the generated documentation for a class's implemented interface method would include the DocBlock summary and description from the interface. 

It didn't. I tried with tags @see, @inheritDoc, and @inheritdoc and none of them alone or in combination made any difference. Having just 1 interface in the file also didn't make any difference. 

So it appears ApiGen is just not built to include documentation from inherited code. Even for the interface itself, you need to expand a method's section to see the DocBlock description. (see screenshots) 

phpDoc is working on a search feature but it is not trivial or coming anytime soon: 

https://github.com/phpDocumentor/phpDocumentor2/issues/636
https://github.com/phpDocumentor/phpDocumentor2/issues/1452

Let me know which set of docs (if any) you want to use. 
![code](https://cloud.githubusercontent.com/assets/726102/9925328/00b89b4e-5cd8-11e5-8c5e-ef8556d53b8b.png)
![interface](https://cloud.githubusercontent.com/assets/726102/9925327/00b63bce-5cd8-11e5-9b4b-c792d81dbf43.png)
![class](https://cloud.githubusercontent.com/assets/726102/9925329/00c3bede-5cd8-11e5-9137-78954d2a78b1.png)

**Comment by alexweissman** [comment]
Could you go ahead an open an issue on ApiGen's Github page to confirm this?  I'm looking at their website and community, and it seems pretty advanced.  I'm still wondering if there is just something we are doing wrong.

**Comment by alexweissman** [comment]
Looking at Doctrine, they appear to suffer from the same problem.  Here is their ApiGen documentation for their `Paginator` class: http://www.doctrine-project.org/api/orm/2.4/class-Doctrine.ORM.Tools.Pagination.Paginator.html#_count

And [here in their source code](http://www.doctrine-project.org/api/orm/2.4/source-class-Doctrine.ORM.Tools.Pagination.Paginator.html#115-118) they are using `inheritdoc`, which seems to do nothing in terms of copying over descriptions.  Then again, they're implementing a core PHP interface, so maybe that interface simply doesn't have descriptions.

It is hard to say.  We could consider also moving the descriptions from interfaces to the classes, if ApiGen's behavior is the "correct" behavior.

**Comment by anthonybartoli** [comment]
I have filed an issue here: 

https://github.com/ApiGen/ApiGen/issues/646

If Doctrine is having the same issue, I bet that's just the way ApiGen generates documentation. 

Having thought about it, I think it makes sense that ApiGen does not include an interface's documentation because interfaces by definition only define the method signatures, not their implementation. The implementation - and perhaps the purpose - of said method could vary across applications.

So wouldn't it generally make sense to include documentation before the signature of the implemented method instead of the interface signature itself?

**Comment by alexweissman** [comment]
> The implementation - and perhaps the purpose - of said method could vary across applications.

I'm not sure I agree with that.  The whole idea behind interfaces is that you can easily swap one object for another when there is a dependency.  So, if my class requires a `DatabaseConnection`, it should work whether I pass it a `MySqlDatabaseConnection` or a `PostgresDatabaseConnection` or a `CouchDBDatabaseConnection`.

That being said, it is conceivable that some methods in some implementation will do something different anyway.  But in that case, shouldn't that be the exception rather than the rule?  So, shouldn't the interface's documentation be the default, and then it can be overridden as needed for particular methods?

This question: http://stackoverflow.com/questions/759703/comment-the-interface-implementation-or-both is about C#, but I believe the principle is the same.

**Comment by alexweissman** [comment]
Also, thanks for looking into this :+1:

**Comment by anthonybartoli** [comment]
Thanks for the link!

I suppose we have a half-way solution: 

	/**
	 * {@inheritDoc}
	 */

Includes the DocBlock summary but not the description: 

![summary](https://cloud.githubusercontent.com/assets/726102/9962117/2d3acb0e-5df2-11e5-9fe6-c604b277549d.png)

So based on everything, perhaps "The theme for the root user is always 'root'.  The theme for guest users is 'default'.  Any other users will have their themes determined by their primary group." (as an example) should be moved to the implemented method's signature rather than be an interface description?

**Comment by anthonybartoli** [comment]
Having the general purpose in the interface summary and implementation details in the implemented method signature with `{@inheritDoc}` seems to give what you're looking for: 

![newcode](https://cloud.githubusercontent.com/assets/726102/9962371/71e17540-5df3-11e5-88a0-dac815d8a14b.png)

![newdoc](https://cloud.githubusercontent.com/assets/726102/9962377/76dd24ae-5df3-11e5-95ab-57db8756ee1e.png)

**Comment by alexweissman** [comment]
Cool!  I think this is an acceptable compromise ;-)

It shouldn't be too much work to move the "long descriptions" from the interface to the `MySql*` implementations.  I can do this with a hotfix.

On another note, how much work is it to generate the documentation from the code?  Is this something we can automate (i.e., whenever the repository is updated), or should we just run it through ApiGen "manually" every time there is a new release?

**Comment by alexweissman** [comment]
Ooh, I think I just answered my own question.  Check this out: https://github.com/ApiGen/ApiGen/wiki/Generate-API-to-Github-pages-via-Travis

**Comment by alexweissman** [comment]
Let's plan on releasing our first set of API pages to the website with version 0.3.1.

**Comment by cookieman768** [comment]
I cannot wait for the documentation because I'm planning on having people being able to register through Minecraft but I need to figure out how the user registration works without filling the form out. I hope that the new release is soon. :-)

**Comment by alexweissman** [comment]
Hey @anthonybartoli, I'm almost ready to release 0.3.1.  Do you want to generate the new docs?  The issue with interfaces shouldn't be a problem any more, since I've gotten rid of `DatabaseInterface` now that we're using Eloquent.

**Comment by alexweissman** [comment]
Ok, I did it!  http://www.userfrosting.com/api/

**Comment by anthonybartoli** [comment]
Good to know! Let me know if you run into further issues.

**Comment by alexweissman** [comment]
Thanks for all your help.

**Comment by alexweissman** [comment]
At last, we can close this issue :-D
