### ISSUE TITLE
When will 0.3.0 be released?

### ISSUE THREAD

**Issue by 9tontruck** [alexweissman/UserFrosting#274]
I was looking for a user management integrated PHP framework to start my project and UserFrosting is the one that I was looking for! Thank you for your work!

Because I just started using your framework, I have a few questions about it before I go deep into my work with your framework.

I am planning to upgrade once 0.3.0 is release no matter what it is. Will it be easy to upgrade from existing framework? Or should I wait for the new version?

**Comment by alexweissman** [comment]
I would recommend waiting, if you can.  It will be at least another month or two, and the structure will be pretty different from how it is now.

I will try to make a migration guide after the release, but I doubt the upgrade will be something we can automate.

**Comment by 9tontruck** [comment]
Thanks for the reply. I will probably start my project with the existing one today, but I will start writing framework-free coding part as much as possible. I will be waiting for your next version.

BTW, 0.3.0 sounds like it is still in beta release. What plan do you have in your mind for the future? Are you working by yourself?

**Comment by 9tontruck** [comment]
Just for a suggestion towards 0.3.0,
would you be able to add a media file management tool please? It may probably include this:
- The user uploads their photos and videos in media page
- The user can choose their media from the list of his/her media files
- Admin sets maximum total file size for each user
- Admin writes a javascript code like 
var data = {multi_selection:true, ....}
button.onclick(this, popupMediaSelection(data, callback));

You might know the one in Wordpress. It is really really useful for developers.

**Comment by masterofimps** [comment]
Any expected release date for 0.3.0 ?

**Comment by thomas1216** [comment]
ETA for 0.3.0?

**Comment by alexweissman** [comment]
Conservatively we're looking at the end of the summer, but hopefully sooner than that.  The semester is over, so I have a lot more free time now ;-)

**Comment by alexweissman** [comment]
If you want a preview, check out the dev branch https://github.com/alexweissman/UserFrosting/tree/dev-0.3.0

**Comment by r3wt** [comment]
closing as not a real issue

**Comment by alexweissman** [comment]
Be nice!
