### ISSUE TITLE
New field in users table not editable

### ISSUE THREAD

**Issue by compoundf** [alexweissman/UserFrosting#277]
First -- thanks for such an awesome user management system. I love it!

My question is this:

I've followed your tutorial on how to add a new user field and it works fine. The problem that I'm having is that I cannot edit the field in user management. I modified the widget-users.js just like the tutorial says in order to "override this default value when we open the form in editable mode"  - - however, the new field is still blocked when I try to edit it. The only way I can get it to become editable is to change 'display' : 'disabled' to 'display' : 'show'.   If I do that, it's editable even on the view page. 

Can you point me in the right direction?

**Comment by alexweissman** [comment]
Did you do a hard reload of your Javascript?  Your browser might be caching the old version of `widget-users.js`.  `Cmd+Shift+R` on a Mac, or `Shift+F5` on Windows.

**Comment by compoundf** [comment]
Well I feel silly. Yknow I tried refreshing many times and even closed out the window and re-opened it... but this time it worked. I guess all I had to do was post about it here and decided to work ><

Thank you!

**Comment by compoundf** [comment]
ack! just when I thought it was ok.. 

So the field is editable now, but when I click "update user" it doesn't do anything. It's as if the button is just for show. Could I have missed something somewhere?

**Comment by alexweissman** [comment]
No problem...I've banged my head against a wall for many hours dealing with cached JS.
