### ISSUE TITLE
Custom template

### ISSUE THREAD

**Issue by flamx** [alexweissman/UserFrosting#279]
I would like to use my own template (built on Bootstrap 3). How to do this?

**Comment by alexweissman** [comment]
Right now, the easiest way would be to replace the HTML in `models/page-templates`, `account`, and the main directory.  You can also replace the CSS in `css/sb-admin.css`, `css/sb-admin-master.css`, and `css/bootstrap-custom.css`.

The new version will have a proper templating and theming system based on Twig, so it will be much easier to use.

**Comment by flamx** [comment]
Thanks

**Comment by Boscorelli** [comment]
@alexweissman Can you now explain how to this on current version?

**Comment by Silic0nS0ldier** [comment]
@Boscorelli Your best bet is asking at the [chat](https://chat.userfrosting.com/channel/support).
