### ISSUE TITLE
Do User Accounts have to be rebuilt after creating a User-Defined field?

### ISSUE THREAD

**Issue by JohnWeez** [alexweissman/UserFrosting#283]
I would like to experiment duplicating the "city" example for adding a user-defined field. Will this affect existing user accounts that have been set up already?

**Comment by alexweissman** [comment]
You can set a default value for the new field in MySQL.  So, all existing user accounts will get the default value when you create the new column.  Other than that, no, it won't interfere with existing user accounts.
