### ISSUE TITLE
Having issues Editing a user

### ISSUE THREAD

**Issue by thomasburleigh** [alexweissman/UserFrosting#284]
I was attempting to edit a user and I received the following error, can you help me out?:

#5 /home/dashboard/public_html/forms/form_user.php(412): FormBuil in /home/dashboard/public_html/models/funcs.php on line 75, referer: http://dashboard.yt/account/users.php

#4 /home/dashboard/public_html/models/form_builder.php(66): FormBuilder->renderTextField('sign_up_stamp'), referer: http://dashboard.yt/account/users.php

#3 /home/dashboard/public_html/models/form_builder.php(89): FormBuilder->generateFieldData('sign_up_stamp'), referer: http://dashboard.yt/account/users.php

#2 /home/dashboard/public_html/models/form_builder.php(350): ReflectionFunction->invokeArgs(Array), referer: http://dashboard.yt/account/users.php

#0 /home/dashboard/public_html/models/funcs.php(75): DateTime->__construct(), referer: http://dashboard.yt/account/users.php

PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /home/dashboard/public_html/models/funcs.php:75, referer: http://dashboard.yt/account/users.php

![screenshot_141](https://cloud.githubusercontent.com/assets/11783962/6980862/c2c762d4-d9ce-11e4-9e84-d34cc3635833.png)

**Comment by alexweissman** [comment]
See issue #49.

**Comment by alexweissman** [comment]
Let me know if you're still having trouble!
