### ISSUE TITLE
Start installation - White page

### ISSUE THREAD

**Issue by horwath** [alexweissman/UserFrosting#285]
After setting up the database connection details and starting the Installation it wont load anything the page is white(blank).  No errors.
The folder is on a sub domain: http://1ezres.addicted.hu/1ezres/install/wizard_site_config.php

Thanks,

Balázs

**Comment by alexweissman** [comment]
When you say "no errors", do you mean shown on the page, or do you mean the php error log as well?

**Comment by horwath** [comment]
I mean on he page, sorry I'm not that good in php how can I genereateor see a php error log?

**Comment by alexweissman** [comment]
It really depends on your hosting platform.  A lot of hosts just have it create a file called `error_log` in the same directory as where the error occurred.  Otherwise, you will need to ask your hosting service.

**Comment by horwath** [comment]
From the php log file:
[Fri Apr 10 19:45:48 2015] [error] [client 66.249.67.122] PHP Parse error: syntax error, unexpected '[' in /home/fs_local/x003228/web/addicted.hu/1ezres/models/funcs.php on line 63
[Fri Apr 10 21:53:50 2015] [error] [client 79.114.30.145] PHP Parse error: syntax error, unexpected '[' in /home/fs_local/x003228/web/addicted.hu/1ezres/models/funcs.php on line 63, referer: http://1ezres.addicted.hu/install/

**Comment by lilfade** [comment]
Change the [ it references on line 63 in /models/funcs.php to array( and
also change the next ] to a )

**Comment by horwath** [comment]
Changed to  $formatted = ();, but the error is the same:
[Sat Apr 11 19:19:23 2015] [error] [client 213.222.190.114] PHP Parse error: syntax error, unexpected ')' in /home/fs_local/x003228/web/addicted.hu/1ezres/models/funcs.php on line 63

**Comment by lilfade** [comment]
Change it to $ formatted = array();

**Comment by horwath** [comment]
Thanks, now there is aversion problem, but I checked and I have MySQL client version: 5.5.34 the error:
I'm sorry, due to a security flaw in older versions of PHP, UserFrosting requires PHP 5.4 or later. For more

**Comment by horwath** [comment]
Sorry the question was stupid its PHP not Mysql....

**Comment by horwath** [comment]
Its version 3.3.2deb1. So it wont work with this or isthere a workaround? Many thanks!

**Comment by lilfade** [comment]
Php should not be 3.3.x it should be either 4.x or 5.x  you can add a file
to your Web root named info.php inside add this

<php
Phpinfo();
?>

Goto your browser and goto info.php and this will tell you your php version

**Comment by alexweissman** [comment]
I would also strongly recommend upgrading to PHP 5.4 or later - give your webhost a call, they'll usually do it for you!

**Comment by alexweissman** [comment]
Let us know if you're still having problems after upgrading PHP.
