### ISSUE TITLE
Nav not showing up

### ISSUE THREAD

**Issue by jwren5** [alexweissman/UserFrosting#286]
I am not sure what happened, but when I login to my site via a user, the top and side nav bars do not show up. all you see is the top left link, black, and the main body. (see attached image)

from the admin perspective, it looks fine.

I looked back through my code and there doesn't seem to be anything weird going on.. is this a authorization issue?

thanks!
![screen shot 2015-04-07 at 10 44 20 am](https://cloud.githubusercontent.com/assets/11281779/7028437/16a74238-dd13-11e4-950e-fc7bd1d29a24.png)

**Comment by jwren5** [comment]
This may help narrow it down.

starting in line 405 of db_functions I have this:
 // Safe to interpolate directly because group_ids are trusted data
        $group_list = "(" . join(',', $group_ids) . ")";
        echo "about to create query";
        $query = "SELECT
            *
            FROM ".$db_table_prefix."nav AS n
            JOIN ".$db_table_prefix."nav_group_matches as m ON (n.id = m.menu_id)
            WHERE m.group_id IN $group_list ORDER BY n.position";
		echo "about to prepare query";
        $stmt = $db->prepare($query);
		echo "about to execute query";
        $stmt->execute();
		echo "about to parse query";
        while ($r = $stmt->fetch(PDO::FETCH_ASSOC)) { 
			echo "iteration";
            $id = $r['id'];
            $results[$id] = $r;
			//error_log("id: ".$id);
			//error_log("results: ".var_dump($results));
			echo "ID: ".$id;
			echo "<br>";
			var_dump($r);
			echo "<br>";
			echo "<br>";
			echo "<br>";
        }
		echo "finished";

what is echo-ed from the user side is: (it is all echoed from the admin side)
about to create queryabout to prepare queryabout to execute queryabout to parse query finished

so that narrows it down to line 418 not working (right?)
while ($r = $stmt->fetch(PDO::FETCH_ASSOC)) { 
			echo "iteration";
            $id = $r['id'];
            $results[$id] = $r;
			//error_log("id: ".$id);
			//error_log("results: ".var_dump($results));
			echo "ID: ".$id;
			echo "<br>";
			var_dump($r);
			echo "<br>";
			echo "<br>";
			echo "<br>";
        }

**Comment by alexweissman** [comment]
If you think it might be an authorization issue, you can turn on auth debugging.  In line 132 of `models/config.php`, set `LOG_AUTH_FAILURES` to true.  Then, any time a user is denied access to a resource it will be logged in the error log.

**Comment by jwren5** [comment]
it doesn’t seem to be throwing an error when i do that.
any other thoughts?

Jon

**Comment by alexweissman** [comment]
Hmm ok, so it's probably not an auth issue.  Did you change any code in that function?

**Comment by jwren5** [comment]
nope. the only thing i have done with the whole file is add fields for registration. nothing was touched within that specific function.

**Comment by alexweissman** [comment]
Did you create new group(s)?  You may need to manually add the nav items if you added the user to a new group, but not to any of the original default groups (User or Administrator).  See https://github.com/alexweissman/UserFrosting/wiki/Adding-a-navigation-menu-item.

**Comment by jwren5** [comment]
no they are in the default admin and user groups.

**Comment by jwren5** [comment]
I removed several test users and added a fresh one and that seemed to do the trick... not sure what that did! but it seems to be working now.

**Comment by alexweissman** [comment]
Yay!  Please reopen if you have any more trouble.
