### ISSUE TITLE
After installation - White page

### ISSUE THREAD

**Issue by Reksal** [alexweissman/UserFrosting#288]
No problems with installation, but when I try to use Login.php I get a white page. The error log gives the following:

[11-Apr-2015 20:25:41 Europe/Berlin] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /Users/bert/Websites/models/languages/nl.php:184) in /Users/bert/Websites/models/config.php on line 196
[11-Apr-2015 20:25:41 Europe/Berlin] PHP Warning:  Cannot modify header information - headers already sent by (output started at /Users/bert/Websites/models/languages/nl.php:184) in /Users/bert/Websites/account/index.php on line 48

I don't understand this, I don't use the nl.php. In the config.php the language setting is en.php (2x). Any idea what's wrong?

Thanks, Bert

**Comment by alexweissman** [comment]
I notice there is a blank line on `nl.php` at the very end, past the php closing tag.  Try deleting that - PHP may be interpreting that as "output".  If that works, I'll fix it in the repo.

**Comment by Reksal** [comment]
Spot on. Problem solved, but what I still don't understand is that I don't use the nl.php, why should this cause a problem. But, thanks for your quick response.

**Comment by alexweissman** [comment]
That is weird, indeed.  Maybe some service on your server is touching every file in the directory for some reason?  At any rate, glad we figured it out, I'll update the code.

**Comment by lilfade** [comment]
This is why they say to not use the closing tag haha

**Comment by alexweissman** [comment]
Yeah.  But for some reason, it just feels so...wrong.

**Comment by rttaylor** [comment]
I found the same problem on error_functions.php  ... blank line after the closing tag, which caused this problem to show up when a user login session had expired and they refreshed the current page they were on.

**Comment by alexweissman** [comment]
Hmm, it should only do that when AJAX mode is set to "false" when you call `apiReturnError`.  Where are you calling this function?

**Comment by rttaylor** [comment]
I cloned dashboard.php and created a new page in the same directory.  That function result is echoed after the HTML tag on dashboard.php.

Thanks,

Rob Taylor

(c) 919-349-7027

**Comment by alexweissman** [comment]
Sorry, I meant the `apiReturnError` function.  That shouldn't get called at all from `renderAccountPageHeader`.
