### ISSUE TITLE
User Management Table

### ISSUE THREAD

**Issue by barlow1123** [alexweissman/UserFrosting#289]
Hello,

Wondering if there is any way that the filter/search field for a single column could be changed to a dropdown.

I have a field in the user registration that is a dropdown and would like to be able to filter the users in the table using this dropdown.

Cheers

**Comment by alexweissman** [comment]
It looks as though the Tablesorter plugin [supports this](https://mottie.github.io/tablesorter/docs/example-widget-filter-custom.html), so I would check out their code and examples.  The current code for initializing the user Tablesorter is in `js/widget-users.js`.

You may have to update with the newest version of Tablesorter - I'm not sure which version their example requires.

**Comment by r3wt** [comment]
might be possible with x-editable

**Comment by alexweissman** [comment]
Let's just upgrade to the latest version of Tablesorter, then this will be easy for people to do.
