### ISSUE TITLE
User Permissions should be at group level also

### ISSUE THREAD

**Issue by sriharisahu** [alexweissman/UserFrosting#291]
Currently for every user, the admin has to explicitly provide permissions - once the user is created. This should be modified and permissions should be available at group level. Basically all group members should have same permissions and then if admin wants to provide or remove some permissions at the user level.

**Comment by alexweissman** [comment]
That feature already exists - have you checked out the Authorization panel?

**Comment by sriharisahu** [comment]
Thanks. I had thought that we can only change user permissions in the auth panel.
