### ISSUE TITLE
Send email 

### ISSUE THREAD

**Issue by sarah0730** [alexweissman/UserFrosting#292]
hi,alex:
    In the process of sending mail, need to wait for a very long time, to prompt the user to wait.
    how to add?

Thank you

**Comment by alexweissman** [comment]
You mean something like a "please wait" indicator?  You could do this using AJAX and some Javascript.

**Comment by sarah0730** [comment]
i  try

**Comment by chrison999** [comment]
Sarah, bootstrap has a nice progress bar feature here:  http://getbootstrap.com/components/#progress

All you have to do is hook it into your code to get the current progress.  (Sorry, but I don't know how to do that.)  :)

Hope that helps a tiny bit.

Chris

**Comment by sarah0730** [comment]
Chris，thankyou！i use  Javascript.to solved.

**Comment by alexweissman** [comment]
You can also use the `.button('loading')` component of Bootstrap to make a button temporarily say "Please wait..." or something along those lines: http://getbootstrap.com/javascript/#buttons

I actually just used this feature on my company's website: http://bloomingtontutors.com/quiz/finite-math/question/51
