### ISSUE TITLE
Display Names with non english characters

### ISSUE THREAD

**Issue by Bonsailinse** [alexweissman/UserFrosting#293]
So I tried to create a user (via the manual form at users.php) with a display name like "Thomas Müller" and the error I got is "Display name can only include alpha-numeric characters". 

I think you should be able to convert special characters to their HTML entities (in this case ```&uuml;```) or simply allow a set of special characters since the database collation is utf8.

**Comment by alexweissman** [comment]
Sure, the current validation rules are just defaults.  Feel free to customize them as you need.  

The rules you'd want to change are in the `createUser` function at https://github.com/alexweissman/UserFrosting/blob/master/models/secure_functions.php#L102.

**Comment by alexweissman** [comment]
Actually, I don't see any reason why we should disallow special characters for display names as default behavior.  

As long as they get escaped when being outputted (which Twig does by default), there shouldn't be an XSS risk.  Thanks for pointing this out to me!
