### ISSUE TITLE
detect when user signup is completed?

### ISSUE THREAD

**Issue by rob-lindman** [alexweissman/UserFrosting#295]
we have a number of different systems in our service, and selected UserFrosting to provide a single signup facility... as opposed to having a variety of signup forms. 

I have deployed UserFrosting, and I am trying to figure out if there is an easy way to hook when a user has completed signup, and then to trigger perhaps a curl request to post some details (username) to another web page on a different server, or run a query to update some tables in a database.

**Comment by alexweissman** [comment]
So, you'd want some kind of live feed to notify you as users sign up?

One thing you could do is modify the `createUser` function to add a row to some other table (say, `notifications`, for instance).  Then you could use a `cron` job or something to periodically ping that table.  You could keep an extra bit in each row of that table to keep track of which notifications have been delivered so far.

**Comment by rob-lindman** [comment]
What is desired is that when the user signs up for the service, and successfully authenticates with email verification, the user is signed up for our bug tracker, which is on a different server, and this could be triggered via a curl post to a script on that server.

**Comment by alexweissman** [comment]
Well if you just want to execute a `curl` command, you could use `exec`.  Just be **very careful** not to include any unsanitized user-supplied data when you use `exec`.

**Comment by rob-lindman** [comment]
I would use curl in the context of PHP and I just need to know what function gets fired when a user completes verification of their email.

**Comment by rob-lindman** [comment]
What file will I need to modify, basically.

**Comment by alexweissman** [comment]
You should create a new function (perhaps in a new file), and call it from [`createUser`](https://github.com/alexweissman/UserFrosting/blob/master/models/secure_functions.php#L102) in `models/secure_functions.php`.

**Comment by alexweissman** [comment]
We've sort of done this now in v0.3.1, with User events.

**Comment by alexweissman** [comment]
Ok, gonna close this now.
