### ISSUE TITLE
HybridAuth + UserFrosting?

### ISSUE THREAD

**Issue by mizterp** [alexweissman/UserFrosting#296]
I was thinking of using HybridAuth (https://github.com/hybridauth/hybridauth) to simplify the signup/login process and then use UserFrosting to manage access to specific pages.

In this particular case I want to use it for a small web-app where I'll grant beta-access to specific users only (i.e. not all the users who signup via HybridAuth will/should have instant access).

How would you recommend I do something like this... or should I rather focus exclusively on UserFrosting?

**Comment by Jusomeara** [comment]
Just an idea. As UserFrosting uses [Slim Auth]( https://github.com/jeremykendall/slim-auth) which uses Zend\Authentication, it might be worth looking at [zf-oauth2](https://github.com/zfcampus/zf-oauth2) or asking the Slim-auth project about it.

**Comment by alexweissman** [comment]
Actually, UserFrosting will be using Slim, but probably not SlimAuth.  The problem is that SlimAuth only provides access control via routes, and we need to provide far more fine-grained control that can also take context into account.  Basically, my plan is to more or less use the same access control system we have in place now (with a few improvements).

As far as **authentication** goes, that is a different matter.  Does HybridAuth also for in-house authentication, as well as through other identity providers?  If so, it might be worth using in the next version.

**Comment by mizterp** [comment]
@alexweissman HybridAuth's main focus is to provide user **sign-up/sign-in** and **authentication** using *"well known social networks"*, so they do not provide in-house authentication :(

Would also like to know you guys think regarding the use of [RBAC] (https://github.com/OWASP/rbac) for authorization.

**Comment by alexweissman** [comment]
Dang - well, maybe we can still use HybridAuth to handle other identity providers.

The problem with RBAC is that it will not be powerful enough.  From what I can tell, there is no way to define context/conditions for authorization.  For example, with RBAC you can set a permission like `delete_post`, but there is no way to say "`delete_post` if post belongs to a user in your own group", or something like that.  From what I can tell from their [documentation](http://phprbac.net/docs_tutorial.php), you'd have to make separate permissions to handle those cases (`delete_post_group_1`, `delete_post_group_2`, etc).

I'm working on a way to make our in-house authorization system support an even more flexible range of permission conditions; see https://gist.github.com/alexweissman/d6055008e61ed4c6b556.

**Comment by Jusomeara** [comment]
@alexweissman Hi Alex, I look in the [auth folder](https://github.com/alexweissman/UserFrosting/blob/slim/userfrosting/auth/auth.php) and assumed userfosting was utilising jeremykendall/slim-auth.

On another note has anyone used [ZF-FR](https://github.com/zf-fr/rbac) a Zend Framework 3 prototype of the ZF2 Zend\Permissions\Rbac component. It may be worth looking at as they state ‘Any parent role will inherit the permissions of their children’.

**Comment by alexweissman** [comment]
Oh!  Yes I was exploring it as an option, but I guess I didn't delete it when I decided not to use it.

Inheritance is a topic worth discussing.  Currently, we don't have any sort of framework for explicitly defining hierarchies of groups.  I brought it up in #65, but I didn't see much interest.

We can also talk about defining hierarchies of individual permissions.  Actually, this could be implemented with my conditional permission system.  The "condition" for a parent group's permission could be a check to see whether other group(s) have that same permission.  This might become computationally expensive, though.
