### ISSUE TITLE
User Password

### ISSUE THREAD

**Issue by Dippies** [alexweissman/UserFrosting#297]
Hi Guys

Alex thanks for a great system once again , been using it plenty in the last few months.
i Was looking around the issues and wiki and couldn't find anything.

Well atleast i saw that you were using password_hash , but where wondering if a user is logged if there is anyway to get his password without it being hashed , so in other word i would like to get the password once the user is logged in , in plain text 

I need the password in plain text or some time of hash so that i can pass that vairable to another system and compare the 2 password

the password in the system is crypt 

Kind Regards
Dries

**Comment by ebrightTP** [comment]
Here's the way to get around the hash: NEVER STORE THE PASSWORD IN PLAIN TEXT.

The technique I use is putting the external communications involving the password in the process_login.php, or a thread launched by that. That's the only time the server should ever "know" the password. You must NEVER store the password. 
On Fri, Apr 24, 2015 at 12:56 AM, Dippies  wrote: 

	Hi Guys 

	Alex thanks for a great system once again , been using it plenty in the last few months.
 i Was looking around the issues and wiki and couldn't find anything. 

	Well atleast i saw that you were using password_hash , but where wondering if a user is logged if there is anyway to get his password without it being hashed , so in other word i would like to get the password once the user is logged in , in plain text  

	I need the password in plain text or some time of hash so that i can pass that vairable to another system and compare the 2 password 

	the password in the system is crypt  

	Kind Regards
 Dries

**Comment by lilfade** [comment]
If you need to compare you can go into process_login.php and crypt the
password there and store it for future use, although I'd recommend naming
it abstractly so people with access to session won't know what it is maybe
something like crypt_hash.

**Comment by alexweissman** [comment]
@ebrightTP really is right, you should find another way to implement what you are trying to do.  

One thing you can do is to decouple the user authentication from UserFrosting and treat it as a separate, third service.  Then you can have both UserFrosting, and your other system, use the new service as a common authentication provider.
