### ISSUE TITLE
white page after install

### ISSUE THREAD

**Issue by hfzg** [alexweissman/UserFrosting#298]
After installation I'm getting white page, php error is Fatal error: Cannot redeclare class Valitron\DefaultValidator in /var/www/cms2/models/validation/Validator.php on line 46 ...

Can you help me fix it?
Thanks in advance

**Comment by alexweissman** [comment]
Did you modify the code in any way before installing?

**Comment by hfzg** [comment]
no i haven't, everything is as is, from zip file, i have also tried to download it twice and install it few times but still getting same error, i'm using kubuntu 14.04 with latest updates, also with apache,php and mysql

**Comment by alexweissman** [comment]
Yeah that's weird, the only place where `Validator.php` gets included is in [config.php](https://github.com/alexweissman/UserFrosting/blob/354abdac93973e5d1fc8f5828279843d71d3b7cd/models/config.php#L51).  

It could have something to do with Ubuntu; see this SO answer: http://stackoverflow.com/a/6566415/2970321
