### ISSUE TITLE
Change user group on registration

### ISSUE THREAD

**Issue by landwulf** [alexweissman/UserFrosting#299]
I have two types of user I want to be able to create accounts for, I decided to duplicate the create_user.php file and so far both work fine, apart from the fact that I cannot seem to figure out how to set a user to belong to one group or another on creation/registration. I can change the users group and dashboard individuality in the admin dashboard as expected but what would the code in my create.php file have to be? My goal is to have two registration pages that creates two types of user (not a problem), but they need to belong to different groups on registration so when they login they are taken to the correct dashboard as per their group.

Any help would be greatly appreciated, I am very new to PHP and any obvious solution I have tried has had no success.

**Comment by ebrightTP** [comment]
Have a hidden "source" or "origin" field in the registration form. Then, modify the function dbAddUserToDefaultGroups() function to take the source or origin field (defaults to ""). 

It's a good idea for security purposes to hardcode, or pull from a specific table, what accepted values translate into which user group ids. Simply re-run the $query_user command with the chosen user group id. 
On Wed, Apr 29, 2015 at 01:45 PM, landwulf  wrote: 

	I have two types of user I want to be able to create accounts for, I decided to duplicate the create_user.php file and so far both work fine, apart from the fact that I cannot seem to figure out how to set a user to belong to one group or another on creation/registration. I can change the users group and dashboard individuality in the admin dashboard as expected but what would the code in my create.php file have to be? My goal is to have two registration pages that creates two types of user (not a problem), but they need to belong to different groups on registration so when they login they are taken to the correct dashboard as per their group. 

	Any help would be greatly appreciated, I am very new to PHP and any obvious solution I have tried has had no success.
