### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by sp-99** [alexweissman/UserFrosting#300]
After I press start install it comes up with this error:

Parse error: syntax error, unexpected '[' in /BLAHBLAH/models/funcs.php on line 63

**Comment by lilfade** [comment]
I swear no one looks at the wiki or the closed tickets lol.

None the less, change the [and following] to this minus the quotes ...
"Array ()" ... you may have to do this in a couple places if you get this
error again.

**Comment by sp-99** [comment]
I did a bit more searching and found the problem, sorry :(

**Comment by alexweissman** [comment]
Haha, it's ok.  Maybe we can throw a custom error message when this happens, to remind people that they need PHP 5.4+
