### ISSUE TITLE
https://github.com/alexweissman/UserFrosting/wiki/Adding-a-navigation-menu-item

### ISSUE THREAD

**Issue by investordashboards** [alexweissman/UserFrosting#303]
Using the method here: https://github.com/alexweissman/UserFrosting/wiki/Adding-a-navigation-menu-item

I am able to get a menu item on the left and clickable/working... However, the issue is that it does not stay highlighted. I am using the default data and adding 1 column in the two tables:

13, left, {my page locaiton}, Start Page, 1, members, , 0
Then
auto_id, 13, 1 

Hover and click work fine, however after click it then goes back to dashboard as the "selected" (highlighted) item... Page is showing correctly through this all. It is purely what is being shown as selected on the menu. This only is affecting custom menu items - not the default ones. So I am pretty sure it is user error somewhere...

Any ideas?

**Comment by gamenew09** [comment]
When the menu gets rendered for the custom page make sure the paramater is the css class in the database.
````
<?php
 echo renderMenu("css-here");
?>
````

**Comment by investordashboards** [comment]
Wow, I was that tired :-)

Thanks!

**Comment by alexweissman** [comment]
:zzz:
