### ISSUE TITLE
how to add radio button field??

### ISSUE THREAD

**Issue by iamrohan14** [alexweissman/UserFrosting#304]
i know how add a new user text field .. but i want to add a gender field which require a radio button ..plzz help meby providing the instructions :)

**Comment by alexweissman** [comment]
Does it need to be an actual "radio" button, or can you use a [toggle](http://getbootstrap.com/javascript/#buttons-checkbox-radio)?  If so, you can add:

```
  "gender" => [
    "type" => "toggle",
    "display" => "show",
    "label" => "Gender",
    "choices" => [
        "Male" => "Male",
        "Female" => "Female"
    ]
```

to `$fields_default` in `forms/form_user.php`.

**Comment by iamrohan14** [comment]
toggle is good..bt do i have to do all the changes like user field?

**Comment by iamrohan14** [comment]
ok , i will try then will let you know

**Comment by iamrohan14** [comment]
thnxx alot its working :)

**Comment by iamrohan14** [comment]
can you give me the solution to chnge the languages of display-alerts ..i want alerts in english

**Comment by alexweissman** [comment]
Actually the default language is English - did you mean that you want to change it to something else?

**Comment by r3wt** [comment]
been open more than 20 days with no purpose. closing.
