### ISSUE TITLE
Login breaks if user visits site without www and the domain is set with www

### ISSUE THREAD

**Issue by saulide** [alexweissman/UserFrosting#306]
Im having a problem, that if the host provider has some internal redirect rules, the login doest work if in configuration the website is e.g. www.test.com and he visit the site with test.com ( or vice versa if in configuration test.com and he visits the site via www.test.com)

i have a workaround for the login site now:
$protocol = (@$_SERVER["HTTPS"] == "on") ? "https://" : "http://";

if (substr($_SERVER['HTTP_HOST'], 0, 4) !== 'www.') {
    header('Location: '.$protocol.'www.'.$_SERVER['HTTP_HOST'].'/'.$_SERVER['REQUEST_URI']);
    exit;
}

but it feels so dirty....

**Comment by alexweissman** [comment]
Do you need to have the www and non-www domains treated separately?  If I were you, I'd just [put a redirect in my .htaccess](https://github.com/phanan/htaccess#force-non-www-in-a-generic-way) and make one of the domains your canonical domain.  

This will also be better for SEO purposes, as Google won't treat your site as duplicate content.

**Comment by r3wt** [comment]
Hi, we are moving to close the issue. If it continues to be a problem, please provide more information and a set of steps to reproduce the problem. Thanks
