### ISSUE TITLE
Changing Password Kicks the User Out

### ISSUE THREAD

**Issue by ebrightTP** [alexweissman/UserFrosting#307]
Whenever I change the password, it requires a user to log in again.  

What should I be looking for to determine where this is occurring?

**Comment by alexweissman** [comment]
This is where the request gets processed:
https://github.com/alexweissman/UserFrosting/blob/master/api/update_user.php#L130

And this is the function that actually updates the password:
https://github.com/alexweissman/UserFrosting/blob/master/models/secure_functions.php#L331

**Comment by ebrightTP** [comment]
I'll look at that. Thank you.

Related question: Is it supposed to kick the user out when you update the password?
On Tue, May 5, 2015 at 01:04 PM, Alex Weissman  wrote: 

	This is where the request gets processed:
https://github.com/alexweissman/UserFrosting/blob/master/api/update_user.php#L130 (https://github.com/alexweissman/UserFrosting/blob/master/api/update_user.php#L130) 

	And this is the function that actually updates the password:
https://github.com/alexweissman/UserFrosting/blob/master/models/secure_functions.php#L331 (https://github.com/alexweissman/UserFrosting/blob/master/models/secure_functions.php#L331)

**Comment by alexweissman** [comment]
I don't think so.  Or at least, it doesn't do that for me.  Is this happening with users in the default groups, or some custom-made groups?

**Comment by r3wt** [comment]
closing this issue. if it continues to be a problem, we will resurrect an investigate the issue.
