### ISSUE TITLE
No Access After Re-Install

### ISSUE THREAD

**Issue by mailmann006** [alexweissman/UserFrosting#308]
The first time I installed, it worked fine. No problems. I deleted everything, created a brand new database, then installed fresh. Now every time I install, it goes through the whole process flawlessly, but after the final steps and after deleting the install folder, whenever I try to login it just refreshes the login page. Also, which is very strange, the first time I installed I remember some very nice looking buttons to choose options such as allow email/username login. I find it strange that these buttons are now simple radio buttons. Did something get updated today in the few hours between my initial install and the following install?

**Comment by alexweissman** [comment]
Nope, I haven't pushed anything new today.  If you're getting just standard radio buttons, then it sounds like an issue with CSS/JS.  If JS isn't working either, then that would explain why login doesn't work (login uses AJAX).  Can you check your browser console and see if it is getting any errors with loading the CSS and JS includes?

**Comment by mailmann006** [comment]
Strangest thing. I came home from work and installed it on an alternate system and had no issues for the second time. The initial install on the other system was golden, but I had filled it with dummy data to test. I was looking to do a clean install but have had various problems afterwards. I'm pretty excited to implement this, kudos.
Sent from my Kyocera Hydro

Alex Weissman <notifications@github.com> wrote:

Nope, I haven't pushed anything new today.  If you're getting just standard radio buttons, then it sounds like an issue with CSS/JS.  If JS isn't working either, then that would explain why login doesn't work (login uses AJAX).  Can you check your browser console and see if it is getting any errors with loading the CSS and JS includes?

---

**Comment by mailmann006** [comment]
Apologies for the cellular response. My problem is that I need to find out why I can't create this in an environment that it previously ran in. I have cleansed the environment after first use, as well as destroyed the initial databases. I'm hesitant to replicate the error here. Could you tell me how you would personally go about doing a fresh installation on a local server? I feel as though I am missing a minor detail.

**Comment by mailmann006** [comment]
I see no errors in the console. What appears to be happening is that when I try to log in for the first time after a fresh install, it redirects me to the login page again even though I have enetered the proper credentials. What I do find very strange is that if I fill the username and password with junk data, the button does not post. It will just hang on the login page.

**Comment by mailmann006** [comment]
I have installed on a live server with no issues. Oddly, I am still unable to re-install on the first machine.

**Comment by mailmann006** [comment]
I have installed on a live server with no issues. Oddly, I am still unable to re-install on the first machine.
