### ISSUE TITLE
Nav bar replace

### ISSUE THREAD

**Issue by thomas1216** [alexweissman/UserFrosting#310]
Hello

I already got an admin php template with header and sidebar, how can merge yours sidebar and hearder with my own header and sidebar.?

Thanks for the info

**Comment by alexweissman** [comment]
Do you need to change the way the menu itself is built, or just the general visual layout?

If you just want to change the styling, the css files `sb-admin.css` and `sb-admin-master.css` are what you want to look at.  Unfortunately it may take some manually going through and figuring out which properties to merge into which classes.

If you need to changethe structure itself, the code that generates the nav menu is located here: https://github.com/alexweissman/UserFrosting/blob/5461b83dfae03268de5130e5ca4c208526cf58c4/models/template_functions.php#L14

0.3.0 will have theming, so this should be easier in the future ;-)

**Comment by thomas1216** [comment]
My template has the Same Structure, Left Side and Top Side, my left side already got some menus items in the left, like example picture, i just want add your sidebar to mine under login
![image](https://cloud.githubusercontent.com/assets/11229573/7641328/064a76f6-fa57-11e4-8a42-e42cfecf0c68.png)

Thanks for you help

**Comment by alexweissman** [comment]
Hmm, in that case I would just modify the `fetchMenu` function and call it directly from inside your menu code.

**Comment by thomas1216** [comment]
this is the code from my sidebar, 

'
		<link rel="stylesheet" href="../assets/css/abc.css" class="abc-main-stylesheet" id="main-abc-style" />
        
		<link rel="stylesheet" href="../assets/css/bootstrap.css" />
		<link rel="stylesheet" href="../assets/css/font-awesome.css" />
        
        
		<link rel="stylesheet" href="../assets/css/jquery-ui.css" />
		<link rel="stylesheet" href="../assets/css/datepicker.css" />
		<link rel="stylesheet" href="../assets/css/ui.jqgrid.css" />

		
		<link rel="stylesheet" href="../assets/css/abc-fonts.css" />
        
        <body class="no-skin">
		
		<div id="navbar" class="navbar navbar-default">
			<script type="text/javascript">
				try{abc.settings.check('navbar' , 'fixed')}catch(e){}
			</script>

			<div class="navbar-container" id="navbar-container">
				
				<button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
					<span class="sr-only">Toggle sidebar</span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>
				</button>
		
		<div class="main-container" id="main-container">
			<script type="text/javascript">
				try{abc.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			
			<div id="sidebar" class="sidebar responsive">
				<script type="text/javascript">
					try{abc.settings.check('sidebar' , 'fixed')}catch(e){}
				</script>

				<div class="sidebar-shortcuts" id="sidebar-shortcuts">
					<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
						<button class="btn btn-success">
							<i class="abc-icon fa fa-tasks"></i>
						</button>

						<button class="btn btn-info">
							<i class="abc-icon fa fa-comments-o"></i>
						</button>

						
						<button class="btn btn-warning">
							<i class="abc-icon fa fa-users"></i>
						</button>

						<button class="btn btn-danger">
							<i class="abc-icon fa fa-cogs"></i>
						</button>

						
					</div>

					<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
						<span class="btn btn-success"></span>

						<span class="btn btn-info"></span>

						<span class="btn btn-warning"></span>

						<span class="btn btn-danger"></span>
					</div>
				</div>

                
              <ul class="nav nav-list">
					<li class="">
						<a href="index.php">
							<i class="menu-icon fa fa-tachometer"></i>
							<span class="menu-text"> Dashboard </span>
						</a>

						<b class="arrow"></b>
					</li>
                    
                    <li class="active">
                     <a href="tasks.php">
							<i class="menu-icon fa fa-tasks"></i>
							<span class="menu-text"> Tasks </span>
						</a>
                        
                        <b class="arrow"></b>
                        </li>
                        
                        

					<li class="">
						<a href="comments.php">
							<i class="menu-icon fa fa-comments-o"></i>
							<span class="menu-text">Comments</span>
                             </a>
							<b class="arrow"></b>
						</li>

						

							<li class="">
								<a href="dropzone.php">
									<i class="menu-icon fa fa-cloud-upload"></i>
									<span class="menu-text"> Dropzone File Upload </span>
                                    
								</a>

								<b class="arrow"></b>
							</li>

					<li class="">
						<a href="desktop.php">
							<i class="menu-icon fa fa-desktop"></i>
							<span class="menu-text"> Desktop </span>
						</a>

						<b class="arrow"></b>
					</li>

					<li class="">
						<a href="calendar.php">
							<i class="menu-icon fa fa-calendar"></i>

							<span class="menu-text">
								Calendar

								
								<span class="badge badge-transparent tooltip-error" title="2 Important Events">
									<i class="abc-icon fa fa-exclamation-triangle red bigger-130"></i>
								</span>

								
							</span>
						</a>

						<b class="arrow"></b>
					</li>

					<li class="">
						<a href="gallery.php">
							<i class="menu-icon fa fa-picture-o"></i>
							<span class="menu-text"> Gallery </span>
						</a>

						<b class="arrow"></b>
					</li>

					

							<li class="">
								<a href="timeline.php">
									<i class="menu-icon fa fa-pencil-square-o"></i>
									<span class="menu-text"> Timeline </span>
								</a>

								<b class="arrow"></b>
							</li>

						
                        <li class="">
								<a href="faq.php">
									<i class="menu-icon fa  fa-exclamation-circle"></i>
									<span class="menu-text"> FAQ </span>
								</a>

								<b class="arrow"></b>
							</li>					
					</li>
				</ul>

				
				<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
					<i class="abc-icon fa fa-angle-double-left" data-icon1="abc-icon fa fa-angle-double-left" data-icon2="abc-icon fa fa-angle-double-right"></i>
				</div>

				
				<script type="text/javascript">
					try{abc.settings.check('sidebar' , 'collapsed')}catch(e){}
				</script>
			</div>'



![sidebar1](https://cloud.githubusercontent.com/assets/11229573/7652573/ecbde6ca-fadb-11e4-8d1d-fd6d092959ce.PNG)

The attached Picture is the output of my Sidebar, can you assist me how add your sidebar to mine using the Layout.

Thanks again for your help.

**Comment by thomas1216** [comment]
@alexweissman 

I called from my menu Code, but overlay my Sidebar, 

I enter the field manually to show how i want meger your sidebar with mine, Should looks like the following picture after merging. i use Ace Admin Dashboard.

![image](https://cloud.githubusercontent.com/assets/11229573/7704916/3021881e-fe0f-11e4-9c7c-82e080d2901f.png)


Any Help would be appreciate.

**Comment by alexweissman** [comment]
honestly, doing it manually like this might be the best way for now.  I'm working on a way to make account pages more easily configurable.
