### ISSUE TITLE
configuration token

### ISSUE THREAD

**Issue by karsnoordhuis** [alexweissman/UserFrosting#313]
hello,
i am installing userfrosting but cannot continue because i do not have  configuration token, where can i get one?

**Comment by thomas1216** [comment]
You will  need to go to the Database you created for userFrosting and under Users table you will see the token.

**Comment by karsnoordhuis** [comment]
it isnt there. i didnt enter it in the installer mayby thats wy i cannot find it?

**Comment by alexweissman** [comment]
Nope, the installer generates one for you.  It is actually in the `configuration` table, not the `users` table.

**Comment by karsnoordhuis** [comment]
Thanks everyone it works now! 
I don't know if this is a bug or its my phone but in landscape mode the menu doesn't scale well

**Comment by alexweissman** [comment]
Cool!  Menu scaling might be a problem with the StartBootstrap template, maybe?  I'm updating to their newer template in the new version.
