### ISSUE TITLE
Contents

### ISSUE THREAD

**Issue by moket2** [alexweissman/UserFrosting#314]
Hi,
I discovered "UserFrosting" since 2 months and I find it very well , thank you for your help.
I need each user acces to specfic folder
like user1 can only see content of folder1...
If it's not possible maybe only each one can access to a specific page.
Thank you

**Comment by alexweissman** [comment]
How about a `.htaccess` file in each folder that forwards all requests to that particular folder's `index.php` file?  Then, you can check the user's permissions before serving them the requested page (perhaps using `include`).

**Comment by moket2** [comment]
Thank you for the idea!! i'm going to try and give you feedback

**Comment by alexweissman** [comment]
Let us know if you're still having any problems.
