### ISSUE TITLE
Installation Issues (UserFrosting)

### ISSUE THREAD

**Issue by poker94** [alexweissman/UserFrosting#315]
Hi!
Sorry , maybe you can help me:

I am trying to install userfrosting , but when I click on " Start Installation" in the address  /install , automatically switches to /install/wizard_site_config.php , and locked there ; without showing any additional information or steps.

Thanks a lot for your help!

Regards

**Comment by poker94** [comment]
Problem solved. But now im haveing this error:

"I'm sorry, due to a security flaw in older versions of PHP, UserFrosting requires PHP 5.4 or later. For more information, please see"


But I have reviewed and have the version: 5.4.33


Thanks again

**Comment by alexweissman** [comment]
Great, glad you got it sorted out and welcome to UserFrosting!
