### ISSUE TITLE
Configuration Token

### ISSUE THREAD

**Issue by poker94** [alexweissman/UserFrosting#316]
Hi, Again:

I wonder where I can find the "Configuration Token" that I requested to complete the installation .

I can not find it, and unfortunately did not know where to look for.

If you could help me, I will be grateful

Thanks a lot, 
Regards

**Comment by X-Anonymous-Y** [comment]
A configuration token will be placed in your database

**Comment by thomas1216** [comment]
the installer generates one for you. It is actually in the configuration table,

**Comment by poker94** [comment]
Hi,
Thank you very much for your quick answer.

Start again the search for this , and I had no success.

Unfortunately I have very little knowledge in this type of procedure , but as a project that started individually I have nobody to help me.

If you could give me an exact address, it could be very helpful .


Apologize again, 


Regards..

**Comment by X-Anonymous-Y** [comment]
Http://localhost/phpmyadmin

Mysql database "userfrosting"

Mysql table  - "uf_configuration"

Table id - "7" "root_account_config_token"

Sorry for my Bad english  ;)

**Comment by poker94** [comment]
Problem solved!


Thanks you very much!!

**Comment by alexweissman** [comment]
Glad you figured it out!  By the way, feel free to close any issues you open once they're resolved ;-)
