### ISSUE TITLE
dev-0.3.0 mistakes

### ISSUE THREAD

**Issue by X-Anonymous-Y** [alexweissman/UserFrosting#318]
Hi Alex, I like and enjoy working with UF.
I'm just not the best in programming.
I wanted to try the new structure "dev-0.3.0" but getting since the last update a few mistakes.
Can you help me?

I'm sorry for the bad english!

Log:
Notice: Undefined index: plugin in XXX\dev-0.3.0\userfrosting\models\mysql\MySqlSiteSettings.php on line 28

Fatal error: Uncaught exception 'Exception' with message 'The value 'default_locale' does not exist in the core userfrosting settings.' in XXX\dev-0.3.0\userfrosting\models\mysql\MySqlSiteSettings.php:71 Stack trace: #0 XXX\dev-0.3.0\userfrosting\config-userfrosting.php(109): UserFrosting\MySqlSiteSettings->__get('default_locale') #1 XXX\dev-0.3.0\public\index.php(2): require_once('XXX...') #2 {main} thrown in XXX\dev-0.3.0\userfrosting\models\mysql\MySqlSiteSettings.php on line 71

and if I change the line:
     \ Fortress \ Message Translator :: setTranslationTable ($ app-> config ("locales.path") "/" $ app-> site-> default_locale ".php"...);

to.
     \ Fortress \ Message Translator :: setTranslationTable ($ app-> config ("locales.path") "/en_US.php".);

Then comes a new error message:
Notice: Undefined index: plugin in XXX\dev-0.3.0\userfrosting\models\mysql\MySqlSiteSettings.php on line 28
Slim Application Error
The application could not run because of the following error:

Details

Type: Exception
Message: The value 'author' does not exist in the core userfrosting settings.
File: XXX\dev-0.3.0\userfrosting\models\mysql\MySqlSiteSettings.php
Line: 71
Trace

#0 XXX\dev-0.3.0\userfrosting\controllers\accountcontroller.php(35): UserFrosting\MySqlSiteSettings->__get('author')
#1 XXX\dev-0.3.0\public\index.php(53): UserFrosting\AccountController->pageLogin()
#2 [internal function]: {closure}('login')
#3 XXX\dev-0.3.0\userfrosting\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Closure), Array)
#4 XXX\dev-0.3.0\userfrosting\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#5 XXX\dev-0.3.0\userfrosting\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#6 XXX\dev-0.3.0\userfrosting\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 XXX\dev-0.3.0\userfrosting\auth\csrfguard.php(51): Slim\Middleware\MethodOverride->call()
#8 XXX\dev-0.3.0\userfrosting\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): Slim\Extras\Middleware\CsrfGuard->call()
#9 XXX\dev-0.3.0\userfrosting\vendor\slim\slim\Slim\Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#10 XXX\dev-0.3.0\public\index.php(182): Slim\Slim->run()
#11 {main}

PHP: 5.6.8
MySQL: 5.6.24

**Comment by alexweissman** [comment]
Hey, thanks for checking out the dev!  Are you trying to use it with an existing database from an older version of UF?  The table structure is slightly different; see https://github.com/alexweissman/UserFrosting/blob/dev-0.3.0/sql/sample-db.sql.

**Comment by X-Anonymous-Y** [comment]
No, I have used the new structure

**Comment by alexweissman** [comment]
Can you try dumping the contents of `$app->site` using `print_r` in `config-userfrosting.php`, just after it is initialized?

**Comment by alexweissman** [comment]
Ohhh, I see the problem.  That was before I added the `plugin` column to `uf_configuration`.  Hang on, I'll update the initialization SQL file.

**Comment by alexweissman** [comment]
Ok, try reinitializing your DB with the latest push.

**Comment by X-Anonymous-Y** [comment]
I will check it now

**Comment by X-Anonymous-Y** [comment]
ok at the moment all works

Thanks for the quick help :)

**Comment by X-Anonymous-Y** [comment]
okay or not xD

on:
forgot-password
and:
resend-activation

comes the error:

[25-May-2015 20:11:54 Europe/Berlin] PHP Fatal error:  Cannot use object of type UserFrosting\MySqlSiteSettings as array in XXX\dev-0.3.0\userfrosting\controllers\accountcontroller.php on line 84

[25-May-2015 20:11:54 Europe/Berlin] Error (1) in XXX\dev-0.3.0\userfrosting\controllers\accountcontroller.php on line 84: Cannot use object of type UserFrosting\MySqlSiteSettings as array

[25-May-2015 20:12:24 Europe/Berlin] PHP Fatal error:  Cannot use object of type UserFrosting\MySqlSiteSettings as array in XXX\dev-0.3.0\userfrosting\controllers\accountcontroller.php on line 101

[25-May-2015 20:12:24 Europe/Berlin] Error (1) in XXX\dev-0.3.0\userfrosting\controllers\accountcontroller.php on line 101: Cannot use object of type UserFrosting\MySqlSiteSettings as array


but I not need this at the moment :P

**Comment by alexweissman** [comment]
Yeah, I haven't implemented those features yet ;-)

**Comment by X-Anonymous-Y** [comment]
no problem, I do not need it at the moment. have only seen it

should I close here, or leave it open?

**Comment by alexweissman** [comment]
Close-tastic!
