### ISSUE TITLE
Try Call Current #Username# but doesn't Work.

### ISSUE THREAD

**Issue by thomas1216** [alexweissman/UserFrosting#319]
Hello

I tried to Call the Current Username and populate in my topnav  but dont work

![image](https://cloud.githubusercontent.com/assets/11229573/7799814/3438059e-02d9-11e5-9ae9-2260ca104661.png)

Someone Call Help me!!

Thanks

**Comment by alexweissman** [comment]
Are you doing this separately from the `renderMenu` function?

**Comment by thomas1216** [comment]
yes

**Comment by alexweissman** [comment]
So yeah, that's the problem.  `renderMenu` is the function that replaces the hooks with the actual values.  Is there any way you can change your code to do it from the `renderMenu` function?

**Comment by alexweissman** [comment]
Also, if you can wait until 0.3.0, this will be a lot easier to do ;-)

**Comment by X-Anonymous-Y** [comment]
you can do it with:

<?php
require_once("models/config.php");
?>

<a href='' class='dropdown-toggle' data-toggle='dropdown'><?php echo "$loggedInUser->username";?><b class='caret'></b></a>

or not Alex?

**Comment by alexweissman** [comment]
Well the problem is that the topnav is dynamically constructed in `fetchMenu`.  So, he would need to put `$loggedInUser->username` into `fetchMenu`.

**Comment by r3wt** [comment]
Hi, please provide a set of steps to take in reproducing the problem. if we can reproduce it, we can probably fix it.

**Comment by r3wt** [comment]
All 0.2.x issues are being closed at this time so we can focus on pushing 0.3.0 out the door.
