### ISSUE TITLE
0.3.0 Ajax Best Practices -- Client Side

### ISSUE THREAD

**Issue by r3wt** [alexweissman/UserFrosting#321]
We need a smaller foot print for Javascript. Specifically, we need to make ajax forms uniform.

One way is the universal event specifies callback pattern, which i have more or less authored.

in this way, you specify your form like

`<form method="post" data-before="loginValidate" data-callback="loginProcess" action="ajax/blah">`

`loginValidate` is a function to validate the form. it should return false for success or an error string for error. it accepts no parameters, but the form is passed as `this` in the context of the function so that the function may process the form. 

`loginCallback` is the callback to perform post submit. the callback is called with the form as `this` in the context of the function, so you can do stuff like `this.trigger('reset')` from inside of your callback function.

the callback should accept 1 argument, `data`, which is the response from ajax request. with this pattern, it is responsible to make our front end development much more agile.

Here is an example of the pattern implemented with Noty for notifcations and Bootstrap

https://github.com/r3wt/StarterKit/blob/master/static/js/starterkit.js#L98

1 additional consideration is that forms should use `button type="submit"` rather than `input type="submit` so we can disable and show a loading spinner during submission.

I would encourage that this pattern be implemented in 0.3.0 immediately.

**Comment by alexweissman** [comment]
I agree, it is dumb to have to write a separate `submit` handler for each form.  For validation, we are already using the FormValidation plugin, which actually handles the field validation and displaying instant error messages.  See https://github.com/alexweissman/UserFrosting/blob/dev-0.3.0/userfrosting/templates/common/login.html#L38 for an example of how this is used.

But, it would be good if we can consolidate this somehow, like you said perhaps by creating a generic "form submission handler", and then attaching callbacks.  However, some forms need to behave slightly differently.  For example, I have configured the "site settings" page to auto-submit.  Furthermore, it converts unchecked checkboxes to submittable values.  See https://github.com/alexweissman/UserFrosting/blob/dev-0.3.0/userfrosting/templates/themes/default/site-settings.html#L117.  How do you propose we encapsulate this?

**Comment by r3wt** [comment]
@alexweissman based on what you've said i think i know how we can make this work.

we could add classes to our forms that signify how our code handles the form.

I'm thinking some names:

`.auto-submit` -  (site page for example, could use data attributes to control behavior)
`.ajaxify` - (my example)
`.ajaxify.contains-file` (file upload example)
`.default` - do nothing?

any ideas or comments welcome

**Comment by alexweissman** [comment]
Actually instead of a CSS class, let's use the `data-*` attributes:

`data-submit-type = onchange`
`data-submit-type = ajaxify`
`data-submit-type = ajaxify-with-file`
`data-submit-type = default`

Also, do you know about the jQuery Forms plugin: http://malsup.com/jquery/form/?  It might already handle a lot of what you're talking about.  Not sure if it plays nicely with FormValidation, though.  Can you investigate?
