### ISSUE TITLE
i got an issue when i edit a user the delete buttom is no align with edit and disabled buttoms

### ISSUE THREAD

**Issue by thomas1216** [alexweissman/UserFrosting#323]
Hello,

i got an issue when i edit a user the delete buttom is no align with edit and disabled buttoms, i tried to look for the code but i was unable to find out the issue.

Thanks

![image](https://cloud.githubusercontent.com/assets/11229573/7816849/c5a86e86-039e-11e5-9f25-4edac5e4e5ca.png)

account/user_details.php?id=2

**Comment by alexweissman** [comment]
Could you please post the **generated** source to a Gist?

**Comment by thomas1216** [comment]
Sure, 

https://gist.github.com/thomas1216/5e453522c986aafaa496

**Comment by alexweissman** [comment]
Can you get the generated source (the source your browser renders after executing all the Javascript)?  Firefox has an option for this in the "Web Developer Extension" plugin.

**Comment by thomas1216** [comment]
That Source code generated by firefox is located at 

https://gist.github.com/thomas1216/5e453522c986aafaa496

**Comment by alexweissman** [comment]
Actually, that's just the source code **loaded** by Firefox.  You need to use the "View Generated Source" function to see what the DOM looks like after Javascript is executed.  You'll notice that none of the actual HTML for the widget is present in the code you're showing me.

**Comment by thomas1216** [comment]
Done i updated the Gist 

https://gist.github.com/thomas1216/5e453522c986aafaa496

**Comment by alexweissman** [comment]
Thanks.  Is the `hideable` CSS class being applied?  (If you click "inspect element" on the `col-sm-` div that contains your Delete buton)

**Comment by thomas1216** [comment]
Can you tell me which File(s) Generated that Code and where is located? thanks

**Comment by alexweissman** [comment]
The form is generated in `forms/form_user.php`.

**Comment by thomas1216** [comment]
I'm not  using sb-admin-master.php, this css code is required?
'vert-pad {
  padding: 10px 0px;
}'

**Comment by alexweissman** [comment]
This:
```
.hideable {
    min-height: 0px;
}
```

**Comment by thomas1216** [comment]
That fix my issue, thanks so much

**Comment by alexweissman** [comment]
No problem!

**Comment by thomas1216** [comment]
One more thing, Can you tell me where is this code,  I use the Same File but i get different Results.

Output Mine
![image](https://cloud.githubusercontent.com/assets/11229573/7822658/100da2b8-03c5-11e5-8a7d-13d9f65f2b05.png)


Output yours
![image](https://cloud.githubusercontent.com/assets/11229573/7822636/f6cd3822-03c4-11e5-8a04-838bcb2af017.png)

Many thanks

**Comment by alexweissman** [comment]
That is also located in `form_user.php`: https://github.com/alexweissman/UserFrosting/blob/master/forms/form_user.php#L342.

**Comment by thomas1216** [comment]
Is css code bootstrapradio used for that?

**Comment by alexweissman** [comment]
yes, it powers the "primary group" buttons.

**Comment by thomas1216** [comment]
Nice Work like a Charm, Thanks Again.
