### ISSUE TITLE
Create user from an other php page

### ISSUE THREAD

**Issue by antoiner77** [alexweissman/UserFrosting#325]
Hi,
I have a little problem with my project, I have to be able to create a user without going through UF (registration of new members is disabled). I tried to make a POST Request on create_user.php (https://github.com/alexweissman/UserFrosting/issues/240)  but I get the error message. Is there a simple way to add a user in the database? (Especially for the password).

Thanks in advance

**Comment by alexweissman** [comment]
The password is hashed using the `password_hash($password, PASSWORD_BCRYPT)` function.  So if you hash the password using that function, everything else should be straightforward.
