### ISSUE TITLE
More About Menus

### ISSUE THREAD

**Issue by WilliamPearce** [alexweissman/UserFrosting#326]
I'm a very new user of **UserFrosting**, having installed it yesterday. I'm very impressed, but realise it's a work in progress. Best wishes for a long and productive life for UF.

My question concerns new pages and their inclusion in menus. I have followed the procedure in the wiki entitled **Adding a navigation menu item**, helped as well by some items here  under **Issues**. Like Issue #137, I am interested at this stage in a simple page level authorisation using the two standard primary groups. 

Everything works fine, except that I do not seem to be able to make the menu entry to just primary group 1 users' sidebar menus - I do not want the item to appear in the root user's account screens. The new page appears in the **Page-level authorization** table when viewing site **authorization.php**, and I have checked the boxes for **Private** and **User** and left unchecked the **Administrator** column, but the new page entry appears in both groups menus. In fact, experimenting with other entries in the **Page-level authorization** table, it does not seem to change anything when I check and uncheck a few items - even after logging out and in again. I found something that I think bears on my query in issue #127, but the code alexweissman refers to version 0.3.0. What version would it have been that I downloaded yesterday from the top menu at http://www.userfrosting.com?

Thanks for your comments.

**Comment by alexweissman** [comment]
The official "master" version is still 0.2.2, and that is the version that you'd be downloading through the website.  However, a lot of the issues you're seeing would be remedied in 0.3.0, which you can check out here: https://github.com/alexweissman/UserFrosting/tree/dev-0.3.0.

I think you'd appreciate the theming system, which lets you completely control the layout and styles for different primary groups.  For example, you can directly code into the menus to determine whether a menu item should always be displayed, or only displayed if a particular user has access: https://github.com/alexweissman/UserFrosting/blob/dev-0.3.0/userfrosting/templates/themes/default/menus/sidebar.html#L18.  Access control is now determined by "authorization hooks", which can be used to control access to entire pages, as well as more fine-grained aspects of your site's functionality.

**Comment by WilliamPearce** [comment]
Thanks Alex. Well, 0.3.0 looks really special. Time for bed now, but I know what I'll be doing tomorrow.

**Comment by alexweissman** [comment]
In v0.3.0, the easiest way to do this would be to override the menu item in the `root` theme.  You can first add the menu item to the `default` theme like so:

```
        {% if checkAccess('uri_zerg') %}
        <li>
            <a href="{{site.uri.public}}/zerg"><i class="sc sc-zerg fa fa-fw"></i> Zerg</a>
        </li>
        {% endif %}
```

And give access to primary group 1 only by setting the following entry in the `authorize_groups` table:

| id  | group_id | hook | conditions |
| ------------- | ------------- | ------------- | ------------- |
| x | 1 | uri_zerg | equals_num(self.primary_group_id,1) |

If you just want anyone who is a member of group 1 (not just primary) to be able to access the URL, change the condition to `always()`.

To make it disappear from the `root` theme, you could copy the `sidebar.html` template file from the `default` theme to the same subdirectory in the `root` theme.  Then just remove the link from the copy of the file that's in the `root` theme.  All themes are stored in `userfrosting/templates/themes`.

**Comment by alexweissman** [comment]
Let me know if you need any more help!
