### ISSUE TITLE
Barebones version of 0.3.0 is ready for preliminary testing

### ISSUE THREAD

**Issue by alexweissman** [alexweissman/UserFrosting#327]
The basic framework is ready to be tested, which includes an installer, login, registration, account activation, password recovery, user settings, user management, group management, and site settings.  The frontend management tool for authorization hooks is still not available.  I would appreciate some feedback on the basic structure of the code.

Available here: https://github.com/alexweissman/UserFrosting/tree/dev-0.3.0

**Comment by r3wt** [comment]
:+1: will pull in tonight and give it a test run!

**Comment by alexweissman** [comment]
Something that would be really useful is if someone could test the access control policies for various features.  In addition to testing through the actual web interface, it would be great if someone could try POSTing various bogus requests to the backend.

For example trying to update user details:
```
POST /users/u/1  // POST to this URI to update info for user 1
```
Or, trying to update site settings:
```
POST /config/settings
```
This should be tried while logged out, then while logged in as root user, admin user, regular user, etc.  Try posting bogus data (`DROP TABLE uf_user;=7`), invalid data (`primary_group_id='your mom'`), and unauthorized data (`groups[2]=1` when logged out/logged in as a non-admin user).
