### ISSUE TITLE
How do I show username and title please help me

### ISSUE THREAD

**Issue by cybersoldier** [alexweissman/UserFrosting#329]
I'm sorry I'm writing with google translate

No problem with the show user id and email

echo $loggedInUser->user_id;
echo $loggedInUser->email;

How do I show username and title ?

echo $loggedInUser->user_name;
echo $loggedInUser->title;

**Comment by alexweissman** [comment]
Try 
```
$user = fetchUser($loggedInUser->user_id);
echo $user['user_name'];
echo $user['title'];
```

**Comment by cybersoldier** [comment]
thank you very much
worked
