### ISSUE TITLE
Add a new user field thats not requiered.

### ISSUE THREAD

**Issue by klndsgn** [alexweissman/UserFrosting#331]
Thanks a lot for your API.

Well written and all but i can't figure how to add a new User-Field which is only additional for example the birthdate - should i just delete the validate in secure_functions.php?

Thanks for your help!

![bildschirmfoto 2015-05-28 um 14 03 58](https://cloud.githubusercontent.com/assets/4508056/7859576/a232ab9c-0542-11e5-92a3-91934c27221c.png)

**Comment by alexweissman** [comment]
Did you use `$validator->optionalPostVar` in `create_user.php`?

**Comment by alexweissman** [comment]
Let me know if you're still having trouble.
