### ISSUE TITLE
Filenames in the controller directory : Issue and Resolution

### ISSUE THREAD

**Issue by ssnukala** [alexweissman/UserFrosting#332]
Thanks for such a wonderful application. I downloaded the 3.0.3 version and installed it locally and also on one of my hosting servers. 

Issue: 
While the install on my MAC works ok, when I installed it on my godaddy shared hosting it would not work. I got the following error

[29-May-2015 17:14:41 America/New_York] PHP Fatal error: Class 'UserFrosting\PageSchema' not found in /<PATH HERE /userfrosting/controllers/BaseController.php on line 14 

This was because the filenames in the controller directory were in all lower case.

Resolution :
I just changed the file names from

mv pageschema.php PageSchema.php
And it worked
so just to be sure I also renamed the following files

mv usercontroller.php UserController.php
mv accountcontroller.php AccountController.php

This matches the file names you are using in the autoload_classmap.php.

Hope this helps

**Comment by alexweissman** [comment]
Thanks for catching this.  I actually changed the filenames on my local dev environment - for some reason, they're not getting synched on Github.  I will look into this.
