### ISSUE TITLE
Same error message throughout - not helpful

### ISSUE THREAD

**Issue by dv314** [alexweissman/UserFrosting#335]
Not sure where to make this request, but it would be helpful if the error messages were different based on where they occurred.

"Oops, looks like our server might have goofed..." is often called, esp in JavaScript, without anything going to server logs. Very difficult to debug what I did wrong with my install given that a code search gets multiple hits on that string.  

OK, back to debugging what I did wrong with the install. ;)

**Comment by alexweissman** [comment]
Yup, I agree.  We're fixing this in 0.3.0.  Feel free to give it a try, it's almost done!

**Comment by dv314** [comment]
Thx for the quick response, Alex.
