### ISSUE TITLE
Can install the UF 3? if yes, do you have instructions.

### ISSUE THREAD

**Issue by thomas1216** [alexweissman/UserFrosting#336]
I tried to install the new version to see how looks like, but i cant find install instructions.

Thanks

**Comment by alexweissman** [comment]
Just download the zip from the `dev-0.3.0` branch, unzip it into your web directory, and specify your database information in `userfrosting/config-userfrosting.php`.

Then, navigate to `/public`.  The installer should automatically come up.

**Comment by alexweissman** [comment]
Also, note that in production, you should not put the `userfrosting` directory in your `public_html` directory.  Instead, put it one level up ;-)

**Comment by tyl3r** [comment]
Hi, i'm also trying to test the dev branch, but i receive this error when i send the form for register the Master account:

```Oops, looks like our server might have goofed. If you're an admin, please check the PHP error logs.```

The log says:
```[02-Jun-2015 03:09:51 Europe/Paris] Error in C:\server\wamp\www\test\uf3\userfrosting\vendor\alexweissman\fortress\fortress\ServerSideValidator.php on line 14: Declaration of Fortress\ServerSideValidator::validate() should be compatible with Valitron\Validator::validate()```

**Comment by alexweissman** [comment]
Thanks I'll check this out.

**Comment by alexweissman** [comment]
Looks like you're getting a "strict" error: https://stackoverflow.com/questions/17234259/strict-standards-declaration-of-should-be-compatible-with

I have strict errors turned off, so I wasn't getting the error.  Let me see if I can either fix this, or suppress the error on this line.

**Comment by alexweissman** [comment]
Ok, that should fix it.

**Comment by tyl3r** [comment]
Sorry for the delay, very busy day..., i just want to say thanks for the fix, that was fast!

**Comment by alexweissman** [comment]
No problem.  I'm trying to get all the basic features working by the end of the week.  Documentation might take a bit longer, though.

**Comment by andrie81** [comment]
Hi.. trying to test UF 3

Got these Error
```PHP Fatal error:  Uncaught exception 'Exception' with message 'The value 'en_US' does not exist in the core userfrosting settings.' in /userfrosting/models/mysql/MySqlSiteSettings.php:126  ```

Stack trace:
```#0 /userfrosting/models/mysql/MySqlUser.php(32): UserFrosting\MySqlSiteSettings->__get('en_US')
#1 /userfrosting/config-userfrosting.php(119): UserFrosting\MySqlUser->__construct(Array, 0)
#2/public_html/index.php(2): require_once('/...')
#3 {main}
  thrown in /userfrosting/models/mysql/MySqlSiteSettings.php on line 126```

Can't seem to figure out where to change the 'default_locale' value.

**Comment by andrie81** [comment]
I try and re-upload all the files again and run it on 'dev'

Error thrown
```
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /public/install/master
on this server.</p>
<p>Additionally, a 500 Internal Server Error
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>```

**Comment by alexweissman** [comment]
Were you able to get through the install process, or does this just happen as soon as you try to navigate to `/public`?

**Comment by andrie81** [comment]
The error appear on the console when I tried to submit the form on Register Master Account. Can't get pass the page.

Current: 'dev'
/public_html/public - index.php location
/public_html/userfrosting

The 1st error appear when: 'production'
/public_html - index.php location
/userfrosting

**Comment by alexweissman** [comment]
Ok, sounds like you're putting all the files in the correct places.  Can you confirm (on your dev environment) that the `uf_configuration` table exists and is not empty?

**Comment by andrie81** [comment]
Yup.. its all there.
![capture](https://cloud.githubusercontent.com/assets/10769776/8042460/f4c969e6-0e51-11e5-9479-bb11426e31c3.JPG)

Here's the console log
![capture](https://cloud.githubusercontent.com/assets/10769776/8042638/1f6d16d8-0e53-11e5-8679-387ee2c61677.JPG)

**Comment by alexweissman** [comment]
I don't think this is a problem in the UF code - any 403 error would come with an error message that gets displayed on the page.  What kind of permissions do you have on the `public` folder?

**Comment by andrie81** [comment]
```public``` is currently 755
and I've double checked that all permissions is in order.

```.htaccess``` comes with the files i have downloaded from github.

I'm currently using a Malaysian provider exabytes.com.my. Well, I'm not surprised tho, as previous version does have problems with their server settings. I'm just trying to rule out whether I have taken a wrong step installing.

Thanks for your help!

**Comment by alexweissman** [comment]
no problem.  So, locally it all works OK?

**Comment by andrie81** [comment]
Sorry Alex, can't say it works OK locally.

I don't have a local server to test the installation. I've always use the host to test any project. Not a good way, but I'm comfortable with it as UltraEdit have FTP Manager. hahaha... 

drawback: Have to search the files locally to find any strings or code line.

**Comment by alexweissman** [comment]
Why not just set up XAMPP?  Takes about 5 minutes and it will make your dev cycle a lot tighter.

**Comment by andrie81** [comment]
Will do that. As I'm interested to try out UF3.

The previous versions do speed things a lot. The only drawback is its easy to miss any changes made to the code. Maybe UF3 will make a lot of things easier.

EG: User list
- users.php
- widget-user.js
- users_table.php
- secure_functions
- db_fuctions

All above need to be carefully noted for any changes made.

**Comment by alexweissman** [comment]
Should be a little bit easier now.  I'll try to update some of the tutorials on "adding a new user field", etc.

**Comment by andrie81** [comment]
Update:
It works fine using XAMPP, Time to contact my provider to solve the issues. Meanwhile, can I just dump the database and import it to the remote host?

Thanks Alex!

**Comment by alexweissman** [comment]
Yes, that should work fine.

**Comment by andrie81** [comment]
I found out that even tho i can login to the remote installation, i can't register any new user using the registration form. Maybe that's what makes the installation stop on Register Master Account.

i can add new user while log in as master. Strange.

**Comment by alexweissman** [comment]
Strange indeed.  Any messages in your php error log?

**Comment by andrie81** [comment]
Nope, nothing in the php error log.

Previous version doesn't play nice with mod security. How about UF3?

**Comment by alexweissman** [comment]
Interesting.  Did they find exactly where `mod_security` blocked the application?  I wonder if it is because we use `exec` in the authorization module.

**Comment by andrie81** [comment]
I've send them a request and will get you an update on that issue.
Previous version of UF also been blocked by mod_security when trying to register a new user but I never seen it as an issue from development side. (I'm a beginner)

**Comment by alexweissman** [comment]
Ah, good point.  Well let me know if they get back to you.  Whether this is a genuine security issue or (more likely) a false positive, I'd like to know.

**Comment by githubsrinath** [comment]
I just downloaded and successfully installed UserFrosting 3.0... Where is page authorization we had in 2.0?  Where is API Folder now?

**Comment by alexweissman** [comment]
There is no more `api` folder - everything is now broken up into methods in various controllers, in `userfrosting/controller`.  Check out http://www.userfrosting.com/navigating/ and then join us in chat.

**Comment by bootnumlock** [comment]
so when i click the register button on the master user creation screen i get a 403... what is the recommended course of action? thanks,

**Comment by alexweissman** [comment]
Hey @bootnumlock this issue is closed, and should not be used as a general "installation help" thread.  Please join us in [chat](https://gitter.im/userfrosting/UserFrosting) for help with installation.
