### ISSUE TITLE
How to setup new secure page

### ISSUE THREAD

**Issue by halbitron** [alexweissman/UserFrosting#338]
Hi, sorry if this is the wrong place for this question, but as a newbie to web development I was able to install v0.2.2 on WAMP server, now what.  How do I secure the web pages for my application?  Where (as in what folder) do I put my html & php pages that the user has to register and login to gain access to? And what code do I have to include in those pages so that they become part of the userFrosting secure environment? Again, so if this is the wrong place for this question, perhaps you can direct me to relevant place/doc...Your patience is greatly appreciate.

**Comment by alexweissman** [comment]
For v0.2.2, you just need to put your secured pages in the `account` directory.  You can do:
```
require_once("../models/config.php");
// Request method: GET
$ajax = checkRequestMode("get");
if (!securePage(__FILE__)){
    apiReturnError($ajax);
}
```
To control access to a page there.  See for example, [`dashboard.php`](https://github.com/alexweissman/UserFrosting/blob/master/account/dashboard.php).

However, I would highly recommend checking out the [dev](https://github.com/alexweissman/UserFrosting/tree/dev-0.3.0) version (0.3.0) if possible.  It's almost ready (like, a few days away), and it is a lot better organized and uses modern software design patterns.  0.2.2 will be deprecated fairly soon.

**Comment by halbitron** [comment]
Alex, I appreciate your generosity, patience and deligence--your are a stud! As soon as the kids go to bed, I will implement and update you tomorrow of a suceessful implementation...

**Comment by alexweissman** [comment]
No problem - v0.3.0 is now the master branch, so enjoy!
