### ISSUE TITLE
" /install/ was not found on this server"

### ISSUE THREAD

**Issue by sebwae** [alexweissman/UserFrosting#341]
Hey,

I'm having an issue with the new v0.3.0 when trying to install it.

I'm trying to install it on a simple vps with LAMP so I put the "userfrosting" folder in "/var/www" and the files from "public" into "/var/www/html" but when I'm going to http://mydomain.com I get redirected to "http://mydomain.com/install/?" and a 404 error " /install/ was not found on this server".

Did I missed something?

**Comment by alexweissman** [comment]
Did you copy the .htaccess file as well in the `'public` folder?

**Comment by sebwae** [comment]
Yes, I uploaded everything including the .htaccess file.

**Comment by alexweissman** [comment]
Any messages in the Apache log?

**Comment by sebwae** [comment]
No nothing.

**Comment by alexweissman** [comment]
Hmm, ok two things we can try.  First, try adding a `RewriteBase` directive to your `.htaccess`:
http://stackoverflow.com/questions/12343466/always-get-404-error-in-slim-framework-when-omitting-index-php-in-url

You can also try checking your `httpd.conf` file to make sure that htaccess files are actually supported: http://help.slimframework.com/discussions/problems/5326-slim-framework-404-page-not-found-problem

**Comment by sebwae** [comment]
Thanks forgot to change to "AllowOverride All" in my httpd.conf.

But I'm having another issue now, I receive a Internal Server Error when running the installer, here is the error log: 
Error in /var/www/userfrosting/models/mysql/MySqlSiteSettings.php on line 66: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cp.cp_configuration' doesn't exist

**Comment by alexweissman** [comment]
Is that before or after you create the master account?

**Comment by sebwae** [comment]
ok it's working now, apparently the issue was because I was using something else than "uf_" as my db prefix.

**Comment by alexweissman** [comment]
Hmm, it should still work though!  I'll check into it.

**Comment by sebwae** [comment]
Yes I keep getting errors:
Error in /var/www/userfrosting/models/mysql/MySqlSiteSettings.php on line 232: file(): Filename cannot be empty, referer:

**Comment by alexweissman** [comment]
Hmm, sounds like it can't find your error log file.  Could you check your `php.ini` and make sure you have error logging enabled?

**Comment by alexweissman** [comment]
Ok, that should fix the issue with table prefixes.  Let me see if I can do something more robust with the error logging issue.

**Comment by sebwae** [comment]
The log file was not defined in my php.ini it's working perfectly now.

Thanks a lot!

**Comment by alexweissman** [comment]
No problem!

**Comment by mckinnon** [comment]
I just spent some time chasing this down. (ref https://github.com/alexweissman/UserFrosting/issues/341)

When the the Installation guide says 
> Find the block that looks like:
 `<Directory /blah/blah/blah/>`
`    Options Indexes FollowSymLinks`
`    AllowOverride None`
`    Require all granted`
`</Directory>`
> Change AllowOverride None to AllowOverride All.

The "/blah/blah/blah/" matters and there may be several blocks which match (oops). It must be the public directory into which UserFrosting is being installed. 

i.e. for Ubuntu or RedHat, it will be 
`<Directory /var/www/>`
`        Options Indexes FollowSymLinks`
`        AllowOverride All`
`        Require all granted`
`</Directory>`
unless you used a non-default like /srv/www.

**Comment by alexweissman** [comment]
Ah, thanks.  Could you open a new issue for this?

**Comment by mckinnon** [comment]
If you like, sure.
