### ISSUE TITLE
Site Settings

### ISSUE THREAD

**Issue by exylian** [alexweissman/UserFrosting#342]
Hello,

getting issues after the installation.

On the Dashboard it shows "Oops, looks like our server might have goofed. If you're an admin, please check the PHP error logs."

My Error log show up

[Wed Jun 10 16:27:33.584029 2015] [:error] [pid 27035] [client 213.196.217.111:63346] Error in PATH/userfrosting/userfrosting/models/mysql/MySqlSiteSettings.php on line 232: file(): Filename cannot be empty, referer: http://dossier.felixhoevel.de/account/settings

**Comment by alexweissman** [comment]
Looks like you have the same problem as #341.  Please check that your error log is set up in `php.ini`.  I just pushed a patch that will detect this condition automatically now.

**Comment by exylian** [comment]
Ah yeah I see i've got an other path specified for my php error log :dancer: 
error_log = /var/log/php-errors.log resoved it!
