### ISSUE TITLE
web.config

### ISSUE THREAD

**Issue by Diddyy** [alexweissman/UserFrosting#343]
Heya, could you provide me with a working web.config for IIS?

**Comment by alexweissman** [comment]
Hey, I actually haven't worked with IIS before.  Is web.config the IIS counterpart of .htaccess?  If so, and you want to figure it out, I'd be grateful for your contribution!

**Comment by Diddyy** [comment]
Yes web.config is like Apaches .htaccess, I'll work it out tomorrow and share it with you! Great work so far glad to see it's ongoing!

**Comment by alexweissman** [comment]
Great, thanks so much!

**Comment by Diddyy** [comment]
I attempted to convert it to web.config but with no luck. The simple work around is to install http://www.helicontech.com/ape/ and choose a full server download when promoted on the installer Helicon Ape provides support for Apache .htaccess and .htpasswd configuration files in Microsoft IIS. so once this is installed it should all work which is does on my end.

**Comment by alexweissman** [comment]
Thanks, I'll add to the README.
