### ISSUE TITLE
locale / *_* - updated

### ISSUE THREAD

**Issue by X-Anonymous-Y** [alexweissman/UserFrosting#344]
Hey Alex.

I do not know if you're interested but I have updated the locale file

<a href="https://gist.github.com/9fadec09f40e59bbfceb.git" >Gist Link.</a>

**Comment by alexweissman** [comment]
Yesss, thank you so much!  I'll integrate it.

**Comment by X-Anonymous-Y** [comment]
Sers Alex.

I updated the file
Fixed small typo
now it's okay.

please Just look at the line 38 and 39.

it is still missing, which is recognized.
if email login is enabled "email, user name or password is invalid."
if email login is disabled "Username or password is invalid."

<a href="https://gist.github.com/9fadec09f40e59bbfceb.git" >Gist Link.</a>

just an idea

**Comment by X-Anonymous-Y** [comment]
have the code in all languages cleaned

all files in the gist link available

**Comment by alexweissman** [comment]
Sweet, thanks!

**Comment by alexweissman** [comment]
So did you just change `de_DE.php`, or the rest of the language files as well?

**Comment by X-Anonymous-Y** [comment]
I have really changed the German file. with the other files I have cleaned only the code

**Comment by alexweissman** [comment]
Alright, sounds good.  Could you submit this as a pull request, so I can auto-merge?

**Comment by X-Anonymous-Y** [comment]
done ;)
