### ISSUE TITLE
how do i make a redirect like {{user.user_name}}

### ISSUE THREAD

**Issue by newuser50938** [alexweissman/UserFrosting#347]
I know this gets the current logged in user, but how would i do something similiar for another table like achievements (custom made)? Could anyone explain this to me?

Also, how long is it expected before we have documentation? It would be SO nice if we had them.

**Comment by alexweissman** [comment]
Do you mean that you're trying to access the data from in a Twig template?  

Basically, there are two ways.  If you want to make your data object accessible to **all** templates, you can initialize it in `initialize.php` and add it as a Twig global variable.  See https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/initialize.php#L147.

If you just want to use it in a specific controller route, you can initialize it in that function, and pass it in as a part of the call to `render`.  See for example, the call made in `pageUsers`: https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/controllers/UserController.php#L46

Documentation is on it's way!  For real, unlike the zombies and dragons.  I'm working on a "Navigating UserFrosting" guide right now that basically gives you a tour of the code - hopefully I can get that up tonight or tomorrow.

**Comment by alexweissman** [comment]
This should get you started: http://www.userfrosting.com/navigating/

**Comment by newuser50938** [comment]
Thanks, wasn't aware of navigating.

**Comment by alexweissman** [comment]
That's because I just put it up ;-)
