### ISSUE TITLE
How to submit a form?

### ISSUE THREAD

**Issue by newuser50938** [alexweissman/UserFrosting#349]
Could somebody go more in depth on how to submit a form, step by step? (and the data entering the DB)?

**Comment by alexweissman** [comment]
Yup, I'm working on some walkthroughs and tutorials!

**Comment by alexono1** [comment]
Hello!

Do you have some explanation about it? I'm trying to use UserFrosting now, but no idea how to integrate form/db processing properly, please advise.
Do you have a working example script maybe?

**Comment by alexweissman** [comment]
@alexono1, I would start by looking at how some of the core UF features integrate form processing.  For example, here is the controller that UF uses to process the "create user" form: https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/controllers/UserController.php#L297

You can also join us in chat: https://gitter.im/alexweissman/UserFrosting, and I or some of the other guys who have been starting to work with UF could help you out.

**Comment by alexweissman** [comment]
I will try to put together a tutorial on this soon.
