### ISSUE TITLE
Request for example documentation

### ISSUE THREAD

**Issue by jyana** [alexweissman/UserFrosting#350]
Hi Alex -

I understand the basics of PHP and have done a small amount of reading on the concept of front controllers.  I believe this request will be useful for anybody relatively new to PHP and/or user management concepts.

I'm trying to understand the best method for implementing UserFrosting onto a simple 2-4 page website. Do you already have an intention of building a tutorial for something like this?  While I don't expect to burden you with spelling everything out for a newbie - I think it would be useful to explain in moderate depth best implementation practices for the utility.  It sounds like you've spent a considerable amount of timing learning about the proper security methods for user management, and I think we would all benefit from what you have to say regarding implementation.

Thanks!

**Comment by alexweissman** [comment]
Yup, we're working on it!  I've already started on a document that should help you with the basics of Composer, Slim, MVC: http://www.userfrosting.com/navigating/.

I'm working on some tutorials as well.  In the meantime, your best bet would be to join us in chat: https://gitter.im/alexweissman/UserFrosting.

**Comment by jyana** [comment]
Great stuff.  Thank you!

**Comment by alexweissman** [comment]
Also, we now have http://www.userfrosting.com/tutorials and http://www.userfrosting.com/components.
