### ISSUE TITLE
Anyone interested in volunteering to add DocBlock comments to the code?

### ISSUE THREAD

**Issue by alexweissman** [alexweissman/UserFrosting#352]
I need someone who can help add [PHP DocBlocks](http://phpdoc.org/docs/latest/guides/docblocks.html) to the classes and methods - particularly the model classes.  This will help developers to use autocomplete/intellisense when coding.

Anyone interested?

**Comment by checkso** [comment]
Would like to help, are there any prerequisites for doing the job?

**Comment by alexweissman** [comment]
Not really, it's pretty easy to learn how phpdoc works.  I'll add you to chat and we can discuss.

**Comment by alexweissman** [comment]
Ok, it's done!
