### ISSUE TITLE
UF doesn't load all JS and CSS files

### ISSUE THREAD

**Issue by SecurID** [alexweissman/UserFrosting#354]
Hi alex and the others,

I was very happy with using uf v0.2, and today I tried to install v0.3.
Unfortunately I get an unstyled page when I access the installer:

![screenshot 2015-06-25 19 52 16](https://cloud.githubusercontent.com/assets/7266850/8361536/cf3b5b88-1b73-11e5-89cb-396b612ad9e8.png)

Do you have any idea? Is this a problem with the .htaccess ? I asked my webhoster and he told me that mod_rewrite is installed per default.

Thanks for your help and Greetings
Yannick

**Comment by alexweissman** [comment]
Try navigating to just `/public/`.  You no longer need the `index.php` part.  I will look into making it redirect automatically.

**Comment by SecurID** [comment]
Then I get redirected that my domain is on sedo domain parking :( 

You can access it through:
http://yannick-kupferschmidt.com/userfrosting/public/

**Comment by alexweissman** [comment]
It is possible that `mod_rewrite` is installed but not enabled.  See #340.

**Comment by alexweissman** [comment]
You might just need to add a `VirtualHost` block to your `.htaccess`: http://docs.slimframework.com/routing/rewrite/

I will add this to the documentation.

**Comment by SecurID** [comment]
Doesn't work for me :( 
I get an internal server error. 

Pasted this into the .htaccess in /public/
<VirtualHost *:80>
    ServerAdmin info@yannick-kupferschmidt.com
    DocumentRoot "http://www.yannick-kupferschmidt.com/userfrosting/public/"
    ServerName yannick-kupferschmidt.com
    ServerAlias www.yannick-kupferschmidt.com

    #ErrorLog "logs/mysite.com-error.log"
    #CustomLog "logs/mysite.com-access.log" combined

    <Directory "http://www.yannick-kupferschmidt.com/userfrosting/public/">
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>

**Comment by SecurID** [comment]
I installed it on my localhost. Now it works fine. Maybe a problem with the hoster 1und1.de.

**Comment by alexweissman** [comment]
Alright, if you talk to you host and they can give you some more information about the problem, I can try to address it in the installation instructions.

**Comment by SecurID** [comment]
Did some more research on this issue.
I installed a fresh LAMP Stack on an Ubuntu 15.04 server and got the same issue as with my webhoster.

So I compared it with my local installation. Something is wrong with the request URL. Is this defined trough the .htaccess ?

![screenshot 2015-07-02 13 53 36](https://cloud.githubusercontent.com/assets/7266850/8476458/e1358a54-20c1-11e5-9dde-3282e5fe4530.png)

**Comment by SecurID** [comment]
http://docs.slimframework.com/routing/rewrite/
This worked now for the initial page but you can't access any other pages now.

http://unireg-server.cloudapp.net/dashboard/public/

**Comment by SecurID** [comment]
Solved the issue:

You may also, in addition to the above, if it does not work, have to change the override rule from the apache conf file (either apache2.conf, http.conf , or 000-default file).

Locate "Directory /var/www/"

Change the "Override None" to "Override All"

That worked for me. I think you should add this to the documentation :)

**Comment by alexweissman** [comment]
Awesome, thanks.  When you say "in addition to the above", what do you mean?  Setting a `<VirtualHost *:80>` block?

**Comment by SecurID** [comment]
No. Sorry forgot to include the source. I deleted the VirtualHost block and did this:

http://stackoverflow.com/a/21658877

**Comment by alexweissman** [comment]
Boom, done: http://www.userfrosting.com/installation/
Thanks again for looking into this for me!
