### ISSUE TITLE
Can't login to root user after creation

### ISSUE THREAD

**Issue by oleggen** [alexweissman/UserFrosting#355]
I have installed userfrosting under dev using the following structure:
example.com/dev/public/
example.com/dev/userfrosting/

After creating a new user, on the public folder url appears the "Register Master Account" form.
When going to url /public/config/settings? I get a 404 error.

Under uf_configuration the install_status says complete and the root_account_config_token is empty.

![screen shot 2015-06-26 at 11 13 44 am](https://cloud.githubusercontent.com/assets/7424209/8373432/4265d5da-1bf5-11e5-9882-e41033c50c1a.png)

**Comment by oleggen** [comment]
I started fooling around with it and after changing install_status to be empty I can login and everything seems to work ok for now.

**Comment by alexweissman** [comment]
Hmm, that's weird.  So you created the master account, then logged in and it forwarded you to `config/settings` and that gave you a 404 error?  Or did you create another account first?

**Comment by oleggen** [comment]
* It forwarded me to settings and it worked just fine.
* When I tried to go to the homepage there was the 'Register Master Account' form.
* When refresh the settings page it would  be 404.

I have had (and still have) only one account.

I played a little with htaccess and with the db but from what I see I couldn't do anything that could have solved it.

*Not sure if to open a new issue for this or that is even an issue.* Now that it works when going to homepage it redirects to dashboard. so I'm not sure what this stand for  but I commented for now on line 23:   $app->user->landing_page

**Comment by alexweissman** [comment]
`$app->user->landing_page` is the page that you get redirected to when you first log in, as determined by your primary group.  When `install_status` is set to `complete`, it should automatically cease trying to get you to register the master account.

**Comment by oleggen** [comment]
Is there a way to change the landing from the dashboard?
If not I'd love to contribute such option :)

**Comment by alexweissman** [comment]
Yup, go into Groups and edit the landing page for a group.

**Comment by alexweissman** [comment]
Ok, let us know if you are still having trouble!
