### ISSUE TITLE
Set twig environment to debug for using the twig dump function

### ISSUE THREAD

**Issue by oleggen** [alexweissman/UserFrosting#356]
I'm trying to echo an array in twig and I found this documentation on twig's site:
```
$twig = new Twig_Environment($loader, array(
    'debug' => true,
    // ...
));
$twig->addExtension(new Twig_Extension_Debug());
```
In `/userfrosting/vendor/slim/views/Twig.php` I have edited `$parserOptions = array('debug' => true);`
And I have added this line 
`$this->parserInstance->addExtension(new Twig_Extension_Debug());`
 after 
```
$this->parserInstance = new \Twig_Environment(
                $loader,
                $this->parserOptions
            );
```

and I get an error saying
```
Fatal error: Class 'Slim\Views\Twig_Extension_Debug' not found in /public_html/dev/userfrosting/vendor/slim/views/Twig.php on line 126

Warning: Cannot modify header information - headers already sent by (output started at /public_html/dev/userfrosting/vendor/slim/views/Twig.php:126) in /public_html/dev/userfrosting/initialize.php on line 142
```

**Comment by alexweissman** [comment]
You might just need to add `Twig_Extension` via Composer.  See this issue: https://github.com/slimphp/Slim-Views/issues/39.

**Comment by oleggen** [comment]
After adding the and installing and installing the extensions via composer I get this server error:

# Slim Application Error
The application could not run because of the following error:
#### Details
**Type:** Twig_Error_Syntax
**Message:** The function "dump" does not exist in "dashboard.html" at line 23
**File:** /Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/twig/twig/lib/Twig/ExpressionParser.php
**Line:** 572
#### Trace
0_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/twig/twig/lib/Twig/ExpressionParser.php(351): Twig_ExpressionParser->getFunctionNodeClass('dump', 23)
1_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/twig/twig/lib/Twig/ExpressionParser.php(144): Twig_ExpressionParser->getFunctionNode('dump', 23)
2_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/twig/twig/lib/Twig/ExpressionParser.php(84): Twig_ExpressionParser->parsePrimaryExpression()
3_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/twig/twig/lib/Twig/ExpressionParser.php(41): Twig_ExpressionParser->getPrimary()
4_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/twig/twig/lib/Twig/Parser.php(141): Twig_ExpressionParser->parseExpression()
5_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/twig/twig/lib/Twig/Parser.php(95): Twig_Parser->subparse(NULL, false)
6_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/twig/twig/lib/Twig/Environment.php(544): Twig_Parser->parse(Object(Twig_TokenStream))
7_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/twig/twig/lib/Twig/Environment.php(596): Twig_Environment->parse(Object(Twig_TokenStream))
8_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/twig/twig/lib/Twig/Environment.php(332): Twig_Environment->compileSource('{% set page_gro...', 'dashboard.html')
9_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/slim/views/Twig.php(87): Twig_Environment->loadTemplate('dashboard.html')
10_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/slim/slim/Slim/View.php(255): Slim\Views\Twig->render('dashboard.html', NULL)
11_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/slim/slim/Slim/View.php(243): Slim\View->fetch('dashboard.html', NULL)
12_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/slim/slim/Slim/Slim.php(757): Slim\View->display('dashboard.html')
13_/Applications/MAMP/htdocs/UserFrosting/public/index.php(41): Slim\Slim->render('dashboard.html', Array)
14_[internal function]: {closure}()
15_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
16_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
17_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
18_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
19_/Applications/MAMP/htdocs/UserFrosting/userfrosting/auth/CsrfGuard.php(51): Slim\Middleware\MethodOverride->call()
20_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Extras\Middleware\CsrfGuard->call()
21_/Applications/MAMP/htdocs/UserFrosting/userfrosting/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
22_/Applications/MAMP/htdocs/UserFrosting/public/index.php(365): Slim\Slim->run()
23_{main}

**Comment by oleggen** [comment]
It's as simple as hack, instead of editing the vendor file (which is a big no no) I have added these line to  `/userfrosting/initialize.php`:

```
$twig->addExtension(new Twig_Extension_Debug());
$twig-> enableDebug();
```

And it works like a charm.

**Comment by FreeWebber** [comment]
Same on Slim 3, solution:

in /bootstrap/app.php:

```
$container['view'] = function($container){
    $view = new \Slim\Views\Twig(__DIR__ . '/../resources/views', [
        'cache' => false,
        'debug' => true
    ]);

    $view->addExtension(new Twig_Extension_Debug());

    $view->addExtension(new \Slim\Views\TwigExtension(
        $container->router,
        $container->request->getUri()
    ));
    return $view;
};
```

**Comment by alexweissman** [comment]
@FreeWebber is the `Twig_Extension_Debug()` something that we should add to the `core` Sprinkle's `ServiceProvider` class?
