### ISSUE TITLE
How to add a secure  page?

### ISSUE THREAD

**Issue by bajida** [alexweissman/UserFrosting#357]
How to add a secure page to the userfrosting.
For example
public
index.php
secure.php
..
..
Userfrosting
....
.....
.....

Now how to make secure.php only available to the signin users and requires login to view secure.php.

**Comment by alexweissman** [comment]
@bajida you should put your code for that page into a **route** and secure it using `checkAccess`.  See the tutorial on adding a new page: http://www.userfrosting.com/tutorials/

**Comment by bajida** [comment]
Nope could in grab your word, it is very well build but little confusing....

consider the following  secure.php in the public folder as above now what exact routing should i do...i tried a lot and could in fix...if you give an example it will be really help full

<?php
require_once "../sour/initialize.php";
  
//then it is confusing for me totally
?>

<html>
<head></head>
<body>
....
...
..
</body>
</html>

**Comment by alexweissman** [comment]
Don't put any `.php` files other than `index.php` in your `public` folder - that is the key concept you need to understand first.  In this new version of UserFrosting, pages != `.php` files.  

Instead, you basically need to do three things:

1. Create a template `mypage.html` file in `userfrosting/templates/themes/default`.  Use `{{placeholders}}` for your dynamic variables.
2. Connect it to a route in `public/index.php`.  So for example, if you want your page to be at `http://example.com/mypage`, you need to make a route like this:

```
    $app->get('/mypage/?', function () use ($app) {    
        // Access-controlled page
        if (!$app->user->checkAccess('uri_mypage')){
            $app->notFound();
        }
        
        $app->render('mypage.html', [
            'page' => [
                'author' =>         $app->site->author,
                'title' =>          "My page",
                'description' =>    "This is my page.",
                'alerts' =>         $app->alerts->getAndClearMessages()
            ]
        ]);          
    });
```

You can put this anywhere in `index.php` before the final `$app->run()` command.

3. Create an authorization hook `uri_mypage` for this page in the `uf_authorize_groups` table.  The tutorial should help you out with this part.

**Comment by alexweissman** [comment]
Let us know if you're still having trouble, or join us in chat!
