### ISSUE TITLE
no access to SiteSettings (/config/settings)

### ISSUE THREAD

**Issue by bearkingde** [alexweissman/UserFrosting#361]
Hi there! I'm trying to use UserFrosting. Install seems to be okay. I have access to the dashboard. But I cannot access the site settings. I get a blank page. Any idea? Thanks for your help!

**Comment by alexweissman** [comment]
Are you getting any error messages in your PHP log or browser console?

**Comment by bearkingde** [comment]
i get the following in the Safari console:
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (settings, line 0)

not much info... is it?

there seems to be something wrong with the error log also since i'm getting "Oops, looks like our server might have goofed. If you're an admin, please check the PHP error logs." in the dashboard. i'm not sure if i have access to the php.ini have to figure that out...

**Comment by alexweissman** [comment]
The console message is telling you that the server (i.e., the PHP script) returned an error code.  So, the problem is definitely on the server.

`php.ini` is not the php error log.  Are you running locally, or on a hosting service?  Are you using something like XAMPP, WAMP, etc?

**Comment by bearkingde** [comment]
i only tried running user frosting on a hosting service...

**Comment by alexweissman** [comment]
Alright, the first thing I would do is either contact them or search their website to find out where your PHP error log is stored.  Often times it is just placed right into your `public_html` directory or the equivalent.  Once we get the error messages, that will help us figure out the problem.

I would also strongly advise you to set up a local development environment to build and test your code before making it live.  I recommend [XAMPP](https://www.apachefriends.org/index.html).

**Comment by bearkingde** [comment]
okay. what i get in the apache error log is:
Error in /path/on/the/server/userfrosting/models/mysql/MySqlSiteSettings.php on line 232: file(): Filename cannot be empty, referer http://xxx/dashboard

I am allowed to upload custom php.ini files. they have to be in every directory that contain executed code.
looking at the default php.ini I find the following:
error_reporting  =  E_ALL & ~E_NOTICE
display_errors = On
display_startup_errors = Off
log_errors = Off
track_errors = Off

I do not find information on the path to the php error log. I know where the the apache error logs are stored. would that be the location to point userfrosting to? if yes, how do i do that?
would i be enough to store a custom php.ini in /userfrosting/models/mysql ?

thanks for your help! i really appreciate it!!!

**Comment by alexweissman** [comment]
Well right off the bat, you need to have `log_errors` set to `On`.  There is usually also an `error_log` setting where you can set the log path.  But if you can set up the custom php.ini with `log_errors = On` (and also `display_errors = Off`, for security), a log might just turn up in either the `mysql` directory or the home directory.

**Comment by alexweissman** [comment]
Let us know if you find your error log.
