### ISSUE TITLE
Definition Root User

### ISSUE THREAD

**Issue by SecurID** [alexweissman/UserFrosting#362]
Where is it defined which one is the root user?
Can't find anything in the database or in the config files. Is this hardcoded anywhere?

Thanks for your help.

**Comment by X-Anonymous-Y** [comment]
UserFrosting/userfrosting/config-userfrosting.php

Line 48
And Line 74

**Comment by SecurID** [comment]
Oh. Thank you very much. 
Tought this is the Admin Group ID.

**Comment by X-Anonymous-Y** [comment]
:D no Problem... please close here!
