### ISSUE TITLE
PHP code in normal site?

### ISSUE THREAD

**Issue by Randolfo333** [alexweissman/UserFrosting#363]
Hello,

I am new to using UserFrosting but used UserCake before. As it was quite simple to add new PHP-code to an existing UserCake site, I do not understand how I can do that in UserFrozing. For Example, I just went into "userfrosting\templates\themes\default" and added "<?php echo "Test"; ?>" to its code, but whe running it on my local server, it prints "Test"; ?>". 
As I hope to be able to use UserFrosting, I would be glad if one of you knew the solution to that problem.

Thanks in advance and best regards.

**Comment by alexweissman** [comment]
Hi, and welcome to UserFrosting!

UF uses a special templating language called [Twig](http://twig.sensiolabs.org/) to render the viewable content.  So, you cannot insert PHP directly into a template file.  Instead, you can pass in variables through the call to `render`.

I would highly recommend that you start with the [tutorial for creating a new page](http://www.userfrosting.com/tutorials/), just to learn your way around.  Then, feel free to join us in [chat](https://gitter.im/alexweissman/UserFrosting) if you need more help.

**Comment by Randolfo333** [comment]
Thanks for your answer.
I was able to create a new html-file and insert it into the Userfrosting-Layout by reading your tutorial. It also seems like I know how to use the Twig-syntax for creating loops e.g.. Nevertheless, I was not able to find out how to use native php for printing content when the user enters this site. Shouldnt I be able to use php in the html-file cause I render it in the index.php? Im sorry for asking probably basic questions, but tutorials as this one for Twig: http://symfony.com/doc/current/cookbook/templating/PHP.html
didnt help me.
Thanks again and best regards.

**Comment by alexweissman** [comment]
Cool, sounds like you're going in the right direction.  Symfony framework supports both Twig and PHP in the templates, but we currently only support Twig.  Are you absolutely sure that you need raw PHP in the template?  You should try to do as much of the controller logic in the controller method, then pass it's output into the template.

**Comment by Randolfo333** [comment]
Unfortunately, as I already wrote all my functions and Mysql-connections with php and only wanted to switch to Userfrosting, I need to use raw PHP. Nevertheless, thank you very much for your support.

**Comment by alexweissman** [comment]
How big is your codebase?  It shouldn't be that hard to untangle your code and tame it to fit into MVC.  This will also have the added benefit of making your code more maintainable down the road.

**Comment by Randolfo333** [comment]
Ok, I will take a look at this, thank you :).

**Comment by alexweissman** [comment]
Let us know if you need any more help.
