### ISSUE TITLE
remove fevicon of usercake 

### ISSUE THREAD

**Issue by iamrohan14** [alexweissman/UserFrosting#366]
I want to remove favicon from the website i have already deleted it from the css favicon file .but usercake favicon is still displaying in the site

**Comment by ebrightTP** [comment]
The favicon is cached in your browser. If you clear the cache, it should disappear (or change, if you replaced it with something else).
On Fri, Jul 10, 2015 at 06:33 AM, iamrohan14  wrote: 

	I want to remove favicon from the website i have already deleted it from the css favicon file .but usercake favicon is still displaying in the site

**Comment by iamrohan14** [comment]
Tried cleaning cache still it is displaying

**Comment by iamrohan14** [comment]
Thannxx @ebrightTP its done
