### ISSUE TITLE
Extending userfrosting for my web game

### ISSUE THREAD

**Issue by Mindcrank** [alexweissman/UserFrosting#367]
Hello! I am a self taught programmer, and my knowledge is patchy, but I've decided to use userfrosting as a base and develop my project from there, both as an exercise in learning web development, and because I have long wanted to develop my own simulation web game, but had no confidence in my ability to write clean, secure code.

So I think user frosting is awesome, and I'm really happy to have a starting point. I've spent a couple weeks already looking through the code and doing my best to understand it; I want to follow the MVC concept and the pattern userfrosting has laid out for me. It's extremely helpful to my learning process to be extending something written by someone else, rather than doing it all from scratch myself. For that reason I'm really really enthusiastic about this project, thank you for making it a reality!

As with any student though, I'm still learning and I have a few questions about how best to extend the base code.

I'm adding tables to my database right now to store game objects (in this case, Cats), and my questions are mostly about how to add onto the existing framework to be able to access my database information with php in the most efficient way. If I'm correct in my understanding of MVC, this is mostly done through the abstract classes in the models folder? (a tutorial about how to extend the userfrosting database and existing classes would be extremely helpful to me, if it's not in the works already!)

I have played around with it a little, and though I don't fully understand how it works, I've managed to create a working MySqlCat.php file and MySqlCatLoader.php file. the table it references contains basic information about the cat, like it's id, the id of the user it is attached to, it's name, and sex. I am able to retrieve that data with my CatController and send it to various twig templates to be displayed on various pages.

My question is this: **Do I have to repeat this process for every single table I add to my database?**

I'm wanting to add mendelian genetic information about the cats to my databases, and after following guidelines about database normalization, I've come to realize it might requires QUITE a lot of tables. It seems like a daunting and arduous task to create a model.php for each and every single one of these tables, especially when the data is so similar. For example, I want to structure the tables like this for each gene:

Gene Name
Cat_id, Allele 1, Allele 2

and there might be eleven or so tables of a similar structure, representing the individual genes a cat can have. It seems excessive to create a MySql(GeneName).php and MySql(GeneName)Loader.php for each and every single gene.

I've considered this format:

Gene table
cat_id, gene name, allele 1, allele 2

but it seems like bad database design, because I can't properly enforce enumeration rules for each allele. (For example, the alleles of the base gene include black and cinnamon as options. but the alleles for eye color can not be black or cinnamon. but the table wouldn't be able to enforce that rule.) And I assume with enough Cats in the system, the table would eventually get bogged down, considering there would be 1 table but elven + rows for each cat. whereas the previous layout, there's elven+ tables, but each only contains 1 row per cat.

**Comment by alexweissman** [comment]
Hi @Mindcrank, thank you for the well thought-out question.  I can see that you've put a lot of time into understanding how the code works!

It sounds like you're on the right track.  As for your database structure, it's hard to say.  I'm not a database expert (I barely remember about normal forms, etc), so I can't tell you what the absolute correct design would be.  Have you tried asking on StackOverflow?

Personally, I would probably create a single Gene table (like in your second option), and enforce the data rules in the model code.  For example, I might check enumerations for the alleles in the setter methods for my `MySqlGene` class.

The downside of this approach, of course, is that your tables will be less portable, since they will be relying on the PHP code to enforce the enumerative rules.

**Comment by Mindcrank** [comment]
I have not yet tried asking on stackoverflow. But the more I think about it, the more reasons I have to have an individual table for each gene. It would make it a lot easier for me to add new genes in the future, if I wanted to, and I think it would also be easier if I were to want a search cats function that sorts them by specific traits.

So I would much rather go with: single table for each gene, 1 row per cat that has that gene.

Gene Name
cat id, allele 1, allele 2

But I still have the problem of not wanting to create an individual model for each and every single one of these gene tables, especially when the table structure is exactly the same, and I would be calling the same methods on every single one of them. The only differences would be the tables name, and the enumeration rules for two columns. Having a model for each of them seems counterproductive to DRY.

**So is it possible for me to create one single model that represents all of these tables?** how would i do that and still make it compatible with the rest of the code? Slim is kinda a new thing to me, and so is having classes that represent the database (I'm embarrassingly new to databases and web development haha).

**Comment by alexweissman** [comment]
What if you create a base class, `MySqlGene`, and then have very lightweight classes that extend it for each specific type of gene?

```
class MySqlGene extends MySqlDatabaseObject {

}

class MySqlGeneEyeColor extends MySqlGene {

}

class MySqlGeneSitsOnKeyboard extends MySqlGene {

}

...

```

Then you could put the methods that are common to all genes in the base class.

**Comment by Mindcrank** [comment]
Hmmm... That seems doable. I'm going to try it out! Would it be bad practise to put all those lightweight classes into one file or no?

**Comment by alexweissman** [comment]
Well, if you want to be fully compliant with [PSR-1](http://www.php-fig.org/psr/psr-1/), technically each class should go in a separate file.

But, we're not fully PSR-* compliant anyway, so I'd say it's up to you.

**Comment by alexweissman** [comment]
Let us know if you need any more help!
