### ISSUE TITLE
Change default url from localhost to localhost:81

### ISSUE THREAD

**Issue by ksammuchiri** [alexweissman/UserFrosting#368]
Hi my xampp software uses port 81 where can i change it since each time i load the http://localhost:81/frost/public/install/master I cant register the new Master Account

**Comment by alexweissman** [comment]
We are working on this, but for now you can change it manually in here: https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/models/mysql/MySqlSiteSettings.php#L130

**Comment by ksammuchiri** [comment]
Thanks, but where exactly do I change in that line?

**Comment by alexweissman** [comment]
Just add `81` right after the colon.  This is the line that builds all of the URLs.

**Comment by ksammuchiri** [comment]
http://localhost:81/frost/public/81//localhost/frost/public/install/master creates that link

**Comment by ksammuchiri** [comment]
![untitled81](https://cloud.githubusercontent.com/assets/8858207/8640110/673918c4-28f5-11e5-90d1-02aec2d69fbc.png)

**Comment by ksammuchiri** [comment]
$environment['SERVER_NAME'] ...where can i change the server name I think that's where the error ls

**Comment by ksammuchiri** [comment]
this worked !
 $uri_public_root = $environment['slim.url_scheme'] . "://" . "localhost:81" . $environment['SCRIPT_NAME'];
anyway if you get another solution just tell me. I like your work

**Comment by alexweissman** [comment]
Oh, right, my bad, that was the wrong colon!  Try:
`$uri_public_root = $environment['slim.url_scheme'] . "://" . $environment['SERVER_NAME'] . ":81" . $environment['SCRIPT_NAME'];`

**Comment by alexweissman** [comment]
By the way, you can always view the environment variables when logged in by visiting `/sliminfo`.

**Comment by ksammuchiri** [comment]
this worked !
 $uri_public_root = $environment['slim.url_scheme'] . "://" . "localhost:81" . $environment['SCRIPT_NAME'];
anyway if you get another solution just tell me. I like your work

**Comment by ksammuchiri** [comment]
Thanks

**Comment by Acoon** [comment]
I'm using this instead, then it figures it out it self.
$uri_public_root = $environment['slim.url_scheme'] . "://" . $environment['SERVER_NAME'] .":".$_SERVER['SERVER_PORT']. $environment['SCRIPT_NAME'];
