### ISSUE TITLE
Errors surrounding loggedInUser

### ISSUE THREAD

**Issue by JohnWeez** [alexweissman/UserFrosting#370]
A bit of a novice, so please bear with me.
Having issues losing loggedInUser, along with variables associated with it (username, and some fields we added). We need to pass is these variables into outside url's so we can load specific user data.
We've tried different structure and syntax, but still can't shake these errors. We were able to recreate the errors when we logged into the same user account in different browsers.

Here are the 3 we keep getting:
PHP Notice:  Undefined variable: loggedInUser in mydirectory/etc/etc
PHP Notice:  Trying to get property of non-object in mydirectory/etc/etc
PHP Fatal error:  Cannot use object of type loggedInUser as array in mydirectory/etc/etc

**Comment by alexweissman** [comment]
@JohnWeez I'm not sure I understand - are you using the latest version (0.3.0)?

**Comment by JohnWeez** [comment]
I am using 2.2.

Sorry to clarify I am trying to use loggedInUser information, such as username, and pass it into a URL. I am not using the dashboard template, but created my own pages.

**Comment by alexweissman** [comment]
Ok.  I'm not really providing support for 0.2.2 anymore, but it looks like the problem is that `$loggedInUser` is simply not visible in that directory.  Have you checked your includes?

How far along are you in your project?  Would it be possible for you to switch to 0.3?

**Comment by JohnWeez** [comment]
I have 
require_once("../models/config.php")
and
<?php
	echo renderTemplate("head.html", array("#SITE_ROOT#" => SITE_ROOT, "#SITE_TITLE#" => SITE_TITLE, "#PAGE_TITLE#" => "Dashboard"));
  ?>
in my page. Am I missing something?
Well we have about 400 client users, so pretty far along. To get 3 I would have to start from scratch, correct?

**Comment by alexweissman** [comment]
You could migrate your database over without too much trouble, but the code you'd want to start from scratch and then gradually bring in some of your current codebase.

I think it would be worth it though, if you have the time.  The old version, frankly, has some terrible software design practices and is far behind in terms of modern PHP practices.  I will be migrating my own business software (which has quite a bit of extension) very soon.

**Comment by JohnWeez** [comment]
So there is no way to fix my issue or upgrade without essentially starting from scratch?

**Comment by JohnWeez** [comment]
The strangest part is that it works most of the time, just randomly it will not pick up loggedInUser. Like I said I can recreate it pretty consistently by either logging in as the same user on two different computers, or logging in windows, one being a normal chrome window and the other an incognito.

**Comment by alexweissman** [comment]
So this only happens when you're logged in to the same account from two different places?

**Comment by JohnWeez** [comment]
Not necessarily, just the only way I've been able to recreate it. It happens to my clients randomly. After logging in and out, sometimes a couple times, loggedInUser gets recognized.

**Comment by alexweissman** [comment]
This sounds more like an issue with `$_SESSION` than a problem with the code, then...

**Comment by alexweissman** [comment]
Let me know if you're still having problems!
