### ISSUE TITLE
Port issues

### ISSUE THREAD

**Issue by Acoon** [alexweissman/UserFrosting#372]
Hi,

I just pulled the latest coe from git and had issues installing.
Mainly it is related to the site uri you are using.

Since my MAMP dev is not running on port 80 but 8888. However, alot of the urls you generate, filters out the port numbers. So http://localhost:8888/userfrosting becomes http://localhost/userfrosting

This does not work :(

/Thomas

**Comment by alexweissman** [comment]
Please search existing issues (open and closed) before opening a new issue.  This has already been brought up in #368 and #369.

**Comment by Acoon** [comment]
I see. I altered the line to this to make it dynamic:
`$uri_public_root = $environment['slim.url_scheme'] . "://" . $environment['SERVER_NAME'] .":".$_SERVER['SERVER_PORT']. $environment['SCRIPT_NAME'];`

**Comment by alexweissman** [comment]
Ooh, I like that solution!  Thanks.

**Comment by Acoon** [comment]
Modified it a bit to ensure you dont have problems with protocols. Now it only use port numbers in case you use non standard port number (80/443)
```
$serverport = (($_SERVER['SERVER_PORT'] == 443) or ($_SERVER['SERVER_PORT'] == 80)) ? '' : ':'.$_SERVER['SERVER_PORT']; 
$uri_public_root = $environment['slim.url_scheme'] . "://" . $environment['SERVER_NAME'] .$serverport. $environment['SCRIPT_NAME'];
```

**Comment by alexweissman** [comment]
Nice, thanks.  I was reading the PHP documentation on this parameter: http://php.net/manual/en/reserved.variables.server.php

> Under the Apache 2, you must set UseCanonicalName = On, as well as UseCanonicalPhysicalPort = On in order to get the physical (real) port, otherwise, this value can be spoofed and it may or may not return the physical port value. It is not safe to rely on this value in security-dependent contexts. '

I'm not sure if this counts as a "security-dependent context", though.  What I might do is make these all configuration settings that are set to the `SERVER` variables by default, but then can be changed by the developer as needed.

**Comment by alexweissman** [comment]
Ok, I have added this to the latest push.
