### ISSUE TITLE
How to add custom fields to user and group settings?

### ISSUE THREAD

**Issue by spinturnix** [alexweissman/UserFrosting#374]
Hello,

First of all, thanks for this awesome framework. It's been a huge help to me in my current project. I am building a user dashboard to show specific website tracking and analytics. Each user or group will need the ability to add their individual api keys, account numbers, etc. for later recall in the template to load their user specific data. 

I'm having some trouble adding functional custom fields to user and group settings. I've added one test field to user-info-form.html, but when I submit, it throws an error "No data/bad data sent". I assume the value is not being passed along to the database, but I'm unsure how to troubleshoot that. 

Any help is greatly appreciated, thanks again.

**Comment by alexweissman** [comment]
Hi @spinturnix,

The first thing you'll need to do is modify your request schema to accept the new fields.  Please see, for example: https://github.com/alexweissman/UserFrosting/blob/dev/userfrosting/schema/forms/user-create.json.  This will tell UF which fields to expect from the submission of that form.

The next thing you'll need to do is extend your model.  If you just want to store these new fields in the same `user` or `group` table, you'll want to:
1. Add a new column to the database table (`user` or `group`)
2. Add the new field to the table whitelist: https://github.com/alexweissman/UserFrosting/blob/dev/userfrosting/initialize.php#L57

So, that should get you started.  If you're still having trouble after that, please join us in [chat](https://gitter.im/alexweissman/UserFrosting) and we'll try to help you out.

**Comment by spinturnix** [comment]
That worked perfectly, thanks!
