### ISSUE TITLE
Selection Dropdown UF

### ISSUE THREAD

**Issue by javaftper** [alexweissman/UserFrosting#375]
Hello,

version - 0.3.0

I've added a number of custom user fields which are working and propagating to the database however one of the fields (gender) needs to be a selection drop-down box.

I have established from the 'locale' drop-down on user settings the required changes to the json's and HTML however I have not been able to determine where to define my property values for gender.

The locales are populated by scanning the directory that contains the locale php files (\www\userfrosting\locale).
/**
     * Get an array of available locales for UserFrosting by scanning the path specified in $app >config('locales.path').
*

Where should I put something like this?-

'gender' => [
            'type' => 'select',
            'label' => 'Gender',
            'icon' => 'fa fa-fw fa-edit',
            'items' => [
                'M' => 'Male',
                'F' =>  'Female'
            ]
 ]

Are there any plans to add this type of functionality to be populated from the database? Obviously not really needed for this case but I was thinking about larger and common data sets like states in America, years etc.

thanks.

**Comment by alexweissman** [comment]
Hi @javaftper , the syntax you are using is no part of UserFrosting.  Instead, you should simply define the dropdown as a `select` element in the Twig template.  To populate the various options, you should use Twig's `{% for blah in foo %}` syntax.  So something like:

```
<select id="input_gender" class='form-control select2' name="gender">
    {% for option, label in genders %}
    <option value="{{option}}">{{label}}</option>
    {% endfor %}
</select>
```

And then define an array like:
```
$genders = [
  "m" => "Male",
  "f" => "Female",
  "o" => "Other"
];
```
Which you pass into Twig through the call to `render` in the controller code.

**Comment by javaftper** [comment]
Ah that's great.   Thanks.
