### ISSUE TITLE
Blank page - Can not begin instalation

### ISSUE THREAD

**Issue by pauljcurtis** [alexweissman/UserFrosting#376]
I have added the public and usefrosting folders to my local site. I have edited the config-userfrosting.php details. 

I have then gone to the http://localhost/{mysite}/public/ in my browser but it shows blank. Am I doing something wrong??

Any help is appreciated.

**Comment by alexweissman** [comment]
Have you checked the troubleshooting steps at the bottom of the installation guide?  http://www.userfrosting.com/installation/

This is a question that has been [asked](#351) [before](#373) - in the future, please check through closed issues before opening a new one.

**Comment by pauljcurtis** [comment]
Thank you... I didn't know there was a closed questions section. I've found
what I hope will solve the issue.

The installation guide could do with a terminology guide as some of the
terms are not clear unless the person does this kind of thing all of the
time.

**Comment by pauljcurtis** [comment]
My error.... It would help if I entered my localhost password correctly... Sorry for wasting time

**Comment by alexweissman** [comment]
No problem.  But, I am surprised that it showed you a blank page instead of an error message!
