### ISSUE TITLE
Help! UserFrosting Installation

### ISSUE THREAD

**Issue by bleeding-edge** [alexweissman/UserFrosting#378]
Good day!

I would like to ask for your help regarding installation of UserFrosting. Few months ago, I tried to use it successfully but now, I struggled with the new version. I'm using WampServer 2.5 with the latest PHP version. I put the UserFrosting inside www folder. I followed the guide to specify the database information. Whenever I access localhost/userfrosting/public , my page is just a white blank page. I hope you will help me. I'm new in web development and would like to improve my knowledge. Thanks!

**Comment by alexweissman** [comment]
Hi, thanks for trying the new version.  Have you looked at #351 and #373?  Also, have you tried the [troubleshooting instructions](http://www.userfrosting.com/installation/)?

Finally, please report any errors in your php error log.  If you don't know what this is, or where to find it, please Google it.  Thanks!

**Comment by bleeding-edge** [comment]
I haven't looked yet to #351 and #373 but I did the troubleshooting instruction. The error is C:/wamp/www/seos/public/.htaccess: Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration

I'm really excited to fix this and start

**Comment by alexweissman** [comment]
> Invalid command 'RewriteEngine'

Ok, it sounds like you don't have the Rewrite module installed.  Please check the documentation for WampServer to find out how to get this installed.

**Comment by bleeding-edge** [comment]
I uninstalled the WampServer then replaced it with XAMPP. I specify the database info then it works!! I don't know how it works. Thank you sir!

**Comment by alexweissman** [comment]
Cool!  So, XAMPP comes with the Rewrite module installed by default.  I guess WampServer does not.
