### ISSUE TITLE
Switching to server-side pagination

### ISSUE THREAD

**Issue by janezzz** [alexweissman/UserFrosting#380]
Is User Frosting able to support 1000 users in the database? How was the speed with large amount of users? Has it ever been tested with 600 or more users?
I am thinking of introducing this to a large project I am working on but unsure about its performance.  I have run user frosting locally using Easy PHP Dev Server v14.1 and found sometimes it is very slow.

The project I was thinking of introducing has over 500 concurrent users, over 1000 total users. If response time is not satisfactory, then it is not usable for this project.

**Comment by alexweissman** [comment]
@janezzz I haven't personally tried it with more than a few concurrent users, so this is a good question!  Where exactly are you finding it to be slow?

You might also look into [HHVM](http://hhvm.com/), which precompiles your PHP into bytecode and will give you an across-the-board speed improvement for PHP in general.

There are probably some other things that you could tweak to get it to run faster, for example identifying unnecessary database calls, [caching of Twig templates](http://twig.sensiolabs.org/doc/api.html#compilation-cache), and maybe even finding a way to cache authorization checks.

But, the first thing to do would be to identify the speed bottlenecks.

**Comment by janezzz** [comment]
I think the bottleneck is at opening the users page. You query the database
for all the users, and display them in the multi page list. This could
cause performance issues.
Jane

**Comment by alexweissman** [comment]
Oh, yes that is something I have been thinking about as well.  We need to implement server-side pagination (so, only loading the user data for the particular page we are on and then making additional requests as necessary).

If you want to take a stab at it, I'd be happy to review your code and we could get it integrated into UF.

**Comment by janezzz** [comment]
I am only a newbie at PHP, my jQuery and JavaScript are also not very
solid. I am a java, java EE developer. :-)

I may try when I get time.. but really busy recently.

Oh, yes that is something I have been thinking about as well. We need to
implement server-side pagination (so, only loading the user data for the
particular page we are on and then making additional requests as necessary).

If you want to take a stab at it, I'd be happy to review your code and we
could get it integrated into UF.

—
Reply to this email directly or view it on GitHub
<https://github.com/alexweissman/UserFrosting/issues/380#issuecomment-126145364>
.

**Comment by r3wt** [comment]
Example assumes usage of Redbean from within some type of class.

```php
	public function paginatedQuery($sql='SELECT * FROM users WHERE 1 ',$params=[],$page = 1, $per_page=12)
	{
		//we know that php is 0 based, but for presentation purposes pagination should be 1 based.
		//citing this knowledge, we always need to subtract `1` from $page;
		$page = (int) $page;
		if($page < 1){
			$page = 1;
		}
		$offset = abs($per_page * ($page - 1)); // page - 1 * per_page = offset
		$sql.=' LIMIT '.$offset.','.$per_page;
		if(empty($params)){
			$data = \R::getAll($sql);
		}else{
			$data = \R::getAll($sql,$params);
		}
		return $data;
	}

should provide you with a simplified example of how to implement pagination to a given table.

**Comment by alexweissman** [comment]
Thanks.  So, you are suggesting that it should be the client, rather than the server, that is charged with keeping track of the current page that the client is accessing?  I suppose that would be the RESTful thing to do...

**Comment by r3wt** [comment]
@alexweissman Well, i just built my first rest api and that's what i'm doing. it may not be considered correct, but it works ok for my requirements, and it might work for most situations in UserFrosting. 

I wrote a small `jQuery` plugin function called `inView()` that tests when an element is scrolled into view. coupled with some simple data tags for page and api url, it works pretty nice, and its reusable code.

**Comment by alexweissman** [comment]
Ok, it looks like Tablesorter supports server-side (ajax) pagination: https://mottie.github.io/tablesorter/docs/example-pager-ajax.html.  This is next on my radar.

**Comment by alexweissman** [comment]
Alright, I've implemented a rough cut of this in the `dev` branch.

**Comment by alexweissman** [comment]
Working well in 0.3.1.
