### ISSUE TITLE
Admin able to reset user password?

### ISSUE THREAD

**Issue by trinistag** [alexweissman/UserFrosting#381]
I'm not sure if this addressed. Can an admin account get the feature to reset a user account?

**Comment by alexweissman** [comment]
This shouldn't be too hard to do, since we already have a way for users to reset their own password via an email link.  So, all we would need is a button on the admin panel that initiates this process.

**Comment by tbrown0139** [comment]
This will be good

**Comment by alexweissman** [comment]
We should provide two options for the admin: one so they can directly set the user's password, another so that a password reset/recovery link is emailed to the user.

**Comment by alexweissman** [comment]
Alright, I took a first stab at implementing this:
![screen shot 2015-10-26 at 5 09 18 pm](https://cloud.githubusercontent.com/assets/5004534/10744252/f3213e86-7c0e-11e5-8447-482f8d041a62.png)
