### ISSUE TITLE
Processing forms

### ISSUE THREAD

**Issue by Mindcrank** [alexweissman/UserFrosting#382]
I've done my best to figure this out on my own, but it's a little hard with my limited knowledge of json 

Basically I'm creating some tools for myself to make future additions to my game a little easier.

In this case I've generated a form that I want to use to manually add object instances to my game's database (cats, which consist of some basic info fields, then then a list of genes). I've set up the view, and I've tried setting up it's connection to the controller, but it seems to be failing?  when I hit submit, it's supposed to take me to another page (/admin-tools/cat-submit), but instead of getting the generic HTML template ('admin-cat-submit') that I'm using to test the function, I get a blank white page.  but if I type in the url manually, it does load the template as expected. So it seems like I've done something wrong in the code between submitting the form, doing x(currently nothing) with the form data, and redirecting to another page. But I'm pretty inexperienced with forms, and I'm not sure where exactly it's going wrong/what I skipped. Any help would be appreciated!! I'm pretty sure that it has something to do with the form post data?

The form changes to include new genes when I add them to the database, and right now it looks like this:

![image](https://cloud.githubusercontent.com/assets/13084895/9024173/9b3948ce-3886-11e5-80e7-fd11167dbc55.png)

Here's my twig/HTML for the section of the form that deals with genes/alleles

``` html

<form name="cat-create" method="post" action="{{site.uri.public}}/admin-tools/cat-submit">

....

<h3>Genes</h3>

                                        <!-- FOR GENES -->

                                        {% for gene_name, alleles in all_alleles %}
                                        
                                        <div class="form-group">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    {{gene_name | capitalize}}
                                                </span>
                                                <select class="form-control" name={{gene_name ~ "_allele1"}}>
                                                    {% for allele in alleles %}
                                                    <option value="{{allele}}">{{allele}}</option>
                                                    {% endfor %}
                                                </select>
                                                
                                                <select class="form-control" name={{gene_name ~ "_allele2"}}>
                                                    {% for allele in alleles %}
                                                    <option value="{{allele}}">{{allele}}</option>
                                                    {% endfor %}
                                                </select>
                                                
                                            </div>
                                        </div>

                                        {% endfor %}

....

     <input class="btn btn-success" type="submit">
</form>

```

And this is in my index.php

``` php
// ADMIN TOOLS PAGES
    $app->get('/admin-tools/:action/?', function ($action) use ($app) {    
        $controller = new UF\AdminToolsController($app);
        
        switch($action) {
            case "cat":                 return $controller->pageCreateCat();
            case "cat-submit":          return $controller->pageCatSubmit();
            default:                    return $controller->page404(); 
        }
    });
```

And this is the function in my controller:

```    php
public function pageCatSubmit() {
        
        
        $data = [
            'page' => [
                'author' => $this->_app->site->author,
                'title' => "Cat has been created!",
                'description' => "cat created",
                'alerts' => $this->_app->alerts->getAndClearMessages(),
                'active_page' => ""
            ]
        ];

        $this->_app->render('common/admin-cat-submit.html', $data );
        
    }
```

**Comment by alexweissman** [comment]
So, one thing to note is that you are trying to `POST` to `/admin-tools/cat-submit`, but you don't have an `$app->post` route set up (at least not from the code you've shown me).  You only have `$app->get(...`. 

What is the exact sequence of requests that you want to set up?  Is it:

1. Client visits `admin-tools/cat`
2. Client fills in the form and `POST`s to `admin-tools/cat-submit`
3. The application creates a new cat, and then redirects to another page?

In that case, your requests will consist of a `GET`, then a `POST`, then another `GET`.

**Comment by Mindcrank** [comment]
Okay I've worked awhile on this so it makes a little more sense (i hope?). 

What I'd like to do is set this up in the best way to prevent duplicate form submissions, etc. but I'm not sure if thats:

1. Client visists admin-tools/cat
2. Post form to admin-tools/cat, application creates a new cat (and then add a message to the message stream saying it was successful)

or

1. Client visits admin-tools/cat
2. Client fills in the form and POSTs to admin-tools/cat-submit
3. The application creates a new cat, adds message to stream, and then redirects to another page (admin-tools/cat)

or is it Post, Redirect, Get? I've read a little about that pattern? I'm wanting to follow whichever method is best practise, but on top of that I'm getting myself confused over how to implement any of them in MVC format.

Right now in my mind, this is how it should be working with the way I've written the code?
Form posts to cat-submit
``` <form name="create-cat" method="post" action="{{site.uri.public}}/admin-tools/cat-submit"> ```

Then the index sends it to pageCatSubmit() (I have edited my routes since I first posted)

```
// ADMIN TOOLS PAGES
    //get the create a cat page
    $app->get('/admin-tools/:action/?', function ($action) use ($app) {    
        $controller = new UF\AdminToolsController($app);
        
        switch($action) {
            case "cat":                 return $controller->pageCreateCat();
            default:                    return $controller->page404(); 
        }
    });
    
    // post the form to cat-submit
    $app->post('/admin-tools/:action/?', function ($action) use ($app) {    
        $controller = new UF\AdminToolsController($app);
        
        switch($action) {
            case "cat-submit":          return $controller->pageCatSubmit();
            default:                    return $controller->page404(); 
        }
    });
```

then pageCatSubmit() generates a page. (I haven't yet programmed anything handle the post data, I thought I would put that in before rendering the page? Or will it not work this way?)

```
    public function pageCatSubmit() {
        
        $schema = new \Fortress\RequestSchema($this->_app->config('schema.path') . "/forms/cat-submit.json");
        $validators = new \Fortress\ClientSideValidator($schema, $this->_app->translator);

        
        $data = [
            'page' => [
                'author' => $this->_app->site->author,
                'title' => "Cat has been created!",
                'description' => "cat created",
                'alerts' => $this->_app->alerts->getAndClearMessages(),
                'active_page' => ""
            ],
            'validators' => $validators->formValidationRulesJson()
        ];

        $this->_app->render('common/admin-cat-submit.html', $data );
        
    }
```
I also added in Fortress stuff there, because my understanding is that it's used to sanitize data, and I noticed all the other forms on the site used it this way. But I confess, I'm not 100% certain how to use it, and I haven't put a ton of effort into the schema yet. the schema referenced there just looks like this for every single field in the form:

```
{
    "cat_name": {
        "validators": {}
    },
    "owner": {
        "validators": {}
    },
    "sex": {
        "validators": {}
    },
and so on.....

```

I was planning to finish it up when I got to the part of the code that actually handles the post data.

**Comment by alexweissman** [comment]
> 
What I'd like to do is set this up in the best way to prevent duplicate form submissions, etc. but I'm not sure if thats:

> 1. Client visists admin-tools/cat
2. Post form to admin-tools/cat, application creates a new cat (and then add a message to the message stream saying it was successful)

> or

> 1. Client visits admin-tools/cat
2. Client fills in the form and POSTs to admin-tools/cat-submit
3. The application creates a new cat, adds message to stream, and then redirects to another page (admin-tools/cat)

Ok, so this is going to depend on how you choose to submit your form.  If you use a traditional form submission (i.e., just creating a `submit` button and letting HTML handle the rest), then you will need to redirect to another page after creating the new cat and adding the message to the stream.

However, you could choose to use AJAX instead.  This is actually how most of the forms in UserFrosting already work.  In this case, Javascript will detect when someone submits the form, and will pass the data to the `POST` route without leaving your current page.  In this case, there is no need to redirect to another page (and actually, this wouldn't work because the response of that redirect would be sent back into the AJAX callback).  Instead, if necessary, you can use Javascript to reload the page after the request to the `POST` route is complete.

**Comment by Mindcrank** [comment]
Okay I would definitely like to go the Ajax route. I'm in the process of adding a the script into my template. I'm going by the example of the register forms script.  I'm kinda trying to logically figure this out, it's been a long time since I used ajax. at least the JQuery parts are familiar to me haha. I'm hoping I can work this out but I'll likely have more questions.

**Comment by Mindcrank** [comment]
Well that was a headache and a half figuring this out, and I just spent half an hour rooting out a stray ) in javascript -.- I'm both embarrassed and ashamed. But at least I'm learning haha.

Thanks for your direction; I know my questions were all over the place! But my application is now working in the way that I want it to ^^

The submit button is clicked, the page refreshes, and a message shows up in the stream! now I can work on the functions that actually process the the post data.

**Comment by alexweissman** [comment]
Yay, glad you got it figured out!  Feel free to join us in chat if you have any more problems.  It sounds like you're on the right track with the validation schema, too.  Check out https://github.com/alexweissman/wdvss for details on how this works.
