### ISSUE TITLE
mod_fcgid: stderr: PHP Fatal error

### ISSUE THREAD

**Issue by g-3x** [alexweissman/UserFrosting#384]
When trying to install UserFrosting on my server, i come around this little error which seams to break everything:
mod_fcgid: stderr: PHP Fatal error: Class 'Birke\\Rememberme\\Storage\\PDO' not found in /userfrosting/middleware/UserSession.php on line 23
Everything seams to be there where i thing it should be. Might be a problem with Plesk?

**Comment by JetGH** [comment]
I am getting this error as well.

**Comment by alexweissman** [comment]
Hmm, are you using the `master` or `dev` branch?

**Comment by alexweissman** [comment]
Oh, I see.  That's really weird.  Somehow, some of my changes in the `dev` branch made their way into the `master branch`.  Let me try to get this sorted out.

**Comment by alexweissman** [comment]
Ok, should be fixed now.  Sorry about that!

**Comment by alexweissman** [comment]
Alright, this has been fixed.
