### ISSUE TITLE
Add and access new table in the database

### ISSUE THREAD

**Issue by trinistag** [alexweissman/UserFrosting#386]
What steps do I need to take to add a new table to the database and be able to make queries on the twig page?

**Comment by alexweissman** [comment]
Well, you don't want to make queries in the template itself.  Rather, you should load any data you need from within the controller, and then pass that into the call to `render`.  See, for example, how the "users" page works: https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/controllers/UserController.php#L18

As far as creating the database table itself, you should do this via whatever interface you feel most comfortable with (phpMyAdmin, command line, etc).  You may then wish to extend the [model](https://github.com/alexweissman/UserFrosting/tree/master/userfrosting/models/mysql) (either `MySqlDatabaseObject` or `MySqlObjectLoader`) to make it easier to interact with the new table - depending on what the table is and what it is meant to do.

**Comment by trinistag** [comment]
If i wanted to add another controller where would I need to reference the controller in the application?

**Comment by alexweissman** [comment]
Install Composer and run `composer update`.  That will autoload any new files you create.

**Comment by alexweissman** [comment]
See the new tutorial lesson: http://localhost:4000/tutorials/lesson-3-data-model/
