### ISSUE TITLE
Error log inside admin dashboard

### ISSUE THREAD

**Issue by bleeding-edge** [alexweissman/UserFrosting#387]
I need help regarding on this. So far, I haven't encounter any problems but I'm curious about the error log. Too much info I don't know what to do with them. Thanks and more power!

![userfrosting error log](https://cloud.githubusercontent.com/assets/13551028/9153980/1c22ca0a-3eae-11e5-9036-8a6f36d45092.jpg)

**Comment by alexweissman** [comment]
This simply shows lines from your PHP error log (every web server running php has one).  So, these are probably some errors you encountered earlier, and didn't realize they were being logged ;-)

**Comment by alexweissman** [comment]
Let me know if you have any more questions.
