### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by mdhall89** [alexweissman/UserFrosting#388]
Hi, 

When users are created, either as Admin or a Standard user, apart from the theme, is there any other difference out of the box?

I was surprised that the standard users can see the list of users and appears to be able to delete the administrator account :/

Please could someone point me in the right direction to restrict this?

Thanks,
Matt

**Comment by alexweissman** [comment]
Yes, [user groups](http://www.userfrosting.com/components/#groups) control a wide range of behaviors in UF, including access control!  Please carefully read about [authorization hooks](http://www.userfrosting.com/components/#authorization) to learn more about this. 

> I was surprised that the standard users can see the list of users and appears to be able to delete the administrator account :/

This should not be the default behavior that ships with the code.  Could you please join us in [chat](https://gitter.im/alexweissman/UserFrosting) and we can figure it out there?
