### ISSUE TITLE
The character encoding of the HTML document was not declared..

### ISSUE THREAD

**Issue by fstaylor104** [alexweissman/UserFrosting#389]
Hey,

I've created a new html page using the userfrosting tutorial and it was up and running without a problem, but I am now getting the following error, and nothing is being displayed:

The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

How would i go about fixing this?and apologies if it is something trivial!

Many Thanks!

**Comment by fstaylor104** [comment]
Appears to have fixed itself!?

**Comment by alexweissman** [comment]
Let me know if the problem comes up again.  The character set should be already declared in the `<head>` element of the templates: https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/templates/common/components/head.html#L2

**Comment by r3wt** [comment]
@alexweissman Perhaps as a precaution the templates should include `<meta name="charset" content="UTF-8" />` as a failsafe for servers that don't provide the header?

**Comment by alexweissman** [comment]
Let us know if this is still a problem.  Referencing your StackOverflow question: http://stackoverflow.com/questions/32234289/setting-response-header-in-slim-userfrosting

**Comment by fstaylor104** [comment]
Alex,


Cheers, didn't get it sorted but after talking with my supervisor i'm going to continue with my project as a normal php project rather than with userfrosting, mainly due to time constraints!


Many Thanks


Fergus


________________________________

**Comment by alexweissman** [comment]
Ok, no problem.  But consider using UF in the future, it will make you a better programmer, professionally speaking!
