### ISSUE TITLE
Auto-logout after idle period

### ISSUE THREAD

**Issue by HedgeShot** [alexweissman/UserFrosting#39]
Hey guys,

It would be great security wise if there was an auto-logout after X minutes of inactivity from the user.

On a side note, I am note so much of a security expert. To stop XSS attacks, UserFrosting sanitize the inputs with the "sanitize" function, is that enough or should I add function such as xss_clean.php that can be found here: https://gist.github.com/mbijon/1098477 ?

Thanks again for the good work!
Seb

**Comment by alexweissman** [comment]
Alright, time to close this.  Autologout is discussed in #66.  XSS sanitization, for the most part, will be handled on the **output** side by Twig, not the input side.  SQL sanitization of course is handled by the PDO library.
