### ISSUE TITLE
Hook ajax form submissions to apply loading effect to buttons

### ISSUE THREAD

**Issue by r3wt** [alexweissman/UserFrosting#391]
http://bootsnipp.com/snippets/featured/loading-button-effect-no-js

request start
`
onbeforesubmit : function(){ button.addClass('m-progress').prop('disabled',true); }
`

request end
`
.always(function(){ button.removeClass('m-progress').prop('disabled',false); });
`

**Comment by alexweissman** [comment]
Cool, those look nice.  I've been using [FontAwesome's animated icons](http://fontawesome.io/examples/#animated) for this, but this is another good option.

**Comment by r3wt** [comment]
@alexweissman On second thought, i think sticking with font awesome would be the best bet for now. these don't look so good on ie 10 and below

**Comment by alexweissman** [comment]
Ok, did it.  Do you think the buttons should be constant-width (so, same width with the loading icon as they were with the original text)?

**Comment by alexweissman** [comment]
Done-zo, automatically handled by `ufFormSubmit`.
