### ISSUE TITLE
Can't create a master account

### ISSUE THREAD

**Issue by aadionroll** [alexweissman/UserFrosting#392]
I am using wamp server and I unziped the rar file into the www folder in wamp. I edited the config-userfrosting.php and changed the database. But I am not able to create the master account. I don't understand how to. Can someone please help ?

**Comment by alexweissman** [comment]
Hi @aadionroll, did the installer come up for you?  It should automatically take you to a page to create the master account.  Please join us in [chat](https://gitter.im/alexweissman/UserFrosting) if you need more help.

**Comment by alexweissman** [comment]
Looks like this was solved in chat.
