### ISSUE TITLE
send user email after account has been activated

### ISSUE THREAD

**Issue by tosh83** [alexweissman/UserFrosting#393]
Is it possible to allow a user to register - appear as 'unactivated' in the system and then when the admin activates their account they get sent an email to let them know?

**Comment by alexweissman** [comment]
Sure, that shouldn't be too hard.  Do you want to specifically require an admin to activate a new account?

Here is where new accounts get registered - you can modify this as needed: 
https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/controllers/AccountController.php#L248-L381

And here is where admins can update user details (including active status):
https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/controllers/UserController.php#L391-L498

So you can modify those as needed.  Feel free to join us in chat if you need additional help.

**Comment by tosh83** [comment]
Hi Alex thanks for getting back to me.

I'm not brilliant with php, know just enough to get me around things - what part of the function do i need to change to prevent the autmatic activation email being sent when a user registers (I need them to be able to register themselves still - but with no access until I check their serial number - I figured out how to get additional fields into the regsitration).

Im guessing that I can add the automatic activation email function into the usercontroller when an admin activates their account?

**Comment by tosh83** [comment]
also Alex, when adding custom fields it seems to add everything in ok (around 14 extra fields to the reg form) except the title seems to appear in another column, and the last column in the database appears in the title field and then shuffles a columns values up by one column after the primary group id? is there anything in particular I may be doing wrong when creating a new user?

**Comment by alexweissman** [comment]
To turn off the activation email, simply remove this code: https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/controllers/AccountController.php#L352-L377

Then put that code into an `if` block here: https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/controllers/UserController.php#L477

```
if (isset($data['active'])){
    // Send email
}
```
Just be sure that you put any new code **after** the authorization checks.

For your problem with new fields, are you talking about the layout of the create/update form?  Maybe we can discuss in chat.

**Comment by tosh83** [comment]
hmm - I don't seem to have these files - Ive just realised im using UserFrosting Version: 0.2.2.

**Comment by alexweissman** [comment]
Ah.  Any chance you can upgrade to 0.3.0?  0.2.2 is sorely outdated and honestly pretty poorly designed.

**Comment by tosh83** [comment]
Im a bit reluctant to at the moment as I started to utilise 0.2.2 about a month or two before I noticed 0.3 came out - in that time I had done a lot to the front end in terms of styling things up and completely customising the front end for the project - Im not too sure how big a job it would be to overhaul it again and I need to have this project in place for next week :( - was just trying to iron out the last few items.

**Comment by alexweissman** [comment]
Hmm, yeah it might be hard to do that in one week.  Well, here is where the activation email is generated in v0.2.2: https://github.com/alexweissman/UserFrosting/blob/stable-0.2.2/models/secure_functions.php#L183-L213

I hope that helps.  It has been a while since I've even looked at the code from 0.2.2...

**Comment by tosh83** [comment]
Im not surprised if you've been busy on v3. Thanks for you help on this, I'll have a look see if I can sort it. I could have kicked myself when I saw it had all been deprecated. Looking at the function can a similar if/else statement be added like in 0.3.0?

**Comment by alexweissman** [comment]
No problem.  Yeah, it sucks for people who were using 0.2.2, but I wanted to get the project [up to speed with this decade](http://www.phptherightway.com/) before even more people started doing it "the wrong way".

For now, you should be able to add the code to send the activation email here: https://github.com/alexweissman/UserFrosting/blob/stable-0.2.2/models/secure_functions.php#L224-L232

But if this is a personal project, or a project that you will be revisiting in any way in the future, I'd highly recommend converting to 0.3.0 when you have the time.

**Comment by tosh83** [comment]
Sorry for my delay in getting back to you Alex - really appreciate your help on this. am I right in thinking that if i take #L183-213 code and insert it into the function in L224-232 this should only send out the activation email once the administrator has activated the users account in the master account and not when they sign up/register?

I installed version 3 on another test server to look into the possibility of updating this current project - a lot has changed!

**Comment by tosh83** [comment]
still having the issue with adding additional data to the user table - seems to all go through ok except it puts the last field into the 'title' column and then puts the default title variable into the second custom colomn I created and then shifts all other values down 1 column after that - heres a link to the addUser function Ive created to see if this may be the issue? https://www.dropbox.com/s/zv7zqywsjvjionv/addfunction-example.txt?dl=0

**Comment by alexweissman** [comment]
My guess is that it would be the way you're passing in your arguments to `addUser`.  By the way, you can use https://gist.github.com/ to post code snippets, in the future.

**Comment by tosh83** [comment]
Im new to github/gist/gitty all of this and not a brilliant coder (more front end) so you'll have to excuse my newbie errors. is it the secure functions file that feeds th adduser function from this statement https://gist.github.com/e0ae8064a319be2addc5.git

**Comment by alexweissman** [comment]
Yes, typically the secure functions would call the db functions, and then you call the secure functions (which would automatically perform auth checks) from your code.

**Comment by tosh83** [comment]
Hi @alexweissman still no joy on these :( was hoping to go live with the project this week too. Been through all the CRUD functions to see where I may be going wrong - run the insert code through sql on it's own from the addUser function - all good, everything goes in order as it should... checked the db_functions.php file numerous times, checked the functions feeding that from createUser and addUser in secure_functions.php, looked at the create_user.php and even the form on register.php with no luck as to why when a user signs up their title goes into a new surname field, moves all column values down by one and then inserts the last columns value in the title column? very odd indeed - any ideas?

**Comment by tosh83** [comment]
Hi @alexweissman I don't know if these snippets will help with anything? https://gist.github.com/7a30af10c40039999e6b.git - secure_functions
https://gist.github.com/553fc6ec48f72f78a848.git - db_functions

**Comment by alexweissman** [comment]
How about the code that calls `createUser`?  Can I see that?

**Comment by tosh83** [comment]
Sure which file is that in?

**Comment by alexweissman** [comment]
in `create_user.php`.  Did you remember to change that too?

**Comment by tosh83** [comment]
yeah - Im sure Ive picked up everything in there too.

https://gist.github.com/34a6284ac7a7b9d1ba7b.git

**Comment by alexweissman** [comment]
Not quite.  In `create_user.php`, you have:
`createUser($user_name, $display_name, $email, $firstname, $title, $surname, $house, $address1, $town, $county, $postcode, $tel, $modelname, $modelsize, $serial, $dop, $parkname, $parkaddress, $parkpostcode, $password, $passwordc, $require_activation, $admin)`

and in `secure_functions.php`, you have it defined as:

`createUser($user_name, $display_name, $email, $firstname, $surname, $house, $address1, $town, $county, $postcode, $tel, $modelname, $modelsize, $serial, $dop, $parkname, $parkaddress, $parkpostcode, $title, $password, $passwordc, $require_activation, $admin)`

Notice that you moved `$title` in the call to the function.

**Comment by tosh83** [comment]
ahh! good spot! - does the order of the variables have a bearing on the function? I thought as long as the variable was in the function it could be used within at any pomit? - I will admit though php isn't my strong point :(

**Comment by alexweissman** [comment]
nope - function parameters get matched based on the order, not their names.

This is another reason to switch to 0.3.0, btw - no need to deal with individual parameter names anymore ;-)

**Comment by tosh83** [comment]
really? that is a big plus - Ive installed 0.3.0 on another server to test it all out. Got it up and running which was a bit confusing to start - put both folders in public. 

Just back to the $title issue - do these function need to be in order as they appear in the database?

**Comment by alexweissman** [comment]
nope, because you bind them by name in the bound parameter list.

join us in chat if you have questions about the setup for 0.3.0.

**Comment by tosh83** [comment]
i tried making sure the call to function and function parameters matched - when they do for some reason it doesn't allow the registration form to submit - all fields go green but nothing happens - change the create functions and call back to how I had them and they work? am I doing something wrong to prevent the form from working?

**Comment by tosh83** [comment]
do creatUser and addUser function parameters all need to match in a particular/same order?

**Comment by alexweissman** [comment]
So, are you getting any messages in your browser console?  

Your questions are kind of straying from UF-specific, to more general questions about PHP.  I would suggest StackOverflow for some of these more generic programming questions.

**Comment by tosh83** [comment]
Sorry Alex, didn't mean to stray on the php - I was asking if them two particular functions and calls needed to reflect the same ordering/names in the parameters.

500 internal server error in the console? even after switching it back to how it was...?

**Comment by alexweissman** [comment]
Ah, ok.  No, in general, it is just the function definition and function call where the order of parameters need to match up.  There is usually no relationship between one function and a different function's parameters.

Glad you got your issue worked out though, and thanks for the donation!
