### ISSUE TITLE
Subdomain install

### ISSUE THREAD

**Issue by riotbr** [alexweissman/UserFrosting#394]
First of all, sorry about my english ;)

I have one question about the install on a subdomain. I've read the instructions and I'm really confused about something:

This is the suggested structure

```
|-- etc
|-- logs
|-- public_html      // Put the contents of 'public' in here
|   |
|   |-- css
|   |-- images
|   |-- js
|   |-- .htaccess
|   |-- index.php
|
|-- userfrosting    // Put the contents of 'userfrosting' in here
|   |-- auth
|   |-- controllers
|   |-- ...
```

In my case, it will be:

```
|-- etc
|-- logs
|-- public_html
|   |
|   |-- MY_SUBDOMAIN      // Put the contents of 'public' in here
|   |   |-- css
|   |   |-- images
|   |   |-- js
|   |   |-- .htaccess
|   |   |-- index.php
```

So ... where the "userfrosting" folder must be located?

Thanks in advance ;)

**Comment by alexweissman** [comment]
The `userfrosting` directory can be anywhere you want it to be, actually.  I'd recommend putting it in the top level of your directory, though, outside of `public_html`.  Just make sure that in your `index.php`, you update the `require_once` command so that it points to the correct location of `userfrosting/initialize.php`.

**Comment by riotbr** [comment]
Alex, thanks for the quick response.

I think that my first attempt was unsuccessful because of my PHP version. My hosting server gave me the option to set the ".htaccess" using the 5.4 or 5.5, the available versions on the server. I'll make a new upload and change the 'require_once' command.

**Comment by riotbr** [comment]
As I've suspected, the problem was the PHP version. UserFrosting installed and running like a charm =D

Thanks a lot, Alex.

**Comment by alexweissman** [comment]
Cool, glad it's working and welcome to the UF community!

**Comment by riotbr** [comment]
@alexweissman , something weird happened here.

After the first screen (Site Settings), I just clicked on the 'Dashboard' link and 'Configuration>SIte Setttings' again. The screen gone blank. This is the error log:

[26-Aug-2015 21:21:43 America/New_York] Error in /home/greenpub/userfrosting/models/mysql/MySqlSiteSettings.php on line 309: file(error_log): failed to open stream: No such file or directory
[26-Aug-2015 21:21:43 America/New_York] #0 [internal function]: Slim\Slim::handleErrors(2, 'file(error_log)...', '/home/greenpub/...', 309, Array)
#1 /home/greenpub/userfrosting/models/mysql/MySqlSiteSettings.php(309): file('error_log')
#2 /home/greenpub/userfrosting/controllers/AdminController.php(36): UserFrosting\MySqlSiteSettings->getLog(50)
#3 /home/greenpub/public_html/gpmanager/index.php(196): UserFrosting\AdminController->pageSiteSettings()
#4 [internal function]: {closure}()
#5 /home/greenpub/userfrosting/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#6 /home/greenpub/userfrosting/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#7 /home/greenpub/userfrosting/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#8 /home/greenpub/userfrosting/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#9 /home/greenpub/userfrosting/auth/CsrfGuard.php(51): Slim\Middleware\MethodOverride->call()
#10 /home/greenpub/userfrosting/vendor/slim/slim/Slim/Slim.php(1302): Slim\Extras\Middleware\CsrfGuard->call()
#11 /home/greenpub/public_html/gpmanager/index.php(365): Slim\Slim->run()
#12 {main}

**Comment by alexweissman** [comment]
Ironically, the error is happening [when it is trying to open the error log](https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/models/mysql/MySqlSiteSettings.php#L309).  You can manually set the path to the error log, or fix the path in your `php.ini`, etc...

**Comment by riotbr** [comment]
The path it's correct. The problem happens if I delete (cleaning and maniac purposes lol) the file of the website's root. It would be nice to have something to clean the file and/or mark the errors as solved.

**Comment by alexweissman** [comment]
If you're really into logging, you might want to check out [Monolog](https://github.com/Seldaek/monolog).  I'm hoping to integrate it into UF at some point.
