### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by riotbr** [alexweissman/UserFrosting#395]
Hi, @alexweissman.

After being installed, and accessing the link "Site Configuration", the screen gone blank. Below is the error message with debug enabled:

Slim Application Error

The application could not run because of the following error:
Details
Type: ErrorException
Code: 2
Message: file(error_log): failed to open stream: No such file or directory
File: /home/greenpub/userfrosting/models/mysql/MySqlSiteSettings.php
Line: 309
Trace

#0 [internal function]: Slim\Slim::handleErrors(2, 'file(error_log)...', '/home/greenpub/...', 309, Array)
#1 /home/greenpub/userfrosting/models/mysql/MySqlSiteSettings.php(309): file('error_log')
#2 /home/greenpub/userfrosting/controllers/AdminController.php(36): UserFrosting\MySqlSiteSettings->getLog(50)
#3 /home/greenpub/public_html/gpmanager/index.php(196): UserFrosting\AdminController->pageSiteSettings()
#4 [internal function]: {closure}()
#5 /home/greenpub/userfrosting/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#6 /home/greenpub/userfrosting/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#7 /home/greenpub/userfrosting/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#8 /home/greenpub/userfrosting/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#9 /home/greenpub/userfrosting/auth/CsrfGuard.php(51): Slim\Middleware\MethodOverride->call()
#10 /home/greenpub/userfrosting/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Extras\Middleware\CsrfGuard->call()
#11 /home/greenpub/userfrosting/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#12 /home/greenpub/public_html/gpmanager/index.php(365): Slim\Slim->run()
#13 {main}

**Comment by riotbr** [comment]
*UPDATE:  The error occurs only when I delete the error_log. Normal?

**Comment by alexweissman** [comment]
Yup, this line of code is where it is trying to open the error log!

**Comment by riotbr** [comment]
Hi, @alexweissman 

I've decided start from the beginning since the new version it's up; deleted all the stuff of my server.

**1st error -** I had an error (*trying to connect with the database*) on the first step (accessing the index, that proceed with the install). A reload (F5) solved the problem. The install run without any problem. A `error_log` file was created. What I did was to delete this file.

**2nd error -** I've created the master account. I had an error (*blank page*) in the first login. I just reloaded the page (F5) and everything is fine. A new `error_log` file was created. What I did was to delete this file (again).

I don't understand the 1st error since a reload (F5) "solved" the problem. The 2nd error occurred because I'd deleted the `error_log` file. Every time I delete the `error_log` file and try to access a settings page (ie, config/settings) I have the error that is always solved with the reload (F5).

My questions:
- Is not supposed to not have the 1st error?
- It seems like it's **necessary** the existence of a `error_log` file. Ok, I have a little paranoia here, but it is assumed that the absence of errors (ie, the absence of a error_log file) should not produce new errors, right?

Talking about the error message:
*[01-Sep-2015 13:26:33 America/Sao_Paulo] Error in /home/greenpub/userfrosting/models/mysql/MySqlSiteSettings.php on line 309: file(error_log): failed to open stream: No such file or directory
[01-Sep-2015 13:26:33 America/Sao_Paulo] #0 [internal function]: Slim\Slim::handleErrors(2, 'file(error_log)...', '/home/greenpub/...', 309, Array)
#1 /home/greenpub/userfrosting/models/mysql/MySqlSiteSettings.php(309): file('error_log')*

[]'s

**Comment by alexweissman** [comment]
@riotbr , can you join chat: https://gitter.im/alexweissman/UserFrosting to discuss this?

**Comment by alexweissman** [comment]
Ok, it should detect this condition now.
