### ISSUE TITLE
upgrade V.0.2.2 to latest version

### ISSUE THREAD

**Issue by marcie8** [alexweissman/UserFrosting#396]
Hello alex,

I got an question, how easy is it to upgrade from V.0.2.2 to V3 the latest one? i noticed it has a whole new mapping? Hope to hear from you

Thanks!

**Comment by alexweissman** [comment]
It will be some work, but doable.  How big is your project?

**Comment by marcie8** [comment]
Its medium but did not change that much of "core" files. i think i will start when i got some time left. Next versions will be the same mapping/structure?

**Comment by alexweissman** [comment]
Yes, I don't expect any changes as radical as the last one any time in the near future.

**Comment by alexweissman** [comment]
Let us know if you need any more assistance.
