### ISSUE TITLE
New users getting added to all groups, even when not selected

### ISSUE THREAD

**Issue by riotbr** [alexweissman/UserFrosting#397]
Here we go... ;)

I had a blank screen and no error messages after creating a new user and using the same e-mail address of my master account.

So, I tried to create the user "teste1" using other e-mail address: everything gone fine.

Creating a new user, "teste2", and using the same e-mail address of "teste1", the problem occurs again.

The error_log file doesn't have new records. The debug mode is active and doesn't report anything.

**Comment by alexweissman** [comment]
Actually, debug mode needs to be turned `off` for UF's error-reporting to work.  Otherwise, Slim tries to send the debug report as part of the `POST` response, which then never gets displayed anywhere.

**Comment by riotbr** [comment]
Turned off to see what I have of new here.

@alexweissman , for some reason I've encountered some problems related to users. Look:

- created a new user;
- selected de group "User" only;
- after created, the new user it's on all groups;
- I edited the user leaving him only on the group "Users" on the Admin panel;
- I'm following that tutorial "CREATING A NEW PAGE". The step that show only the groups of the user returned an error (it looks like a lost css file);
- I looked on the `MySQL` about the groups of this user in `uf_group_user`. It looked right;
- So, I looked about the `primary_group_id` in `uf_user`: it was marked as "0", so I edited to "1" and it solved the problem.

**Comment by riotbr** [comment]
So, to be clear:

- Created a new user now. The ID is **6**;
- In the `uf_user` table, **6** it's on the `primary_group_id` **1**;
- User **6** it's related to all the groups (1, 2 and 3) in the table `uf_group_user`;
- On the Admin Panel, I removed **6** from the groups 2 and 3;
- User **6**, now: `uf_user` table/`primary_group_id` **1**; related only to the group 1 in the table `uf_group_user`;
- On the Admin Panel, I changed **6** from the group 1 to 3;
- User **6**, now: `uf_user` table/`primary_group_id` **0**; related only to the group 3 in the table `uf_group_user`.

**Comment by alexweissman** [comment]
Ok, I will look into this.  This is all happening with a fresh install, and no modifications to the code?

**Comment by riotbr** [comment]
I confirm: fresh install; no modifications to the code.

The only "hack" necessary was to modify the `.htaccess` file adding `AddHandler application/x-httpd-php55 .php` (to select the PHP version; versions 5.3, 5.4 and 5.5 are available in my server).

**Comment by alexweissman** [comment]
Ok, I have confirmed this bug.  I wonder when/how it crept in!  Anyway, will try to fix it soon.

**Comment by alexweissman** [comment]
Alright, please try again.

**Comment by riotbr** [comment]
@alexweissman , problem solved =D

**Comment by alexweissman** [comment]
:+1: yeah a few other people mentioned issues that, in retrospect, were caused by this bug.  But, no one actually bothered to investigate it until you came along ;-)

**Comment by riotbr** [comment]
But let me be a little self critic... I don't now if the resource was available, but only now I saw the "Set as primary group" button. Your fix it's assigning one and avoiding the "0" group, so this setting (of the button) don't cause any problem if not used.

**Comment by alexweissman** [comment]
Yeah, that button has always been there.  "Primary group" is different from "group membership".

The problem was that it was assigning users to **every** group, not just the checked groups.

**Comment by riotbr** [comment]
As I see, the selection of a primary group it's mandatory.

`Creating` a new user, he is member of the "Users" group (the one marked as "Default Primary Group" on the groups panel). If I unselect the group "Users" and select any other, I have an error if I don't mark the "Primary group" box of the new group.

What you think... if I don't have a selected group, the first selected group, the one intended to the user, is selected as primary too.

**Comment by alexweissman** [comment]
Yes, every user **must** have a primary group.  Primary group determines which theme, icons, etc will be applied to them when they log in.

**Comment by riotbr** [comment]
I think that isn't necessary modify anything (to change their functionality in this regard). A specific alert message for this case, maybe (It's mandatory to choose the selected group as a primary!)?

Btw... I always played as Terran lol

**Comment by alexweissman** [comment]
Hmm, not sure if you understand.  You don't have to choose *the* selected group as primary, because it is possible to belong to multiple groups.  But you must choose *a* selected group as primary.

**Comment by riotbr** [comment]
"But you must choose a selected group as primary."

Yeah, I understood. But if I don't choose the selected group as primary, I receive an alert about a server error when creating the user. I think it would be more friendly a specific alert for this.

![db-alert](https://cloud.githubusercontent.com/assets/1090085/9532694/8f8e1682-4ce3-11e5-9f35-e5f0db437aa1.jpg)

**Comment by alexweissman** [comment]
Oh, I see.  Yeah, I thought there was a more specific error message...I'll look into it.
