### ISSUE TITLE
display specific content if user is a member of group/s

### ISSUE THREAD

**Issue by vinceaar0n** [alexweissman/UserFrosting#398]
please help me i tried installing userfrosting and i'm loving it.. but i cant seem to figure out how to display specific content if user is a member of group/s any help would be greatly appreciated..

**Comment by alexweissman** [comment]
There are a couple of ways to do this.  
1. You could create a new [theme](http://www.userfrosting.com/components/#theming) for a specific group.
2. You could use authorization hooks, and assign your group(s) to those authorization hook(s) in the `authorize_groups` table.  Then, you can use the Twig `checkAccess` function on the assigned authorization hook:

```
{% if checkAccess('my_custom_hook') %}
    // Group-specific HTML goes here
{% endif %}
```

Please join us in [chat](https://gitter.im/alexweissman/UserFrosting) for more assistance.

**Comment by riotbr** [comment]
@vinceaar0n , take a look on the available tutorial `LESSON 1 - CREATING A NEW PAGE` (http://www.userfrosting.com/tutorials/lesson-1-new-page/). It helped me a lot.

**Comment by vinceaar0n** [comment]
i feel pretty stupid .but im trying to learn. this is what i got so far.
![test](https://cloud.githubusercontent.com/assets/14003067/9529358/59b9ee7a-4d2c-11e5-9376-bfb99b4a07c8.png)


{% if checkAccess('test_me') %}
 // Group-specific HTML goes here
{% endif %}




 but still not working

**Comment by alexweissman** [comment]
Which group are you trying to grant access to?  Take a look at the `group_id` column.

**Comment by vinceaar0n** [comment]
group (test) with id group id 3

**Comment by alexweissman** [comment]
Ok, so what you probably want is:

| id  | group_id | hook | conditions |
| ------------- | ------------- | ------------- | ------------- |
|  `10`  | `3` | `test_me` | `always()` |

**Comment by vinceaar0n** [comment]
now i get it.. thanks alot.. super..

**Comment by alexweissman** [comment]
No problem.  For most basic situations, you can use a condition of `always()`.  You only need to provide specific conditions when the user's access is context-dependent in some way.

Don't forget to star the repo!

**Comment by alexweissman** [comment]
Ok, looks like this is solved...
