### ISSUE TITLE
Clueless.. about twig

### ISSUE THREAD

**Issue by vinceaar0n** [alexweissman/UserFrosting#399]
could anybody point me to where i could read or find tutorials regarding twig.. i have a php that displays sql data but cant seem to figure out how to use it in userfrostin with twig. thanks

**Comment by alexweissman** [comment]
Writing a Twig template: http://twig.sensiolabs.org/doc/templates.html
Passing data into a template: http://twig.sensiolabs.org/doc/api.html

> To render the template with some variables, call the render() method:
`echo $template->render(array('the' => 'variables', 'go' => 'here'));`

**Comment by vinceaar0n** [comment]
still confused... is it ok if you give me an example? what im trying to accomplish is this

eg. sql database with table titled "tabletest" and columns tilted "columnid" and "columntest"
<table class="tg">
  <tr>
    <th class="tg-s6z2" colspan="2">tabletest</th>
  </tr>
  <tr>
    <td class="tg-s6z2">columnid</td>
    <td class="tg-s6z2">columntest</td>
  </tr>
  <tr>
    <td class="tg-s6z2">1</td>
    <td class="tg-s6z2">data</td>
  </tr>
</table>

now id like to be able to display/view data on  "columntest" with "columnid" 1 eg. {{tabletest.columnid_1.columntes_data}} and also be able to update database

where on userfrosting do i do this? index.php in public dir? where to put sql settings connection? thanks again.

**Comment by alexweissman** [comment]
Have you read any of the documentation, including:
http://www.userfrosting.com/navigating/
and
http://www.userfrosting.com/tutorials/

That should get you started.

**Comment by vinceaar0n** [comment]
reading it now but nid a little help creating my DataController.php in userfrosting/controllers
cant seem to get it to work

**Comment by alexweissman** [comment]
did you install composer and run `composer update`?

**Comment by vinceaar0n** [comment]
Another Question when installing composer should i specify installation directory?

because default install gives me this error "Composer could not find a composer.json file in home/bitnami To initialize a project, please create a composer.json file" 

should i move userfrosting/composer.json to home/bitnami? and if so should i move it back after update?

**Comment by alexweissman** [comment]
no, you should install Composer globally.  
```
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
```
Please see https://getcomposer.org/doc/00-intro.md#globally

Each project still needs to have its own `composer.json`, though.  So, don't move UF's `composer.json`.  Composer does not install "global" packages, but the composer application itself should be globally accessible.

After installing Composer, all you need to do is run `composer update` **in the same directory that `composer.json` is in**.

**Comment by vinceaar0n** [comment]
wait you lost me there how is installing and updating composer going to help me with DataController.php in userfrosting/controllers?

**Comment by alexweissman** [comment]
Because Composer is responsible for autoloading classes from PHP files (such as the new one that you are creating).

**Comment by vinceaar0n** [comment]
ahh ok thanks for the info learning alot. but finished with the installation and update but still stuck with a white screen.

**Comment by vinceaar0n** [comment]
i need another approach. i followed your tutorial exactly step by step basically replacing group with data. and creating a new datacontroller any idea on what im doing wrong?

**Comment by vinceaar0n** [comment]
basically im trying to make userfrosting twig display or update data from my database are there other tutorials i can read?

**Comment by alexweissman** [comment]
So, to interact with the database, you'll probably want to extend the data model.  I haven't made a tutorial for that yet.  But, were you able to complete **both** tutorials?

**Comment by vinceaar0n** [comment]
yup. i also tried creating a MySqlDataLoader.php from userfrosting/modals/mysql but all i get is a white screen

**Comment by vinceaar0n** [comment]
is there a temporary fix i can use or do to allow me to interact with the database? or can i temporarily disable twig on a single or specified directory, form or page? to be able to execute my php script?

**Comment by alexweissman** [comment]
> i also tried creating a MySqlDataLoader.php from userfrosting/modals/mysql but all i get is a white screen

you need to provide more information.  What exactly did you do?

I would recommend against trying to "temporarily disable" Twig.  It is a standard templating library that is used by the professional PHP community, along with Composer, and is worth spending some time to understand correctly rather than looking for a quick fix.

Do you understand the basic design patterns that UF uses?  The point of MVC and the Front Controller?

**Comment by alexweissman** [comment]
Also, I should point out that your model (for example, your `MySqlDataLoader` class) has nothing to do with Twig.  Twig is for the "view" part of "model-view-controller".  Your controller (`DataController`) takes data from the model and passes it into the view by calling `render`.  See, for example, how the "users" page is generated:
https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/controllers/UserController.php#L102-L125
You'll see how the last thing that the controller does, after gathering all the data via the model, is calling `render` on the Twig template (`user_info.html`) and passing in the data as dynamic content.

**Comment by alexweissman** [comment]
And, for your model, you'll want to declare your table name and columns like so: 
https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/initialize.php#L55

**Comment by vinceaar0n** [comment]
well thanks for the info.. and advice going to re-read the tutorials links and advice you've been giving then try to see if i can get this to work again if not ill post/upload the codes then maybe you can point out what im doing wrong? if thats ok? but i wanna see if i can get this working first

**Comment by alexweissman** [comment]
If you head into chat: https://gitter.im/alexweissman/UserFrosting and go through the archive, you will see that I just walked someone through the entire process for extending the data model.
