### ISSUE TITLE
Blank page when installing master, and /public/account/login

### ISSUE THREAD

**Issue by Sveott** [alexweissman/UserFrosting#403]
Hi!

Getting a blank page when installing master, but user shows up in PHPMyAdmin. And when then accessing localhost/public/ and trying to log in, it just shows "The requested URL /public/account/login was not found on this server."

Any idea what the problem is?

**Comment by alexweissman** [comment]
>  user shows up in PHPMyAdmin

You mean, the root user was successfully created in the `user` table?  Or just that you can see the `user` table was created successfully?

What server are you using?  Are you installing locally or on a live server?

**Comment by Sveott** [comment]
Can see the root user successfully created. When accessing localhost/public I get redirected to /public/dashboard. 

Running Apache/2.2.22 (Debian) headless from my Raspberry Pi.

**Comment by Sveott** [comment]
And when editing install_status from complete to new, and then trying to access localhost/public I get redirected to public/config/settings/? and install_status changes to complete again.

**Comment by alexweissman** [comment]
Yup, the second behavior you described is correct.  This is so UF brings people to the site settings page the first time they log in after installation.

So, it is redirecting you to `/public/dashboard`, and then back to the login page?

**Comment by Sveott** [comment]
Nope, just to /public/dashboard which is blank.

**Comment by Sveott** [comment]
No, sorry, not blank! I recieve this message "The requested URL /public/dashboard was not found on this server."

**Comment by alexweissman** [comment]
Where are you receiving that message?  In the browser console, or on the page itself?  Maybe you'd better join us in chat: https://gitter.im/alexweissman/UserFrosting

**Comment by alexweissman** [comment]
I believe I have figured out how to resolve the issues with Debian/Raspian.  I have updated the installation instructions to account for this problem.  See http://www.userfrosting.com/installation/
