### ISSUE TITLE
Blank page when accessing secure page without valid session

### ISSUE THREAD

**Issue by jkrenge** [alexweissman/UserFrosting#407]
Hi!

* Userfrosting 0.2.2
* Secure pages in subfolder portal/

I think I broke the config somehow: I am receiving a blank page whenever I am accessing a secure page without a valid session (e.g. `https://subdomain.domain.com/portal/`). When I manually enter the root URL (`https://subdomain.domain.com/`), I get the corresponding error message `LOGIN_REQUIRED` and can log in. But I assume the default behaviour is to forward my browser to hat page, when a secure page is accessed. 

Any ideas on how to restore that behaviour?

Thanks. :-)

**Comment by alexweissman** [comment]
Hi @jkrenge, 
Proper handling of routes in v0.2.2 is a hot mess.  This is actually one of the issues that v0.3.0 solves by bringing Slim into the picture.
How far along are you in your project?  Is there any chance you can switch to v0.3.x?

**Comment by jkrenge** [comment]
Actually we're already live and just noticed this behaviour. Would it make sense to diff the template files and such to the original to find any misconfiguration?

**Comment by alexweissman** [comment]
So, looking back on it, each secure page/file does this check:
https://github.com/alexweissman/UserFrosting/blob/stable-0.2.2/account/account_settings.php#L37-L39

This calls `apiReturnError`, defined here: https://github.com/alexweissman/UserFrosting/blob/stable-0.2.2/models/error_functions.php#L34-L49

So if you're not logged in at all, it should be trying to redirect you to `login.php`.  Can you check your browser console and see where it is trying to redirect you to?

**Comment by jkrenge** [comment]
Okay, I located the method and it's unchanged. That's good. :-)

However, I do not see any attempt to redirect in my browser. Maybe I even have a wrong config in my Apache?

**Comment by alexweissman** [comment]
Interesting.  Is it possible that the `$ajax` parameter for `apiReturnError` is getting set to `true`?  Even in that case though, you'd see a response like `["errors" => 0...`.

Are you getting any errors in the PHP log?

**Comment by jkrenge** [comment]
Okay, this was a good idea, why didn't I think of that? I had a look at my PHP Error log, and there it is:

    mod_fcgid: stderr: PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/virtual/pl/html/portal/index.php:20) in /var/www/virtual/pl/html/models/error_functions.php on line 46

So the problem is that the headers are somehow already sent. Maybe a wrong config of Apache?

**Comment by alexweissman** [comment]
What's in `portal/index.php` at line 20?

**Comment by jkrenge** [comment]
Just

    echo renderAccountPageHeader(array("#SITE_ROOT#" => SITE_ROOT, "#SITE_TITLE#" => SITE_TITLE, "#PAGE_TITLE#" => "Dashboard"));

**Comment by alexweissman** [comment]
So, it sounds like `apiReturnError` is somehow getting called *after* that line gets executed.

**Comment by jkrenge** [comment]
In terms of UserFrosting, I think the site only calls

    echo renderMenu("portal-tracking");
    ...
    echo renderCallToAction();
    ...
    echo renderFooter();

after that.

Above line `20` I have the usual:

    require_once("../models/config.php");

    // Request method: GET
    $ajax = checkRequestMode("get");

    if (!securePage(__FILE__)){
        apiReturnError($ajax);
    }

    setReferralPage(getAbsoluteDocumentPath(__FILE__));

**Comment by alexweissman** [comment]
do you have any closing `?>` tags?  sometimes, if whitespace gets added after them, it will be interpreted as output.  It is best to just not use the closing `?>` tags in general.

**Comment by jkrenge** [comment]
Sorry for the short passages, I could have just posted the first few lines of the site:

    <?php

    require_once("../models/config.php");

    // Request method: GET
    $ajax = checkRequestMode("get");

    if (!securePage(__FILE__)){
        apiReturnError($ajax);
    }

    setReferralPage(getAbsoluteDocumentPath(__FILE__));

    ?>

    <!DOCTYPE html>
    <html lang="en">

    <?php
      echo renderAccountPageHeader(array("#SITE_ROOT#" => SITE_ROOT, "#SITE_TITLE#" => SITE_TITLE, "#PAGE_TITLE#" => "Dashboard"));
    ?>

    <body>

So yes, I do have closing `?>` tags, but what's the alternative? You mean generating all output via `echo`?

The head of the page is the same as in, say, `account/dashboard.php`.

**Comment by alexweissman** [comment]
The alternative, and the recommended usage actually, is to [omit the final ?> tag entirely](http://www.php-fig.org/psr/psr-2/#2-2-files).  So, for files that are pure PHP, this can go: https://github.com/alexweissman/UserFrosting/blob/stable-0.2.2/models/error_functions.php#L95

**Comment by alexweissman** [comment]
(yes, 0.2.2 doesn't follow PSR at all, yet another reason to upgrade to 0.3.0 as soon as possible) ;-)

**Comment by jkrenge** [comment]
Oh wow, I learn something new every day. :-)

Alright, I'll leave it as it is for the moment and move to 0.3.0 asap.

**Comment by alexweissman** [comment]
let me know if removing the `?>` tags helps in the meantime.

**Comment by jkrenge** [comment]
No, unfortunately not. I kept having the same error.

I now did a very dirty hack, in `apiReturnError()` at L46 I inserted a check whether the headers are already set, and if so, forward via Javascript.

    if (headers_sent()) {
      echo "Invalid sessions, you're being forwarded... <script type='text/javascript'>window.location.href = 'https://url-to-login'</script>";
    } else {
	    header('Location: ' . $failure_landing_page);
    }

https://github.com/alexweissman/UserFrosting/blob/stable-0.2.2/models/error_functions.php#L46

**Comment by alexweissman** [comment]
Lol.  Well at this point, I guess if it works, it works...

**Comment by jkrenge** [comment]
Right? :-)

**Comment by alexweissman** [comment]
Let me know if you need any more help or want to talk about upgrading to v0.3.0!
