### ISSUE TITLE
Want to upgrade my UF version

### ISSUE THREAD

**Issue by iamrohan14** [alexweissman/UserFrosting#408]
Hey i made my project with the help of UF and now there is a new upgrade in UF i.e 0.3.0 .so how can i upgrade my whole UF along with my project.
Please help :)

**Comment by alexweissman** [comment]
Please see #396.  0.3.0 is radically different from 0.2.2, so the upgrade will have to be done manually.  However in the future, you can create your project as a fork of the main repo.  Then you can make additional upgrades later simply by merging the master branch into your fork.

**Comment by iamrohan14** [comment]
Yes i have seen #396 . bt i have done lots of chnges . right now i have to stick with 0.2.2

**Comment by alexweissman** [comment]
Ok.  I recommend upgrading as soon as possible, though.  The new version is more maintainable, and will make your life a lot easier going into the future.

**Comment by iamrohan14** [comment]
I too want to upgrade . but i think this manual thing will destroy my project :/

**Comment by alexweissman** [comment]
I feel you.  I've actually been putting off upgrading my own business software (which is very complex) to the new version.  But, I've decided that I won't implement any more features until I finally suck it up and do the upgrade ;-)

**Comment by iamrohan14** [comment]
I will try upgrading .if possible :/

**Comment by alexweissman** [comment]
Let us know if you need any help!
