### ISSUE TITLE
How to protect Gitlist or any other web tool using UserFrosting?

### ISSUE THREAD

**Issue by acrolink** [alexweissman/UserFrosting#410]

**Comment by alexweissman** [comment]
I don't know what this means.

**Comment by acrolink** [comment]
I meant, is it possible to provide access control via UserFrosting to packages like Gitlist or other web based PHP applications?

**Comment by alexweissman** [comment]
Yup.  Access control is done programmatically, so all you need to do is add calls to `checkAccess` in the controller/router for those applications.  See http://www.userfrosting.com/components/#authorization for more information on how access control works in UF.

**Comment by acrolink** [comment]
@alexweissman 

Thanks very much. I still think it would be very helpful if you could provide some documentation as how to load UserFrosting under another web app like Gitlist.

I tried earlier today, but I could not figure out how to merge the two apps.

**Comment by alexweissman** [comment]
>  documentation as how to load UserFrosting under another web app like Gitlist

This is going to be highly specific to each application you wish to integrate with UserFrosting.  I have no idea how Gitlist is laid out, how exactly you want to integrate the two pieces of software (i.e., merge them into a single application, or having them communicate via a REST API), and so forth.

The best thing to do would be to go through the tutorials for UserFrosting, and then decide how you want to proceed.  UF and Gitlist both use Twig for templating, which is good, but Gitlist appears to use Silex as its routing framework, while UF uses Slim.  You will need to pick one of those frameworks and adapt the code of either UF or Gitlist to work with whichever framework you choose.

**Comment by acrolink** [comment]
@alexweissman 

Thank you very much. I will learn more about these systems later.

**Comment by alexweissman** [comment]
No problem.  Feel free to join us in chat if you have specific questions about UF/Slim/Twig: https://gitter.im/alexweissman/UserFrosting
