### ISSUE TITLE
Not able to connect to db

### ISSUE THREAD

**Issue by iamrohan14** [alexweissman/UserFrosting#411]
Hello again , i just upload my project from local to godaddy hosting.. Bt i m not able to login or register.. Coz i m unable to connect to database.

I renamed the hostname, username,password, database name in model/db-settings.php

Can anyone help me in resolving this issue .?

**Comment by alexweissman** [comment]
Did you create a database on your hosting account?

**Comment by iamrohan14** [comment]
Yes i created a database .. And updated the database name nd info in  db-settings

**Comment by alexweissman** [comment]
Could be a problem on GoDaddy's end.  Are you able to connect through any other PHP scripts?

**Comment by michaelmbowyer** [comment]
On the GoDaddy server, did you add the user to the database? This part is not always mentioned so it might be that the user isn't authorised.

**Comment by iamrohan14** [comment]
Sorry i forgot it was mysqli error ..
Now we have to use $link variable with the query.. The problem is solved :)
