### ISSUE TITLE
Beefing up the data model with Illuminate

### ISSUE THREAD

**Issue by alexweissman** [alexweissman/UserFrosting#412]
I'm thinking about rebuilding the data model layer (so, the `MySql*` classes) on top of Laravel's [Illuminate](http://laravel.com/docs/5.1/database) database layer.  It works in a very similar way to our current data model (so, a combination of active records and static access facade), but is a lot more powerful.

I will try to make it fully backward-compatible with the existing data layer as well, so that it won't be necessary to make changes in other parts of the code.

**Comment by ssnukala** [comment]
Cool. Looking fwd to that.

**Comment by alexweissman** [comment]
I'll push a dev branch with Illuminate in a couple of days.

**Comment by ssnukala** [comment]
Cool

**Comment by alexweissman** [comment]
Alright, here is a rough cut: https://github.com/alexweissman/UserFrosting/tree/dev/userfrosting/models/database
Seems to be working well, but I haven't tested it thoroughly yet.  Some unit tests would be good ;-)

**Comment by alexweissman** [comment]
Some people like it, some people don't, but it drastically reduces our code maintenance load so it's here to stay ;-)
