### ISSUE TITLE
Only root / user_id_master can edit group membership

### ISSUE THREAD

**Issue by FrNico** [alexweissman/UserFrosting#414]
Not sure if I'm missing something, but seems only root user / id referred to user_id_master can edit group membership today.
I searched in previous issues, seems it was mentionned here:
https://github.com/alexweissman/UserFrosting/issues/362

I'm trying to delegate group membership edit to group "Administrators", but while Admin members can see list of users, and even group membership, doesn't seem they can EDIT group membership, they can simply see it, and edit all other settings.

Is it a bug or intended behavior? Can we delegate group membership edit to Administrators group?

Thanks!

**Comment by alexweissman** [comment]
It is neither a bug nor an intended behavior, it is just the default behavior that you can easily configure.  If you look in the table `authorize_groups`, you can see that group 2 (that's "Administrators") has various permissions, including `view_account_settings` and `update_account_settings`.  You can add the property `groups` to the list of properties that group 2 has permission on `update_account_settings`.
