### ISSUE TITLE
Slim bug could cause unexpected outcomes if post data contains an array.

### ISSUE THREAD

**Issue by r3wt** [alexweissman/UserFrosting#416]
See here for more information: https://github.com/slimphp/Slim/issues/1508  

If anyone forsees this being a problem, i recommend that we possibly find some way to mitigate this. I'm thinking that if at all possible, we could provide a plugin function to fortress @alexweissman What do you think about that idea?

maybe we could add a flag like `is_array:true` to the validation logic, and if it is the fortress plugin would known to pull the data from normal `$_POST` array and merge it into Slim's `$request->post()`

**Comment by alexweissman** [comment]
Hmm, so it looks like they traced that back to HHVM.  Does it make sense to do this with Fortress?  Maybe we should just override Slim's `post()` method in our `UserFrosting` class, which extends `Slim`.

**Comment by r3wt** [comment]
@alexweissman i think that this is a moot point now that its been traced back to hhvm. odds are they will fix it within a month or two, and the amount of UF users affected is probably low.

**Comment by alexweissman** [comment]
Ok, sounds good.
