### ISSUE TITLE
UserController->formUserCreate() assumes there is a primary group (Master branch)

### ISSUE THREAD

**Issue by Aterbonus** [alexweissman/UserFrosting#417]
If there isn't a primary group, the form to create an user will not be displayed.

In [line 184](https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/controllers/UserController.php#L184):
```php
$primary_group = GroupLoader::fetch(GROUP_DEFAULT_PRIMARY, "is_default");
```
GroupLoader::fetch() returns false when there is no match.
So, in [line 192](https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/controllers/UserController.php#L192):
```php
if (isset($default_groups[$group_id]) || $group_id == $primary_group->id)
```
$primary_group is not an object, giving an error.

(Sorry if isn't clear, I speak spanish)

**Comment by alexweissman** [comment]
Ahh, I see.  So if there is no default primary group defined at all, then we have a problem.  Actually, there should technically always be a default primary group defined, but of course this isn't enforced in the database itself.  So, maybe a check would be worthwhile.

**Comment by Aterbonus** [comment]
That is one solution. 
~~Other is give a warning message to the user to let him know there isn't a primary group...~~
Thinking better the check in the database will be better, and enforce one primary group (Now, we can set more than one primary group, but only one is retrieved thanks to fetch).

**Comment by alexweissman** [comment]
I'll look into it.  Also, we are changing the model for what we now call "groups" and "primary group" in 0.3.2, so this shouldn't be an issue in the long run.

**Comment by Aterbonus** [comment]
Ahh, I see. Looking forward for 0.3.2.

**Comment by alexweissman** [comment]
Ok, I've fixed this for now by adding an error message and logging to the error log.  In the future, these kind of "configuration errors" should probably get handled by Monolog (to automatically email an admin, for instance).
