### ISSUE TITLE
placing login form with script on public homepage (instead of separate route) is missing validators

### ISSUE THREAD

**Issue by leanpanda** [alexweissman/UserFrosting#418]
I recommend the following change to the controller so that twig can pass the validators to the javascript on the public home page as well

```php
public function pageHome(){

        $schema = new \Fortress\RequestSchema($this->_app->config('schema.path') . "/forms/login.json");
        $validators = new \Fortress\ClientSideValidator($schema, $this->_app->translator);
        
        
        $this->_app->render('common/home.html', [
            'page' => [
                'author' =>         $this->_app->site->author,
                'title' =>          "your title",
                'description' =>    "description",
                'alerts' =>         $this->_app->alerts->getAndClearMessages(), 
                'active_page' =>    "",
            ],
            'validators' => $validators->formValidationRulesJson()
         
        ]);  
    }

**Comment by alexweissman** [comment]
Why does the home page need the validation rules for the login page, though?  I think if people want to put their login form directly on the home page, they can figure this out ;-)

**Comment by alexweissman** [comment]
I've changed `dev` a bit so that a `ClientSideValidator` (now called `JqueryValidationAdapter`) can be globally registered with the `$app`.  So, this could make it easier to set `validators` as a global Twig variable, if desired.

**Comment by alexweissman** [comment]
closing!
