### ISSUE TITLE
 Postgresql 9.x

### ISSUE THREAD

**Issue by AndyLicht** [alexweissman/UserFrosting#419]
Hi,
is it planed to make UserFrosting useable with Postgres?
It would be a great feature, for people how working with databases, which needing postgis.

Thanks a lot for this great lib.
Andy

**Comment by alexweissman** [comment]
The data layer in the next version (0.3.1) will be built on Eloquent, [which does support Postgres](http://laravel.com/docs/5.1/database#introduction).  So, the answer is yes.

**Comment by neodisco** [comment]
Can you please comment on whether 0.3.1 ended up being Postgres compatible?
