### ISSUE TITLE
HHVM Compatibility issues

### ISSUE THREAD

**Issue by r3wt** [alexweissman/UserFrosting#424]
so problem arises in `MySQLDatabase::connection()` method. I think we should change line 29 from `echo` to `die()` as a temporary solution. otherwise the script never terminates until the fatal is thrown and the user never sees the message of db failure, because its captured (and discarded due to the fatal error) by Slim's Output Buffering.

**Comment by alexweissman** [comment]
Sounds good.  This won't be a problem in 0.3.1, since it uses exceptions to handle DB connection issues.

**Comment by alexweissman** [comment]
A'ight then.
