### ISSUE TITLE
css on non admin

### ISSUE THREAD

**Issue by joshblevins** [alexweissman/UserFrosting#428]
When I log in to my front end as a regular user the css layout is not working appropriately.

www.lmrnet.com/lifemedical/public/dashboard

user: garage
pass: garage5433

**Comment by alexweissman** [comment]
I'm getting a 404 error when I try to access that site.  Are you able to get UF working in your local environment?

**Comment by joshblevins** [comment]
Im working on a site 5 server

On Tuesday, October 20, 2015, Alex Weissman <notifications@github.com>
wrote:

> I'm getting a 404 error when I try to access that site. Are you able to
> get UF working in your local environment?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexweissman/UserFrosting/issues/428#issuecomment-149600573>
> .
>


-- 
Joshua Blevins EMT-P/FFII EMS-I
513-254-2369

**Comment by joshblevins** [comment]
http://lmrnet.com/lifemedical/public/              ---        Main home Page

http://lmrnet.com/lifemedical/public/dashboard#       ----    Main Login Page

after login it will not self redirect

**Comment by alexweissman** [comment]
For me, it's just giving me an infinite redirect loop.  Sounds like a configuration issue, possibly in your `.htaccess`.  

On another note, is there a reason you can't try this in a local dev environment first?  Developing on the live server is a really terrible idea.

**Comment by alexweissman** [comment]
Let us know if you're still having trouble.
