### ISSUE TITLE
Plugin considerations

### ISSUE THREAD

**Issue by r3wt** [alexweissman/UserFrosting#430]
A few issues here.

1. `includes.js.register` and `includes.css.register` both run before `plugins.register` is this intended so that plugins will have to manually apply their own hooks? if so, i guess that makes sense. Not a huge issue if you intend to leave it this way.

2. `includes.js.register` prepends supplied path with `js`. likewise, `includes.css.register` prepends `css` onto supplied path. this is a problem for plugins that wish to register a route to serve such content. in `UFchat`. 

I've resorted to the following work around:

```php
$app->schema->registerJS("common", "../UFchat/script");
```
suprisingly the browser allows this, but i think this is a terrible practice. its my assertion that we should remove the prepended path from both, so that developers will be free to serve plugins from their own registered routes.

**Comment by alexweissman** [comment]
agree with you on both counts.  I've fixed issue 1, issue 2 might be more complicated because of the built-in minification manager.

**Comment by r3wt** [comment]
looks like this is fixed and can be closed.
