### ISSUE TITLE
Default Login Page Tweak

### ISSUE THREAD

**Issue by rihlsul** [alexweissman/UserFrosting#431]
Just to be consistent, on home you have:  `<h1>Welcome to {{site.site_title}}!</h1>`

On login.html you have:   `<h1>Welcome to UserFrosting!</h1>`

Next release, maybe swap in the  `{{site.site_title}}`?

**Comment by alexweissman** [comment]
Good catch, thanks!

**Comment by Editandrew** [comment]
If we're working on home, I think the title should be adjustable from the admin panel.

**Comment by alexweissman** [comment]
It is!  Site title is the first setting...

**Comment by alexweissman** [comment]
It would appear that I actually already took care of this in `dev`!
