### ISSUE TITLE
Tutorial / Docs Adjustment: Composer

### ISSUE THREAD

**Issue by rihlsul** [alexweissman/UserFrosting#432]
I'm a noob to so, so very much of this.  I was trying to follow tutorial 3.  When I hit the composer update step, I was getting errors and could not find anything in the Documentation section.   

I was able to search through a lot of chat room history to find the suggestion Alex made on Oct 12 to remove the /vendor/alexweissman folder entirely before running.  That solved my problem, so perhaps adding that to the Composer page linked from Tutorial 3 would help people out.  Additionally, to the Troubleshooting section on creating a new class.

**Comment by alexweissman** [comment]
Thanks, that is a good idea.

**Comment by alexweissman** [comment]
Ok, I added this to the troubleshooting page.
