### ISSUE TITLE
"/install/ was not found on this server" + broken links

### ISSUE THREAD

**Issue by mckinnon** [alexweissman/UserFrosting#433]
I just spent some time chasing this down. (ref https://github.com/alexweissman/UserFrosting/issues/341)

When the the Installation guide[1] says 
> Find the block that looks like:
 `<Directory /blah/blah/blah/>`
`    Options Indexes FollowSymLinks`
`    AllowOverride None`
`    Require all granted`
`</Directory>`
> Change AllowOverride None to AllowOverride All.

The "/blah/blah/blah/" matters and there may be several blocks which match the above description (oops). It must be the public directory into which UserFrosting is being installed. 

i.e. for Ubuntu or RedHat, it will be 
`<Directory /var/www/>`
`        Options Indexes FollowSymLinks`
`        AllowOverride All`
`        Require all granted`
`</Directory>`
unless you used a non-default like /srv/www.

- - - 
Ref.
[1] UserFrosting's "Requirements and Installation", 21OCT2015. http://www.userfrosting.com/installation/

**Comment by alexweissman** [comment]
Ok, I added this to the installation guide.
