### ISSUE TITLE
i need help in my idea

### ISSUE THREAD

**Issue by mb202020** [alexweissman/UserFrosting#434]
Hello i have this table i want use it in user cake v2.0.2
CREATE TABLE `uc_blog` (
  `id` int(11) NOT NULL auto_increment,
  `userid` int(11) NOT NULL,
  `title` varchar(120) NOT NULL,
  `paragraph` varchar(120) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

how can i make page like blog.php
showing only his own blog posts by `userid`
Example: i am login now, my user id in usercake uc_users is  2  i want blog.php showing posts uc_blog  is `userid` have value 2

**Comment by r3wt** [comment]
Hi @mb202020 This question appears to be unrelated to UserFrosting. We are not responsible and don't provide support for UserCake.

**Comment by rihlsul** [comment]
I think the place for UserCake help is their forums?   http://usercake.com/forum.php ?

**Comment by alexweissman** [comment]
Yup, closed.
