### ISSUE TITLE
Warn user if config-userfrosting.php is missing

### ISSUE THREAD

**Issue by Netrilix** [alexweissman/UserFrosting#445]
The new default install uses `config-userfrosting-example.php` instead of `config-userfrosting.php`. This is a good idea because it forces users to examine the config file before they run the program for the first time. However, I think `index.php` should give a quick explanation of what to fill out in the config, and that they need to rename it to get rid of `-example`.

As it stands right now, an initial run of 0.3.1 will produce nothing but a PHP error page about missing a required include file, which is an ugly thing for a new user to see.

**Comment by alexweissman** [comment]
How about if we just link them to the updated installation guide?

**Comment by Netrilix** [comment]
That'd probably be sufficient if you can add an anchor at Step 4: Create Database and Setup Configuration File and link directly to it.

**Comment by alexweissman** [comment]
Ok, added in hotfix 0.3.1.4.
