### ISSUE TITLE
Dutch error in translations

### ISSUE THREAD

**Issue by Editandrew** [alexweissman/UserFrosting#447]
"ACCESS_DENIED" => "Hmm, het **lijtk** erop dat je geen toestemming hebt om deze pagina te bekijken.",
Should be
"ACCESS_DENIED" => "Hmm, het **lijkt** erop dat je geen toestemming hebt om deze pagina te bekijken.",

**Comment by alexweissman** [comment]
Fixed in 0.3.1.4.
