### ISSUE TITLE
Can't connect page and "The configuration table could not be loaded." in the httpd error_log

### ISSUE THREAD

**Issue by cvpsmith** [alexweissman/UserFrosting#452]
Well, I thought I finally had all of the requirements installed properly (getting php-5.4+extensions on RHEL6 is a PITA!), but when I load the page, I get the "Can't connect to the database" page.  I've set up MySQL properly with a "userfrosting" user and database, and I've double-checked and I know that the password is correct.  I get this in my httpd/error_log:

[Wed Nov 04 21:42:13 2015] [error] [client 170.253.166.190] The configuration table could not be loaded.  Falling back to default configuration settings.
[Wed Nov 04 21:42:13 2015] [error] [client 170.253.166.190] Unable to authenticate user, falling back to guest user.
[Wed Nov 04 21:42:13 2015] [error] [client 170.253.166.190] #0 /var/www/html/userfrosting/vendor/illuminate/database/Connectors/Connector.php(47): PDO->__construct('mysql:host=127....', 'userfrosting', 'p@ssw0rd', Array)\n#1 /var/www/html/userfrosting/vendor/illuminate/database/Connectors/MySqlConnector.php(20): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=127....', Array, Array)\n#2 

Then, later on, it tries to connect with the password "YES" for some reason:

[Wed Nov 04 21:42:13 2015] [error] [client 170.253.166.190] Error in /var/www/html/userfrosting/vendor/illuminate/database/Connectors/Connector.php on line 47: SQLSTATE[HY000] [1045] Access denied for user 'userfrosting'@'localhost' (using password: YES)
[Wed Nov 04 21:42:13 2015] [error] [client 170.253.166.190] #0 /var/www/html/userfrosting/vendor/illuminate/database/Connectors/Connector.php(47): PDO->__construct('mysql:host=127....', 'userfrosting', 'd@than01', Array)\n#1 /var/www/html/userfrosting/vendor/illumin...

I have php54-php-pdo installed and I've checked all of the other requirements as well.  Any ideas?

Thanks in advance,

Paul

**Comment by Netrilix** [comment]
The `(using password: YES)` is actually just MySQL telling you that it's using a password to connect. It won't send the actual password to your error logs.

Did you ensure you edited the correct lines in `config-userfrosting.php`? There's a set of database settings for both production and dev.

**Comment by cvpsmith** [comment]
Thanks for the info.  I finally traced the issue down to MySQL.  Now, when I go to /public, it redirects to /public/install/? and gives the following error:

Not Found
The requested URL /public/install/ was not found on this server.

I checked the public directory, and there isn't even an "install" directory in there.  Nor is there one in the "userfrosting" directory...

**Comment by cvpsmith** [comment]
And this comes up in httpd/error_log:

[Thu Nov 05 10:37:43 2015] [error] [client x.x.x.x] File does not exist: /var/www/html/public/install

**Comment by cvpsmith** [comment]
It looks like it's coming from here in public/index.php:

    /************ INSTALLER *************/

    $app->get('/install/?', function () use ($app) {
        $controller = new UF\InstallController($app);
        if (isset($app->site->install_status)){

Do I have a bad version or something?  TIA...

**Comment by Netrilix** [comment]
No, it sounds like you don't have `mod_rewrite` enabled in Apache.

Mod_rewrite is what directs things like /install/ to the `$app` router in `index.php`.

**Comment by cvpsmith** [comment]
That was it.  mod_rewrite was on, but I had to make sure that "AllowOveride All" was also set for the /var/www/html directory...  Thanks for the help!  Now I'm "ready to rock."!

**Comment by Netrilix** [comment]
Good to hear, glad I could help.
