### ISSUE TITLE
Morris graph JavaScript errors and halts JavaScript if no Graph container is found

### ISSUE THREAD

**Issue by Netrilix** [alexweissman/UserFrosting#455]
If a developer extends the dashboard code (by using the `dashboard` page group), the dashboard's JavaScript tries to load the Morris Graph functions to make the nice-looking dashboard. If their code doesn't include a graph container, the JavaScript errors and halts (meaning no further js is executed).

The dashboard code should look for graph containers before calling the Morris graph code.

**Comment by alexweissman** [comment]
Ok, I fixed this by moving this code (which is demo code anyway) to the specific page.  (v0.3.1.5)
