### ISSUE TITLE
Route to config.js should be configurable

### ISSUE THREAD

**Issue by cmy82** [alexweissman/UserFrosting#461]
I installed 0.3.1.4 the other day fresh, and any POST functions (login,register,resend auth email) do not work and all return Error 403 Forbidden and the console says 'Site undefined'. I had 0.3.0 installed before and it worked no issues, but I can't seem to get 0.3.1.4 to cooperate. If I hit enter again in the address bar, the login page works fine, as well as the register (though no email was sent). But I cant figure out why the request has to be sent a second time. Also, how do I update the SMTP settings once i've installed? Is it as easy as editing the config file?

**Comment by alexweissman** [comment]
Did you migrate your database over to the new 0.3.1 format?

**Comment by cmy82** [comment]
It was a completely fresh install. I deleted all of the databases as well as files. It also behaved the same way on install and created the admin account though it hung on the install page.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: Alex WeissmanSent: Tuesday, November 10, 2015 2:52 PMTo: alexweissman/UserFrostingReply To: alexweissman/UserFrostingCc: Chris MyersSubject: Re: [UserFrosting] Unauthenticated POST functions not working (#461)Did you migrate your database over to the new 0.3.1 format?

—Reply to this email directly or view it on GitHub.

**Comment by alexweissman** [comment]
Ok, I need more information so we can attempt to replicate the problem (everything works fine for me).  What server/OS are you using?  Are you getting any errors in the PHP error log?  What about in your web server log?  What browser are you using?  Can you show me a screenshot of your browser console with that error message?

**Comment by cmy82** [comment]
I will post it later tonight                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.

**Comment by cmy82** [comment]
Here is the console output from the login page. I am using a hosted server that has Apache and Nginx running from my checking. No errors show in the PHP log when the POST fails (except for the email). I am using Firefox v41 (but it also fails on my phone and in IE11). I have not checked the errors on my web server as I don't know how cause I've never had to check them. 

![uf-login-console_dump](https://cloud.githubusercontent.com/assets/3430711/11083049/bf5823a8-87f8-11e5-9cd2-2897cf88309a.png)
[uf-login-console_dump.txt](https://github.com/alexweissman/UserFrosting/files/31519/uf-login-console_dump.txt)

**Comment by cmy82** [comment]
Here is the log data from the install:


[04-Nov-2015 02:57:19 America/New_York] Installing

[04-Nov-2015 02:57:19 America/New_York] Done with checks

[04-Nov-2015 02:57:19 America/New_York] Checking any current tables

[04-Nov-2015 02:57:19 America/New_York] Checking db connection

[04-Nov-2015 02:57:19 America/New_York] Checking php version

[04-Nov-2015 02:57:19 America/New_York] The configuration table could not be loaded.  Falling back to default configuration settings.

[04-Nov-2015 02:57:18 America/New_York] The configuration table could not be loaded.  Falling back to default configuration settings.

**Comment by alexweissman** [comment]
Can you confirm that the `config.js` asset is being loaded?

**Comment by cmy82** [comment]
nope, I have the same message that some others posted where it is missing

**Comment by alexweissman** [comment]
Well, looks like in your dump you've got:
`http://grocerebuddy.backroomsoftwarellc.com/account/scripts/uf/config.js [HTTP/1.1 404 Not Found 390ms]`

So, `config.js` is the "virtual JS file" that generates the JS `site` variable.  Without that, the browser doesn't know what the public URL is for your site, and thus doesn't know where to forward you after it logs you in, registers, etc.

I suspect this has something to do with your `.htaccess` or other configuration file.

**Comment by cmy82** [comment]
So, is config.js auto-generated on install? Cause on install I get an error in the console that says site not defined as well as the config.js file missing.

**Comment by alexweissman** [comment]
No, it is "generated" on every request.  It's not an actual file.  It's really just a path to a route that dynamically generates a response with a Javascript header and commands.

**Comment by alexweissman** [comment]
Take a look for yourself: https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/controllers/BaseController.php#L52-L70

**Comment by cmy82** [comment]
Ok. If that were missing though, would it not break the whole site, and not just the login/register redirects? Was that file/routing in use with 0.3.0? Just trying to figure out where to start. I emailed my hosting provider and had them enable AllowOverride All on my web directory, but still getting error. Though I don't know how to check whether it is set.

**Comment by alexweissman** [comment]
Nah, it would only break pages that use `site['uri']['public']`in Javascript.
Go ahead and join us in chat some time tomorrow, and we'll try to get to the bottom of this.  We'll need to know about any changes you've made to the default `.htaccess`, as well as your server directory structure.

Are you able to get v0.3.1 to work locally at least?

**Comment by cmy82** [comment]
Ok, i'll have all of that ready. Haven't tried it locally

**Comment by cmy82** [comment]
I figured out the problem after you showed me how the config.js file is generated.

You have the path for it hardcoded:

    // JS Config
    $app->get('/js/config.js', function () use ($app) {
        $controller = new UF\BaseController($app);
        $controller->configJS();
    });

So if you have your JS files in a different location than the standard **/{public dir}/js/{file}** location then it will not find the config file because of the hardcoded **$app->get(....)**. If you change the location of the JS directory then you will need to find this block in the index.php file and correct it to match your JS directory.

For me and I think this would be a good way to update the config file (not sure why you have **$public_path** and not **__DIR__** like every other config option) is to add a config option **"js.intpath" => __DIR__ . "/your/js/path"**.

**Comment by alexweissman** [comment]
This is strange, though.  Remember, it doesn't actually need to reference the `js` directory when it generates `js/config.js`.  The `.htaccess`, or whatever configuration file, should be forwarding requests for `js/config.js` directly to `index.php`, where it is then handled by this route.  So, it shouldn't even care if there is actually a directory named `js`!

But, it's working now?

**Comment by cmy82** [comment]
Yes, it's working. From what I get it would matter because of how the get function works. It translates everything with respect to the directory where index.php is located. So if it's saying to look for route {site.uri}/js/config.js but your actual site has {site.uri}/scripts/js/config.js it will never find the file because the route is wrong.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: Alex WeissmanSent: Wednesday, November 11, 2015 9:15 AMTo: alexweissman/UserFrostingReply To: alexweissman/UserFrostingCc: Chris MyersSubject: Re: [UserFrosting] Unauthenticated POST functions not working (#461)This is strange, though.  Remember, it doesn't actually need to reference the js directory when it generates js/config.js.  The .htaccess, or whatever configuration file, should be forwarding requests for js/config.js directly to index.php, where it is then handled by this route.  So, it shouldn't even care if there is actually a directory named js!

But, it's working now?  

—Reply to this email directly or view it on GitHub.

**Comment by cmy82** [comment]
Not sitting in front of the pc right now, but I think the configJS() function references the js.path uri when it generates the file references, so the get has to look in the same route.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.

**Comment by alexweissman** [comment]
Fixed in https://github.com/alexweissman/UserFrosting/commit/8310c13890530f0eb75f13e104fff2fad61315c9.  You can now modify the `js-relative` and `css-relative` variables in the configuration file.  Thanks for helping us find this bug!
