### ISSUE TITLE
Can't edit users

### ISSUE THREAD

**Issue by desynergy** [alexweissman/UserFrosting#49]
Hi guys.  Like the script so far.  But after testing and playing with it, I found that I couldnt edit users.  

When I click the drop down box, and choose Edit User, I get the error:
Oops, looks like our server might have goofed. If you're an admin, please check the PHP error logs.

I check the logs, and nothing is showing up except a bunch of:
[Thu Jun 05 17:16:52 2014] [error] [client XX.XXX.XXX.XX] PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function.

I even tried a fresh install to make sure it wasnt anything I messed up while playing with the code.   

-sh-4.1$ php -v
PHP 5.4.29 (cli) (built: Jun  1 2014 19:30:18)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with the ionCube PHP Loader v4.4.1, Copyright (c) 2002-2013, by ionCube Ltd.

**Comment by tyl3r** [comment]
Sorry for the delay, very busy day..., i just want to say thanks for the fix, that was fast!
