### ISSUE TITLE
Auto-logout

### ISSUE THREAD

**Issue by alexweissman** [alexweissman/UserFrosting#66]
Found this: https://stackoverflow.com/questions/520237/how-do-i-expire-a-php-session-after-30-minutes.  I think this would be pretty easy to implement, just put the code in `config.php` and have the timeout period be another site configuration variable.

An API page could be built if we want some kind of frontend alert when the system is about to log itself out.

**Comment by hannuheljala** [comment]
Is there already somekind of autologout implemented in UserFrosting 0.2.1? If I'm inactive for a while, I get automatically logged out. Or is this "server side issue"? Thanks!

**Comment by alexweissman** [comment]
It's a server issue.  Basically, PHP has a couple of different janky settings that control session lifetime, and depending on your server's configuration it can be tricky to figure out which one is causing the problem.  On top of that, if you have multiple PHP applications running on the same server, they can share a common path for storing sessions.  So what will happen is, one application will "clean up" the sessions from another application.

See Issue #228, and also the top answer here: http://stackoverflow.com/questions/520237/how-do-i-expire-a-php-session-after-30-minutes.  Ultimately, we will need to implement our own session-persistence, possibly using this: http://jaspan.com/improved_persistent_login_cookie_best_practice

**Comment by alexweissman** [comment]
This is handled in 0.3.1 with persistent sessions.  A configuration option might still be worth implementing, though.

**Comment by alexweissman** [comment]
Implemented in 0.3.1.  If anyone is still interested in the "auto-logout" (now that remember-me is implemented), go ahead and open a new issue.  Please note, by auto-logout I mean something like:

![mint autologout](http://i.stack.imgur.com/jVn1L.gif)
