### ISSUE TITLE
Cant edit users 

### ISSUE THREAD

**Issue by salmanshahh** [alexweissman/UserFrosting#86]
If we try to edit the user email address from the dashboard, it shows invalid address. Also if you try to delete user. It says 

Oops, looks like our server might have goofed. If you're an admin, please check the PHP error logs.

**Comment by githubsrinath** [comment]
It happens to me when i log in every time.  

First it says
Oops, looks like our server might have goofed. If you're an admin, please check the PHP error logs.

Then when i press login again...
It says "You're already logged in!"

Then it will never go inside to view dashboard....

Then i forcefully remove from login.php from http://myserver/login.php   it will login and show the dashboard view....

As recommended , i have changed config.php to have 
date_default_timezone_set('America/New_York');

Still issue persist.

Your help is greatly appreciated.

Thanks

**Comment by alexweissman** [comment]
Any chance you'd be able to upgrade to 0.3.0?
