### ISSUE TITLE
Tables should have an optional prefix during setup

### ISSUE THREAD

**Issue by SpringsTea** [alexweissman/UserFrosting#878]
First time using UserFrosting, I am going through the setup and I hit this error:

`[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'slug'. (SQL: select top 1 * from [roles] where [slug] = user)`

I assume this error is happening because there is already a table named `roles` on the DB I'm trying to install onto. My roles table is completely unrelated to what I'm doing with UserFrosting. So from what I can tell, aside from putting this on another database (separating me from the data I need in my app), I'm out of luck as is.

I think having the option to prefix UserFrosting tables on setup to avoid conflicting table names makes a lot of sense.

**Comment by SpringsTea** [comment]
I did not realize you could edit configs before baking, sorry for the trouble.

**Comment by alexweissman** [comment]
I should point out though, that the table prefix setting is going to be global to your entire UF application. So, if you use a table prefix (e.g. `uf_`) in your config, it's going to create all the tables with the prefix, but it's also going to try to access all tables for which you've created a model, with that same prefix.

So if you have have a model associated with your (unrelated) `roles` table, it would still try to reference `uf_roles`, not `roles`.

If your `roles` table is going to be a part of your UserFrosting application, you really ought to rename it to something else.

**Comment by SpringsTea** [comment]
Thanks for the heads up. I'm only using UF for the user management, I'll access data unrelated to users without my own models then.
